### ISSUE TITLE
生产事故？

### ISSUE THREAD

**Issue by Char-CN** [alibaba/DataX#1]
怎么只有几个Star了？

**Comment by jiangnanrusheng** [comment]
估计是代码合并的时候冲突了，解决不了，好几天了 o(╯□╰)o

**Comment by CaoYusong** [comment]
要等几天啊  啊啊 啊 阿啊 啊啊 啊 啊 去啊啊 阿啊  阿

**Comment by windcaller31** [comment]
官方的人呢，给个时间啊，最近想用突然就下线了

**Comment by zuoyedalaohu** [comment]
程序员 你摊上大事了！！！！

**Comment by huakl** [comment]
在线等，急

**Comment by leven-space** [comment]
+1

**Comment by WenYixin** [comment]
哎哟喂文档别丢啊，要了亲命了。。

**Comment by obarong** [comment]
估计是意外开源了一些机密文件，现在要全部收回去

**Comment by drag0nglass** [comment]
怎么清得这么干净？！
好在早先看的时候顺手Fork了一份，急用的同学传送门：https://github.com/drag0nglass/DataX
只有源码，Wiki的部分Fork的时候没有带着。。。

**Comment by huakl** [comment]
楼上好人一生平安。

**Comment by Arvin-Mark** [comment]
----
> **DataX 是异构数据广泛使用的离线数据同步工具/平台，实现包括 MySQL、Oracle、SqlServer、Postgre、HDFS、Hive、ADS、HBase、OTS、ODPS 等各种异构数据源之间高效的数据同步功能。  **
----
* [https://github.com/Arvin-Mark/DataX-src](https://github.com/Arvin-Mark/DataX-src)
* [https://github.com/Arvin-Mark/datax-bin](https://github.com/Arvin-Mark/datax-bin)

**Comment by windcaller31** [comment]
这个怎么配置增量同步，脚本没有啦

**Comment by thinkpad-e550c** [comment]
文档没了，怎么搞，文档别丢呀
