### ISSUE TITLE
能否实现 配合cannal做增量同步的功能

### ISSUE THREAD

**Issue by boboChina** [alibaba/DataX#100]
RT，感谢解答一下

**Comment by boboChina** [comment]
顶一下，个人已经开始尝试编码了，期望官方也关注下这个思路

**Comment by xw24004** [comment]
我们这边也有一个实时的需求，打算和cancel对接的，不知道你那边做的怎样了？

**Comment by boboChina** [comment]
近期会开源，我的做法已经和datax没什么关系了，源码提交了回头我来通知下
