### ISSUE TITLE
oraclereader和mysqlreader作为reader,rdbmswriter写入db2报错

### ISSUE THREAD

**Issue by sunnyshuosun** [alibaba/DataX#1030]
streamreader到rdbmswriter写入到db2数据库没有问题。
    但是oracel和mysql作为reader,rdbmswriter写入db2数据库报错，报无法连接数据库，具体报错如下“2021-05-31 11:19:56.401 [job-0] ERROR RetryUtil - Exception when calling callable, 异常Msg:Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].  -  具体错误信息为：java.sql.SQLException: No suitable driver found for  jdbc:db2://IP:port/database”。rdbmswriter中的plugin.json和libs目录已经写入db2的驱动。
    同时rdbmsreader中db2作为reader可以正常读取，mysqlwriter可以正常写入。

**Comment by aa-yii** [comment]
我也碰到这个问题

**Comment by you10906** [comment]
我也碰到了同样的问题。。。
从达梦到DB2正常，但是从postgresql到DB2报错
`ERROR RetryUtil - Exception when calling callable, 异常Msg:Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].  -  具体错误信息为：java.sql.SQLException: No suitable driver found for jdbc:db2://xxx.xxx.xxx.xxx:50000/testdb`

**Comment by you10906** [comment]
> 我也碰到了同样的问题。。。
> 从达梦到DB2正常，但是从postgresql到DB2报错
> `ERROR RetryUtil - Exception when calling callable, 异常Msg:Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).]. - 具体错误信息为：java.sql.SQLException: No suitable driver found for jdbc:db2://xxx.xxx.xxx.xxx:50000/testdb`

我将db2jcc4.jar复制到datax/lib目录后可以正常同步，不再报错

**Comment by you10906** [comment]
@aa-yii @sunnyshuosun 

> 我也碰到了同样的问题。。。
> 从达梦到DB2正常，但是从postgresql到DB2报错
> `ERROR RetryUtil - Exception when calling callable, 异常Msg:Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).]. - 具体错误信息为：java.sql.SQLException: No suitable driver found for jdbc:db2://xxx.xxx.xxx.xxx:50000/testdb`

我将db2jcc4.jar复制到datax/lib目录后可以正常同步，不再报错

**Comment by philipf-chen** [comment]
rdbmswriter中jdbcUrl参数不能是List，
"jdbcUrl": ["jdbc:sap://172.18.209.131:30215" ] -- 错误
"jdbcUrl": "jdbc:sap://172.18.209.131:30215"  -- 正确

**Comment by TrafalgarLuo** [comment]
@keith-ch 给出的答案是正确的
