### ISSUE TITLE
Datax 设置mysql 8.0 导入mysql 8.0 时报错。无法创建连接。

### ISSUE THREAD

**Issue by shuanger051** [alibaba/DataX#1062]
备注：已检查N遍，账号密码没有问题，已将datax-admin的lib下的mysql5.17jar包替换为mysql8.0.21.jar。

com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].  - 数据库连接失败. 因为根据您配置的连接信息,无法从:jdbc:mysql://47.96.229.76:3306/data_bridge 中找到可连接的jdbcUrl. 请检查您的配置并作出修改. - java.lang.Exception: DataX无法连接对应的数据库，可能原因是：1) 配置的ip/port/database/jdbc错误，无法连接。2) 配置的username/password错误，鉴权失败。请和DBA确认该数据库的连接信息是否正确。
2021-07-03 04:36:49 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.alibaba.datax.plugin.rdbms.util.DBUtil$2.call(DBUtil.java:71)

**Comment by shuanger051** [comment]
已解决。

**Comment by jackchina** [comment]
> 已解决。

怎么解决的？碰到和你一样的问题

**Comment by Galthen** [comment]
> > 已解决。
> 
> 怎么解决的？碰到和你一样的问题

我估计楼主是修改错了地方，应该修改plugin-rdbms-util下的mysql依赖版本。不过看最新的代码，Datax已经自己把mysql驱动版本更新到8.0.16了。

**Comment by shuanger051** [comment]
@jackchina @Galthen 是滴，两个lib都是需要改的。plugin下面那个不改，程序启动会报驱动错误。admin下面的lib下面不改的话，界面TEST CONNECTION 会报错，所以两个都需要改下。

**Comment by hermitcai** [comment]
有谁试过读取使用8.0的版本 写入使用5.7的版本吗

**Comment by bingfenglai** [comment]
遇到一样的问题，请问两个修改的地方具体是哪里？

**Comment by dingxiaobo** [comment]
DataX 现已支持，欢迎使用新版本

**Comment by jishaofeng89** [comment]
解决个锤子哦，我下载下来mysqlreader插件里面还是5.1.47

**Comment by EricMo** [comment]
这是裁员裁走了吗？现在看都还是5.x不是8.x

**Comment by dingxiaobo** [comment]
@jishaofeng89 5.1.47 driver 可以连接 8.0 server
