### ISSUE TITLE
下载源码包解压报错

### ISSUE THREAD

**Issue by tangxin1121** [alibaba/DataX#1069]
下载源码包，解压时报错 ：
“
压缩文件格式未知或者数据已经损坏	
DataX-master\oceanbasev10writer\src\main\libs\oceanbase-connector-java-3.2.0.jar
”

**Comment by myownsword** [comment]
遇到同样的问题  请问解决了吗

**Comment by TrafalgarLuo** [comment]
可以下载最新的产生看下，地址： https://datax-opensource.oss-cn-hangzhou.aliyuncs.com/20220530/datax.tar.gz

在 https://github.com/alibaba/DataX 也可以找到最新地址（不定期更新）。
