### ISSUE TITLE
为什么直接下载的dataX解压后没有clickhouseWriter插件，我应该去哪里下载

### ISSUE THREAD

**Issue by blue0305** [alibaba/DataX#1079]
为什么直接下载的dataX解压后没有clickhouseWriter插件，我应该去哪里下载

**Comment by zhbdesign** [comment]
> 为什么直接下载的dataX解压后没有clickhouseWriter插件，我应该去哪里下载

[https://pan.baidu.com/s/1GmIDU3ZTDHroIl24vwiQjg](url)
提取码：j57q
我有打包好的，下载使用把

**Comment by XuDaojie** [comment]
直接下载的包是一个上古版本，所有没有，最新的要自己编译

**Comment by baisui1981** [comment]
基于DataX构建了一个数据导入的pipeline，简化了安装流程针对clickhouse 导入开箱即用特别好用 可以尝试一下[http://tis.pub/docs/enhance-extra/](http://tis.pub/docs/enhance-extra/)

视频教程：[https://www.bilibili.com/video/BV1x64y1B7V8/](https://www.bilibili.com/video/BV1x64y1B7V8/)

**Comment by Galthen** [comment]
![image](https://user-images.githubusercontent.com/16739927/165689901-62f70ff1-541f-464f-a120-00bc3c547794.png)
我加了几个数据源，有需要自取。

**Comment by dingxiaobo** [comment]
DataX master 现已支持，可以获取新版本
