### ISSUE TITLE
mongo读clickhouse写前后数据总数不一致

### ISSUE THREAD

**Issue by yuhaiyangsay** [alibaba/DataX#1082]
mongo库里有50000条数据，日志记录读到的总数也是这么多，但是写入到clickhouse后数据总数多1000多条，重复同步clickhouse里的总数依旧是这个值不会随机改变

**Comment by zhbdesign** [comment]
> mongo库里有50000条数据，日志记录读到的总数也是这么多，但是写入到clickhouse后数据总数多1000多条，重复同步clickhouse里的总数依旧是这个值不会随机改变

ck是什么表引擎,dataX显示写入多少条,ck数据库是多少条

**Comment by yuhaiyangsay** [comment]
> > mongo库里有50000条数据，日志记录读到的总数也是这么多，但是写入到clickhouse后数据总数多1000多条，重复同步clickhouse里的总数依旧是这个值不会随机改变
> 
> ck是什么表引擎,dataX显示写入多少条,ck数据库是多少条

ck是MergeTree引擎，dataX显示读写50000条，ck写入51672
![image](https://user-images.githubusercontent.com/53259435/129820904-f552eea1-87ef-4fc0-a785-85acaf6c880a.png)

**Comment by yuhaiyangsay** [comment]
> > mongo库里有50000条数据，日志记录读到的总数也是这么多，但是写入到clickhouse后数据总数多1000多条，重复同步clickhouse里的总数依旧是这个值不会随机改变
> 
> ck是什么表引擎,dataX显示写入多少条,ck数据库是多少条

找到原因了，mongo每条记录里都包含document，document又包含数组，transformer把mongo的每一条记录按数组扩展成多条写入ck
