### ISSUE TITLE
3.0源码编译hbase11xsqlreader 0.0.1-SNAPSHOT失败！

### ISSUE THREAD

**Issue by joson1205** [alibaba/DataX#1087]
Tests in error:
  testParseConfig(com.alibaba.datax.plugin.reader.hbase11xsqlreader.HbaseSQLHelperTest): Code:[Hbasewriter-02], Description:[获取phoenix表的列值错误]. - HBase的columns配置不能为空,请添加目标表的列名配置.org.apache.hadoop.hbase.client.RetriesExhaustedException: Can't get the locations - java.sql.SQLException: or(..)ache.hadoop.hbase.client.RetriesExhaustedException: Can't get the locations
  testSplit(com.alibaba.datax.plugin.reader.hbase11xsqlreader.HbaseSQLHelperTest): Code:[Hbasewriter-02], Description:[获取phoenix表的列值错误]. - HBase的columns配置不能为空,请添加目标表的列名配置.org.apache.hadoop.hbase.client.RetriesExhaustedException: Can't get the locations - java.sql.SQLException: org.apac(..)adoop.hbase.client.RetriesExhaustedException: Can't get the locations
  testReadRecord(com.alibaba.datax.plugin.reader.hbase11xsqlreader.HbaseSQLReaderTaskTest): Code:[Hbasewriter-02], Description:[获取phoenix表的列值错误]. - HBase的columns配置不能为空,请添加目标表的列名配置.org.apache.hadoop.hbase.client.RetriesExhaustedException: Can't get the locations - java.sql.SQLException:(..).apache.hadoop.hbase.client.RetriesExhaustedException: Can't get the locations

Tests run: 3, Failures: 0, Errors: 3, Skipped: 0

**Comment by zhbdesign** [comment]
> Tests in error:
> testParseConfig(com.alibaba.datax.plugin.reader.hbase11xsqlreader.HbaseSQLHelperTest): Code:[Hbasewriter-02], Description:[获取phoenix表的列值错误]. - HBase的columns配置不能为空,请添加目标表的列名配置.org.apache.hadoop.hbase.client.RetriesExhaustedException: Can't get the locations - java.sql.SQLException: or(..)ache.hadoop.hbase.client.RetriesExhaustedException: Can't get the locations
> testSplit(com.alibaba.datax.plugin.reader.hbase11xsqlreader.HbaseSQLHelperTest): Code:[Hbasewriter-02], Description:[获取phoenix表的列值错误]. - HBase的columns配置不能为空,请添加目标表的列名配置.org.apache.hadoop.hbase.client.RetriesExhaustedException: Can't get the locations - java.sql.SQLException: org.apac(..)adoop.hbase.client.RetriesExhaustedException: Can't get the locations
> testReadRecord(com.alibaba.datax.plugin.reader.hbase11xsqlreader.HbaseSQLReaderTaskTest): Code:[Hbasewriter-02], Description:[获取phoenix表的列值错误]. - HBase的columns配置不能为空,请添加目标表的列名配置.org.apache.hadoop.hbase.client.RetriesExhaustedException: Can't get the locations - java.sql.SQLException:(..).apache.hadoop.hbase.client.RetriesExhaustedException: Can't get the locations
> 
> Tests run: 3, Failures: 0, Errors: 3, Skipped: 0


hi，这是我用百度网盘分享的内容~复制这段内容打开「百度网盘」APP即可获取 
链接:https://pan.baidu.com/s/1KjXX8CNoMhNsMcQtkK2pfg 
提取码:28z3，我有打包好的

**Comment by TrafalgarLuo** [comment]
已经解决过类似问题，可以参考最新的代码push。 编译命令：
mvn clean package -U -DskipTests assembly:assembly

**Comment by wangxiang93** [comment]
Tests in error:
testParseConfig(com.alibaba.datax.plugin.reader.hbase11xsqlreader.HbaseSQLHelperTest): Code:[Hbasewriter-02], Description:[获取phoenix表的列值错误]. - HBase的columns配置不能为空,请添加目标表的列名配置.org.apache.hadoop.hbase.client.RetriesExhaustedException: Can't get the locations - java.sql.SQLException: or(..)ache.hadoop.hbase.client.RetriesExhaustedException: Can't get the locations
testSplit(com.alibaba.datax.plugin.reader.hbase11xsqlreader.HbaseSQLHelperTest): Code:[Hbasewriter-02], Description:[获取phoenix表的列值错误]. - HBase的columns配置不能为空,请添加目标表的列名配置.org.apache.hadoop.hbase.client.RetriesExhaustedException: Can't get the locations - java.sql.SQLException: org.apac(..)adoop.hbase.client.RetriesExhaustedException: Can't get the locations
testReadRecord(com.alibaba.datax.plugin.reader.hbase11xsqlreader.HbaseSQLReaderTaskTest): Code:[Hbasewriter-02], Description:[获取phoenix表的列值错误]. - HBase的columns配置不能为空,请添加目标表的列名配置.org.apache.hadoop.hbase.client.RetriesExhaustedException: Can't get the locations - java.sql.SQLException:(..).apache.hadoop.hbase.client.RetriesExhaustedException: Can't get the locations

Tests run: 3, Failures: 0, Errors: 3, Skipped: 0 这个咋解决啊

**Comment by marker-wu** [comment]
> 已经解决过类似问题，可以参考最新的代码push。 编译命令： mvn clean package -U -DskipTests assembly:assembly

用这个命令打包还是失败了
![image](https://github.com/alibaba/DataX/assets/45256940/ae8b21c7-84d7-4b3b-bc5a-f0b5ca996951)
