### ISSUE TITLE
ob writer连接泄露问题

### ISSUE THREAD

**Issue by JacksonWang6** [alibaba/DataX#1094]
datax ob writer ConcurrentTableWriterTask写入数据时，每个batch会创建一个连接，但是在写入完成时，没有释放，会导致连接数随着写入不断上涨。

**Comment by JiangWen002** [comment]
这个问题现在什么进展，我这边Greenplum 也出现了类似问题，datx任务建立的连接不释放，导致连接数溢出，DB崩溃

**Comment by JacksonWang6** [comment]
> 这个问题现在什么进展，我这边Greenplum 也出现了类似问题，datx任务建立的连接不释放，导致连接数溢出，DB崩溃

ob writer插件的连接泄漏的bug我找到了，但是Greenplum就不清楚了
