### ISSUE TITLE
java.sql.SQLException: No suitable driver found

### ISSUE THREAD

**Issue by wanghun315** [alibaba/DataX#120]
当前版貌似有个bug，当writer为mysqlwriter时，json中的jdbcUrl会报错，错误信息为：No suitable driver found，错误位置是在DBUtil.java的第392行DriverManager.getConnection的第一个参数没有去除[""]，但是mysqlreader没有问题，好奇怪。

**Comment by Matiz7** [comment]
那改配置能变通过去吗

**Comment by codercg2** [comment]
MysqlWriter类第52行错了，jdbcUrl不应该定义为List类型，应该是String类型

**Comment by d495435207** [comment]
我要是这么写吧报错 :java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List

"connection": [
  {
      "jdbcUrl": "jdbc:mysql://127.0.0.1:3306/autoee_v3",
      "table": [
          "ac_form_config_copy"
      ]
  }
]
我要是这么写吧:就报java.sql.SQLException: No suitable driver found for

"connection": [
  {
      "jdbcUrl": ["jdbc:mysql://127.0.0.1:3306/autoee_v3"],
      "table": [
          "ac_form_config_copy"
      ]
  }
]
一脸蒙逼状.... 怎么办? 挺急的 在线等!!

**Comment by d495435207** [comment]
找到问题原因了. MysqlWriter 目标这么写
`
"connection": [
{
"jdbcUrl": "jdbc:mysql://127.0.0.1:3306/autoee_v3",
"table": [
"ac_form_config_copy"
]
}
`
然后我MysqlReader 里的querySql里写成了这样.
`
"querySql": "[select * from table ]",
`
一致纠结在MysqlWriter里的jdbcUrl,有时候应该换个思路去检查别的地方也许问题就迎刃而解了,
(怕有人没明白再写一次正确的)
`
"querySql": ["select * from table "],
`
具体json怎么写,该是string还是list还是要去参考[官方文档](https://github.com/alibaba/DataX/blob/master/mysqlreader/doc/mysqlreader.md).

**Comment by TrafalgarLuo** [comment]
@d495435207  反馈的方案是对的
