### ISSUE TITLE
build 失败：错误: 对Record的引用不明确

### ISSUE THREAD

**Issue by dingbo8128** [alibaba/DataX#1212]
[INFO] datax-core ......................................... FAILURE [  1.179 s]
[INFO] plugin-rdbms-util .................................. SKIPPED
[INFO] mysqlreader ........................................ SKIPPED
[INFO] odpsreader ......................................... SKIPPED
[INFO] plugin-unstructured-storage-util ................... SKIPPED
[INFO] txtfilereader ...................................... SKIPPED
[INFO] streamreader ....................................... SKIPPED
[INFO] rdbmsreader ........................................ SKIPPED
[INFO] opentsdbreader ..................................... SKIPPED
[INFO] odpswriter ......................................... SKIPPED
[INFO] txtfilewriter ...................................... SKIPPED
[INFO] streamwriter ....................................... SKIPPED
[INFO] adswriter .......................................... SKIPPED
[INFO] rdbmswriter ........................................ SKIPPED
[INFO] tdenginewriter ..................................... SKIPPED
[INFO] tdenginereader ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  26.749 s
[INFO] Finished at: 2021-11-08T16:03:05+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project datax-core: Compilation failure: Compilation failure:
[ERROR] \Users\bo\dev\DataX\core\src\main\java\com\alibaba\datax\core\transport\transformer\FilterTransformer.java:[20,27] 错误: 对Record的引用不明确
[ERROR] \Users\bo\dev\DataX\core\src\main\java\com\alibaba\datax\core\transport\transformer\FilterTransformer.java:[20,11] 错误: 对Record的引用不明确
[ERROR] \Users\bo\dev\DataX\core\src\main\java\com\alibaba\datax\core\transport\transformer\FilterTransformer.java:[72,27] 错误: 对Record的引用不明确
[ERROR] \Users\bo\dev\DataX\core\src\main\java\com\alibaba\datax\core\transport\transformer\FilterTransformer.java:[72,12] 错误: 对Record的引用不明确
[ERROR] \Users\bo\dev\DataX\core\src\main\java\com\alibaba\datax\core\transport\transformer\FilterTransformer.java:[132,26] 错误: 对Record的引用不明确
[ERROR] \Users\bo\dev\DataX\core\src\main\java\com\alibaba\datax\core\transport\transformer\FilterTransformer.java:[132,12] 错误: 对Record的引用不明确
[ERROR] \Users\bo\dev\DataX\core\src\main\java\com\alibaba\datax\core\transport\transformer\FilterTransformer.java:[203,27] 错误: 对Record的引用不明确
[ERROR] \Users\bo\dev\DataX\core\src\main\java\com\alibaba\datax\core\transport\transformer\FilterTransformer.java:[203,12] 错误: 对Record的引用不明确
[ERROR] \Users\bo\dev\DataX\core\src\main\java\com\alibaba\datax\core\transport\transformer\FilterTransformer.java:[253,30] 错误: 对Record的引用不明确
[ERROR] \Users\bo\dev\DataX\core\src\main\java\com\alibaba\datax\core\transport\transformer\FilterTransformer.java:[253,12] 错误: 对Record的引用不明确
[ERROR] \Users\bo\dev\DataX\core\src\main\java\com\alibaba\datax\core\transport\transformer\FilterTransformer.java:[294,26] 错误: 对Record的引用不明确
[ERROR] \Users\bo\dev\DataX\core\src\main\java\com\alibaba\datax\core\transport\transformer\FilterTransformer.java:[294,12] 错误: 对Record的引用不明确
[ERROR] \Users\bo\dev\DataX\core\src\main\java\com\alibaba\datax\core\transport\transformer\FilterTransformer.java:[303,29] 错误: 对Record的引用不明确
[ERROR] \Users\bo\dev\DataX\core\src\main\java\com\alibaba\datax\core\transport\transformer\FilterTransformer.java:[303,12] 错误: 对Record的引用不明确

**Comment by xxh2000** [comment]
加WX: x_010101进交流群交流

**Comment by dingbo8128** [comment]
with java8 ok

**Comment by mumucgq** [comment]
使用java8就可以了

**Comment by caidashi** [comment]
export JAVA_HOME=`/usr/libexec/java_home -v 1.8` 切换到1.8.
