### ISSUE TITLE
datax链接不上Oracle数据库

### ISSUE THREAD

**Issue by xwz111111** [alibaba/DataX#1214]
写好了任务文件，运行的时候一直提示链接不上数据库：THE NETWORK ADAPTER COULD NOT ESTABLISH THE CONNECTION 但是检查了好多遍，地址什么的都是对的，求解！

**Comment by xwz111111** [comment]
是Oracle11.2.0.4.0版本

**Comment by TrafalgarLuo** [comment]
1. 先检查下物理网络连通；
2. 其次留意下是否有防火墙；
3. 数据库白名单配置检查；
4. Oracle 数据库的连接串有多种配置形式，是否都正确配置了；
