### ISSUE TITLE
使用mysqlwriter写入数据到本地时提示数据库连接失败

### ISSUE THREAD

**Issue by SatanSec** [alibaba/DataX#123]
使用mysqlwriter写入数据到本地时提示数据库连接失败
Exception when calling callable, 即将尝试执行第1次重试.本次重试计划等待[1000]ms,实际等待[1000]ms, 异常Msg:[Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].  -  具体错误信息为：java.sql.SQLException: No suitable driver found for ["jdbc:mysql://127.0.0.1:3306/wankeji"]?yearIsDateType=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&rewriteBatchedStatements=true]

相同的用户名密码使用mysqlreader却能正常从本地读取数据

**Comment by guoleopard** [comment]
同问同问

**Comment by aiaix** [comment]
有解决办法吗
