### ISSUE TITLE
mysql中有转义符+双引号会导致datax报错

### ISSUE THREAD

**Issue by an-bad-apple** [alibaba/DataX#1231]
1.我现在mysql中插入一条记录  
`INSERT INTO  test_abc
VALUES ( '\"sdd22s', 'avcvv', '哈哈哈哈', '回回去去', 'ddddd' );`
然后打开mysql ，看到的是 
![image](https://user-images.githubusercontent.com/26055389/143542156-9edb9032-4a33-4c13-88aa-e2ec26905723.png)
2.然后我用sqoop 拉取到hive 里，然后从hive 用datax拉取到clickhouse 里结果报错了。
![image](https://user-images.githubusercontent.com/26055389/143542263-da948427-2132-4273-b54d-8a4a73cc556d.png)
看问题，似乎是 转义+双引号 对datax 有影响。难道只能写replace替换吗

**Comment by an-bad-apple** [comment]
补充问题，如果字段开头有个双引号 也会报错。
如果字段里有三个双引号也会报错

**Comment by Y-evil** [comment]
是CSVReader的问题，你百度下CSV文件的概念，Datax使用的javacsv-2.0.jar包。
偷懒的做法是你把转移符改了，默认是双引号，在UnstructuredStorageReaderUtil.doReadFromStream()方法中。

// 偷懒的解决办法
CsvReader csvReader = new CsvReader(reader);
csvReader.setTextQualifier('\u0000'); // 加上这行，意思是 将默认的转移符 ” 改为 字符\u0000。

它好像可以关闭转移符这个功能，我记不太清了。

**Comment by a2king** [comment]
类型改为"fileType": "csv"，并配置csv参数
"csvReaderConfig":{
    "safetySwitch":false,
    "skipEmptyRecords":false,
    "textQualifier":"",
    "useTextQualifier":false
}
可以解决问题

**Comment by dingxiaobo** [comment]
文件不符合CSV定义，建议修正CSV文件，
感谢 @Y-evil  的解答

**Comment by wj-100** [comment]
类型为啥要改为"fileType": "csv"，
csv参数
"csvReaderConfig":{
 "safetySwitch":false,
 "skipEmptyRecords":false,
 "useTextQualifier":false
 }
为啥也可以了？
