### ISSUE TITLE
表名有特殊字符该如何处理，表名是 Task,任务表

### ISSUE THREAD

**Issue by tankmarshal** [alibaba/DataX#1241]
写成 
`"table":[
    "[Task,任务表]"
]`

报
`执行的SQL为:select * from [Task where 1=2`

**Comment by xxh2000** [comment]
加WX: x_010101进交流群交流

**Comment by TrafalgarLuo** [comment]
增加转义即可，比如 MySQL 数据库可以配置

"table":[ "`[Task,任务表]`" ]
