### ISSUE TITLE
tar包安装方式执行自检脚本报 datax/plugin/reader/._drdsreader/plugin.json]不存在

### ISSUE THREAD

**Issue by bingfenglai** [alibaba/DataX#1242]
环境：centos 7 python2

tar包安装方式执行自检脚本报 datax/plugin/reader/._drdsreader/plugin.json]不存在

**Comment by Ocean-git** [comment]
同问，解压之后有很多隐藏文件，
隐藏文件打开后有Mac OS X字样，是打包错系统了吗
<img width="348" alt="image" src="https://user-images.githubusercontent.com/20833538/145546997-5cfaa7ee-d0f2-486e-94f4-d6c91fced955.png">

**Comment by itsPu** [comment]
同问

**Comment by itsPu** [comment]
谁有历史版本的包吗？

**Comment by Jzzzz24K** [comment]
同问

**Comment by ChenZhuang1217** [comment]
同问

**Comment by Kotoriy** [comment]
同问

**Comment by Kotoriy** [comment]
> 环境：centos 7 python2
> 
> tar包安装方式执行自检脚本报 datax/plugin/reader/._drdsreader/plugin.json]不存在
有解决吗

**Comment by zhaoysg** [comment]
进入 reader/write 目录下执行删除操作（将._drdsreader 等文件删除）
   rrm -f ._*

**Comment by Kotoriy** [comment]
这是来自QQ邮箱的自动回复邮件。你好，我最近正在上课，无法亲自回复你的邮件。我将在课程结束后，尽快给你回复。

**Comment by zhaoysg** [comment]
> 环境：centos 7 python2
> 
> tar包安装方式执行自检脚本报 datax/plugin/reader/._drdsreader/plugin.json]不存在

进入 reader/write 目录下执行删除操作（将.drdsreader 等文件删除）
rrm -f .*

**Comment by xxh2000** [comment]
加WX: x_010101进交流群交流

**Comment by HonorKnight8** [comment]
`find ./datax -type f -name "._*" | xargs rm -f`

**Comment by Kotoriy** [comment]
这是来自QQ邮箱的自动回复邮件。你好，我最近正在上课，无法亲自回复你的邮件。我将在课程结束后，尽快给你回复。

**Comment by TrafalgarLuo** [comment]
已经解决，可以下载最新的，地址： https://datax-opensource.oss-cn-hangzhou.aliyuncs.com/20220530/datax.tar.gz

在 https://github.com/alibaba/DataX 也可以找到最新地址（不定期更新）。

**Comment by Kotoriy** [comment]
这是来自QQ邮箱的自动回复邮件。你好，我最近正在上课，无法亲自回复你的邮件。我将在课程结束后，尽快给你回复。

**Comment by snail2sky** [comment]
肯定是在mac上打包的，在mac上打包会出现一些隐藏文件

**Comment by Kotoriy** [comment]
这是来自QQ邮箱的自动回复邮件。你好，我最近正在上课，无法亲自回复你的邮件。我将在课程结束后，尽快给你回复。
