### ISSUE TITLE
Mongodb中空值的处理

### ISSUE THREAD

**Issue by Sowevo** [alibaba/DataX#125]
当mongodbreader中指定的列包含空值时,会导致
    `com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-00], Description:[您的配置错误.].  - 列配置信息有错误. 因为您配置的任务中，源头读取字段数:6 与 目的表要写入的字段数:7 不相等. 请检查您的配置并作出修改.`
错误
应该是插件的bug

**Comment by Teamo512** [comment]
你这个应该是reader和writer部分的字段个数不匹配，我遇到的一个错误是，当reader中的某个字段在mongodb源数据中不存在时，会出现写到writer部分时发生错位现象，这应该是mongodbreader的bug问题，希望能修复！

**Comment by Sowevo** [comment]
@Teamo512 我也是这个样子,有一个字段不是全部都有值,部分为NULL

**Comment by Teamo512** [comment]
@Sowevo 那你解决了么？有人说要重写mongodbreader

**Comment by Sowevo** [comment]
@Teamo512 没有 昨天晚上才开始用这个,下载了源码看看能不能解决😂
[https://github.com/Sowevo/DataX](https://github.com/Sowevo/DataX)

**Comment by Sowevo** [comment]
@Teamo512 就改了一个字的样子,你可以看下我fork的,大概需要自己编译一下

**Comment by dsdg2016** [comment]
大佬，能帮忙看看mysql那边的吗#134

**Comment by youdemo** [comment]
> @Teamo512 我也是这个样子,有一个字段不是全部都有值,部分为NULL

能用在elasticsearchwriter吗？急求

**Comment by merlinMeng** [comment]
datax 默认是mongo 3.2.2， 如果mongodb 版主在3.4以上，driver 是不支持的，需要自己重新编译，
之后null 错位的情况就消失了，我的是因为版本问题

**Comment by merlinMeng** [comment]
mongdb 查看版本      db.version()
java driver 版本对照  https://docs.mongodb.com/drivers/java#introduction

**Comment by xjunhello** [comment]
这个bug感觉只会影响按字段顺序写入的writer。。。

**Comment by youdemo** [comment]
我已经收到您的邮件并将及时处理。谢谢您！Thank you.Your email is received and will be handled  as soon as possible.
