### ISSUE TITLE
下载下来的二进制包启动报错 datax/plugin/reader/._drdsreader/plugin.json]不存在

### ISSUE THREAD

**Issue by marker-wu** [alibaba/DataX#1254]
下载下来的二进制包启动报错 datax/plugin/reader/._drdsreader/plugin.json]不存在
环境信息：
jdk：1.8
Python：2.7

**Comment by hanjinmingpdx** [comment]
同问。
jdk：1.8.0_312
Python 2.7.5

**Comment by hanjinmingpdx** [comment]
> 下载下来的二进制包启动报错 datax/plugin/reader/._drdsreader/plugin.json]不存在 环境信息： jdk：1.8 Python：2.7

把plugin/reader 和plugin/writter下所有.开头的隐藏文件全部移到其他目录下 再启动

**Comment by jackiesre721** [comment]
把这些目录删了 才能启动

**Comment by yzhang921** [comment]
> > 下载下来的二进制包启动报错 datax/plugin/reader/._drdsreader/plugin.json]不存在 环境信息： jdk：1.8 Python：2.7
> 
> 把plugin/reader 和plugin/writter下所有.开头的隐藏文件全部移到其他目录下 再启动

```
rm writer/.*
rm reader/.*
```

**Comment by TrafalgarLuo** [comment]
已经解决，可以下载最新的，地址： https://datax-opensource.oss-cn-hangzhou.aliyuncs.com/20220530/datax.tar.gz

在 https://github.com/alibaba/DataX 也可以找到最新地址（不定期更新）。
