### ISSUE TITLE
请问log4j2的漏洞会更新掉嘛？

### ISSUE THREAD

**Issue by LiJunXiao** [alibaba/DataX#1266]
最近服务器的自检程序检测到datax里边的有三个模块的插件的log4j2的版本低于2.15，这些插件会更新log4j2的版本嘛？？

**Comment by zlj0123** [comment]
我这里没用到别的插件，我所用的插件里，只有hdfsreader有log4j2的jar包，直接exclude掉，不影响功能

**Comment by TrafalgarLuo** [comment]
已经在主干更新了log4j相关的版本

**Comment by TrafalgarLuo** [comment]
已经在主干更新了log4j相关的版本
