### ISSUE TITLE
希望增加交流群入口

### ISSUE THREAD

**Issue by yinkebao** [alibaba/DataX#1271]
当前README.md文件中的钉钉交流群已满，是否可以继续创建新群以供咨询讨论，谢谢。

**Comment by goudanz** [comment]
加了没用，之前加了他们官方的几个钉钉群，里面都没有任何人说话的。交流更谈不上了。还不如自己拉一个微信群交流呢。

**Comment by qinfangzhe** [comment]
期待官方开个QQ群或者微信群

**Comment by TrafalgarLuo** [comment]
目前暂时没有资源扩容管理钉钉群，麻烦有创意的使用问题在github issue反馈吧， 知识点也能给后面的同学带来帮助。
