### ISSUE TITLE
com.aliyun:hitsdb-client:pom:0.4.0-SNAPSHOT

### ISSUE THREAD

**Issue by smthhy** [alibaba/DataX#1273]
com.aliyun:hitsdb-client:pom:0.4.0-SNAPSHOT  jar包拉不到。改成0.3.7版本的   tsdb.useDatabase(database);  **useDatabase**方法又没有。怎么解决  在tsdbwriter项目里的TSDBWriter类中

**Comment by pkvov** [comment]
编译不过, 只能切到之前的老版本再编译, 没办法, 这个项目的发布太随意了

**Comment by ByteFlyCoding** [comment]
确实是太随意了，完全没有打tag和发release，老哥你切回的版本的的commit id是多少呀？

> 编译不过, 只能切到之前的老版本再编译, 没办法, 这个项目的发布太随意了

**Comment by iamlaobie** [comment]
> 确实是太随意了，完全没有打tag和发release，老哥你切回的版本的的commit id是多少呀？
> 
> > 编译不过, 只能切到之前的老版本再编译, 没办法, 这个项目的发布太随意了
直接把tsdb删了

**Comment by songjunwang** [comment]
这里有release分支
https://github.com/aliyun/aliyun-tsdb-java-sdk/blob/release/0.4.0/pom.xml

**Comment by brokge** [comment]
> 这里有release分支 https://github.com/aliyun/aliyun-tsdb-java-sdk/blob/release/0.4.0/pom.xml
老哥威武.
clone上面项目，切到release/0.4.0 对应分支，install 到本地，即可运行了。

**Comment by phstan** [comment]
git clone https://github.com/aliyun/aliyun-tsdb-java-sdk/tree/master
git checkout -b 0.4 remotes/origin/release/0.4.0
mvn clean install Dmaven.test.skip=true
cp target/hitsdb-client-0.4.0-SNAPSHOT.jar repository/com/aliyun/hitsdb-client/0.4.0-SNAPSHOT/

**Comment by code-dm** [comment]
修改下上面老哥的命令
git clone https://github.com/aliyun/aliyun-tsdb-java-sdk.git
git checkout -b 0.4 remotes/origin/release/0.4.0
mvn clean install -Dmaven.test.skip=true

**Comment by TrafalgarLuo** [comment]
这个问题已经收到，默认会切换到 0.3.7

**Comment by TrafalgarLuo** [comment]
已经解决过类似问题，可以参考最新的代码push
