### ISSUE TITLE
这个项目是不是烂尾了？编译各种报错，我该说些什么？没人管理这个项目了吗？要不然给大家来维护吧。

### ISSUE THREAD

**Issue by GodloveJoseph** [alibaba/DataX#1274]
这个项目是不是烂尾了？编译各种报错，我该说些什么？没人管理这个项目了吗？要不然给大家来维护吧。

**Comment by kilodleif** [comment]
kpi-oriented open source🤣

**Comment by GodloveJoseph** [comment]
你好，来信收到！

**Comment by GodloveJoseph** [comment]
> kpi-oriented open source🤣
这是什么软件？

**Comment by cqboyone** [comment]
> > kpi-oriented open source🤣
> > 这是什么软件？

意思是拿来做绩效的，绩效一打，就不维护了。我真的是无语，阿里开源个这玩意编译都不通过，缺少一堆依赖，甚至还引用了快照版本。

**Comment by GodloveJoseph** [comment]
你好，来信收到！

**Comment by git-isunday** [comment]
> 

so vivid😂

**Comment by BH-Parity** [comment]
希望有能力的大佬可以多贡献代码，毕竟目前比较能用的只有datax了

**Comment by qq29oo** [comment]
能用的，把没用的依赖和module清了就好，就保留你需要用的module，我这边就靠它同步了几十亿数据没出大问题

**Comment by GodloveJoseph** [comment]
你好，来信收到！

**Comment by mumucgq** [comment]
编译出现的报错 都能手动解决.

**Comment by Galthen** [comment]
> 能用的，把没用的依赖和module清了就好，就保留你需要用的module，我这边就靠它同步了几十亿数据没出大问题

我也是这么用的，其实大部分的module都用不到，只需要保留自己需要使用的，同时很大程度的可以减小包大小。

**Comment by GodloveJoseph** [comment]
你好，来信收到！

**Comment by TrafalgarLuo** [comment]
后续会定期更新这个项目（包括代码、文档、issue等），如果有比较好的插件也环境提交 merge request。目前有一个内部版本在对外更新审核中。

**Comment by GodloveJoseph** [comment]
你好，来信收到！
