### ISSUE TITLE
怎样提交代码

### ISSUE THREAD

**Issue by Duanjunqi1024** [alibaba/DataX#1275]
我们是一家小关系数据库公司，编写并测试了datax的插件，我们想把我们的插件提交上去，想知道怎么操作

**Comment by Galthen** [comment]
我理解的是先fork下来，然后修改提交，最后申请合并。
细节可以搜索下。

**Comment by TrafalgarLuo** [comment]
确实是 fork下来，然后修改提交，最后申请合并。后面会定期处理合并请求。
