### ISSUE TITLE
compilation failiure

### ISSUE THREAD

**Issue by john1337** [alibaba/DataX#1284]
tsdbwriter module has hitsdb-client dependency,but 0.4.0-SNAPSHOT doesn't exist in aliyun repo
<dependency>
            <groupId>com.aliyun</groupId>
            <artifactId>hitsdb-client</artifactId>
            <version>0.4.0-SNAPSHOT</version>
        </dependency>

**Comment by TrafalgarLuo** [comment]
此问题已经解决，可以pull最新代码，或者可以下载最新的，地址： https://datax-opensource.oss-cn-hangzhou.aliyuncs.com/20220530/datax.tar.gz

在 https://github.com/alibaba/DataX 也可以找到最新地址（不定期更新）。
