### ISSUE TITLE
hitsdb-client 缺少问题

### ISSUE THREAD

**Issue by zhibodai** [alibaba/DataX#1292]
[ERROR] Failed to execute goal on project tsdbwriter: Could not resolve dependencies for project com.alibaba.datax:tsdbwriter:jar:0.0.1-SNAPSHOT: Could not find artifact com.aliyun:hitsdb-client:jar:0.4.0-SNAPSHOT in public (http://maven.aliyun.com/nexus/content/groups/public/) -> [Help 1]

查了阿里官网发现这个包 hitsdb-client 我看到最新的是 hitsdb-client-0.3.6.jar 把我整傻了。
就改了下目录下
{DataX-Home}/tsdbwriter/pom.xml
把对应版本修改到了 0.3.6 

也不行，旧版本缺少了字段
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project tsdbwriter: Compilation failure
[ERROR] /Users/xmly/Desktop/project/DataX/tsdbwriter/src/main/java/com/alibaba/datax/plugin/writer/tsdbwriter/TSDBWriter.java:[136,24] 错误: 找不到符号

看了下是最近才修改的模块，只能在最外部的pom 里面先注释掉了。

**Comment by lihulanxx** [comment]
这个是真的坑

**Comment by pawnone** [comment]
真的被这个坑惨了

**Comment by TyrantLucifer** [comment]
哈哈哈找到组织了，阿里好像没有推0.4.0的包，改成最新版本0.3.7又有一些api没有，只能先注释掉了

**Comment by lvmoe** [comment]
坑爹

**Comment by forachange** [comment]
阿里对开源也不怎么严谨啊

**Comment by wglgithub** [comment]
到现在也没解决这个问题，哎，失望啊

**Comment by efff** [comment]
+1

**Comment by itchun** [comment]
> 哈哈哈找到组织了，阿里好像没有推0.4.0的包，改成最新版本0.3.7又有一些api没有，只能先注释掉了
+1

**Comment by efff** [comment]
> > 哈哈哈找到组织了，阿里好像没有推0.4.0的包，改成最新版本0.3.7又有一些api没有，只能先注释掉了
> > +1

我看那个包的引用是在 tsdbWriter 模块。tsdb 也用不到，直接把整个模块移除了。

**Comment by TrafalgarLuo** [comment]
近期的更新会解决这个问题，解决方法确实是使用 0.3.7 ，0.4.0有一些特性开源暂时不支持。

**Comment by lysShub** [comment]
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on projec

得了名还想得利呗

**Comment by TrafalgarLuo** [comment]
此问题已经解决了，麻烦新pull下代码，或者：
可以下载最新的，地址： https://datax-opensource.oss-cn-hangzhou.aliyuncs.com/20220530/datax.tar.gz

在 https://github.com/alibaba/DataX 也可以找到最新地址（不定期更新）。
