### ISSUE TITLE
支持自定义行行处理器吗？

### ISSUE THREAD

**Issue by huyongliang** [alibaba/DataX#13]
是否支持在reader之后writer之前改变某些字段的值，再将记录write到目的地呢？

**Comment by binaryWorld** [comment]
@huyongliang  目前不支持，但reader插件可以配置常量插入到writer端

**Comment by huyongliang** [comment]
常量指的是 增加一列值一样的字段到目的地？
这个常量的值也是无法通过判断记录特征动态生成的吗？
目前的版本能否通过简单扩展来增加“行处理器/过滤器”？

**Comment by binaryWorld** [comment]
@huyongliang   
常量是增加一列值一样的字段到目的地；
无法通过判断记录特征动态生成；
可以通过简单扩展来增加“行处理器/过滤器，你可以在read出来后做

**Comment by liupengjava** [comment]
我们年后会编写Transformer功能，支持在传输过程中完成数据的简单转换，到时候会合到开源的版本

**Comment by huyongliang** [comment]
期待中……
