### ISSUE TITLE
datax动态传多个参数，在linux环境下只替换了第一个参数，这是什么原因？

### ISSUE THREAD

**Issue by root-zhan** [alibaba/DataX#1316]
例如：在json中设置参数/${name}/${age}，然后用命令动态传参-Dname=zhangsan -Dage=12，替换后结果为/zhangsan -Dage=12/${age}

**Comment by TrafalgarLuo** [comment]
动态传参命令是   -p"-Dname=zhangsan -Dage=12"

是否少了双引号包括
