### ISSUE TITLE
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: 关键字 'from' 附近有语法错误

### ISSUE THREAD

**Issue by zfq314** [alibaba/DataX#1320]
[sqlserverwriter](https://github.com/alibaba/DataX/blob/master/sqlserverwriter/doc/sqlserverwriter.md)

描述：目的表需要写入数据的字段,字段之间用英文逗号分隔。例如: "column": ["id","name","age"]。如果>
要依次写入全部列，使用表示, 例如: "column": [""]

会报错：

Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: 关键字 'from' 附近有语法错误

原因： "column": [""] 应该为： "column": ['*']

**Comment by TrafalgarLuo** [comment]
感谢反馈，文档已经修正
