### ISSUE TITLE
报错，进行不下去了，求解决方法，感谢。

### ISSUE THREAD

**Issue by studentWang0** [alibaba/DataX#1321]
WARN  DBUtil - test connection of [jdbc:mysql://10.30.233.XX:13306/test_car] failed, for Code:[MYSQLErrCode-02], Description:[数据库服务的IP地址或者Port错误，请检查填写的IP地址和Port或者联系DBA确认IP地址和Port是否正确。如果是同步中心用户请联系DBA确认idb上录入的IP和PORT信息和数据库的当前实际信息是一致的].  -  具体错误信息为：com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server..
2022-03-16 17:08:13.219 [job-0] ERROR RetryUtil - Exception when calling callable, 异常Msg:DataX无法连接对应的数据库，可能原因是：1) 配置的ip/port/database/jdbc错误，无法连接。2) 配置的username/password错误，鉴权失败。请和DBA确认该数据库的连接信息是否正确。

**Comment by studentWang0** [comment]
已经更换了mysql的驱动更换为8.0.18版本的，但是还是报这个错误。

**Comment by sunshine-10** [comment]
整体的json任务文件，转存mysql数据至hive
`{
    "setting": {},
    "job": {
        "setting": {
            "speed": {
                "channel": 3
            }
        },
		
        "content": [
            {
                "reader": {
                    "name": "mysqlreader",
                    "parameter": {
						"username":"root",
						"password":"XXXX",
                        "column":[
                          "xxx"
                        ],
                        "connection":[
                            {
								"jdbcUrl":[	"jdbc:mysql://10.30.233.XX:13306/test_car"
                                ],
                                "table":[
                                    "car_static_data"
                                ]
                            }
                        ]
                    }
                },
                "writer": {
                    "name": "hdfswriter",
                    "parameter": {
                        "column":[
                            {
                                "name":"xxx",
                                "type":"string"
                            }
                        ],
						"defaultFS": "hdfs://bmr-clusteravb",
                        "fileType": "orc",
                        "path": "/dtInsight/hive/warehouse/gcvxx_test.db/test_car_data",
                        "fileName": "test_static_data",
                        "writeMode": "append",
                        "fieldDelimiter": ",",
                        "compress":"snappy"
                    }
                }
            }
        ]
    }
}`

**Comment by sunshine-10** [comment]
整个JSON任务文件，转存mysql数据存入hive


`{
    "setting": {},
    "job": {
        "setting": {
            "speed": {
                "channel": 3
            }
        },
        "content": [
            {
                "reader": {
                    "name": "mysqlreader",
                    "parameter": {
						"username":"root",
						"password":"XXXX",
                        "column":[
                          "xxx"
                        ],
                        "connection":[
                            {
								"jdbcUrl":[	"jdbc:mysql://10.30.233.XX:13306/test_car"
                                ],
                                "table":[
                                    "car_static_data"
                                ]
                            }
                        ]
                    }
                },
                "writer": {
                    "name": "hdfswriter",
                    "parameter": {
                        "column":[
                            {
                                "name":"xxx",
                                "type":"string"
                            }
                        ],
						"defaultFS": "hdfs://bmr-clusteravb",
                        "fileType": "orc",
                        "path": "/dtInsight/hive/warehouse/gcvxx_test.db/test_car_data",
                        "fileName": "test_static_data",
                        "writeMode": "append",
                        "fieldDelimiter": ",",
                        "compress":"snappy"
                    }
                }
            }
        ]
    }
}`

**Comment by studentWang0** [comment]
整个json任务文件，转存mysql数据至hive
`
{
    "setting": {},
    "job": {
        "setting": {
            "speed": {
                "channel": 3
            }
        },

        "content": [
            {
                "reader": {
                    "name": "mysqlreader",
                    "parameter": {
						"username":"root",
						"password":"XXXX",
                        "column":[
                          "xxx"
                        ],
                        "connection":[
                            {
								"jdbcUrl":[	"jdbc:mysql://10.30.233.XX:13306/test_car"
                                ],
                                "table":[
                                    "car_static_data"
                                ]
                            }
                        ]
                    }
                },
                "writer": {
                    "name": "hdfswriter",
                    "parameter": {
                        "column":[
                            {
                                "name":"xxx",
                                "type":"string"
                            }
                        ],
						"defaultFS": "hdfs://bmr-clusteravb",
                        "fileType": "orc",
                        "path": "/dtInsight/hive/warehouse/gcvxx_test.db/test_car_data",
                        "fileName": "test_static_data",
                        "writeMode": "append",
                        "fieldDelimiter": ",",
                        "compress":"snappy"
                    }
                }
            }
        ]
    }
}`

**Comment by TrafalgarLuo** [comment]
请验证下  任务执行 机器和 mysql 数据库之间的网络连通情况， 可以使用 mysql 客户端工具建立连接对比测试下

**Comment by pioneer-code** [comment]
请问解决了嘛

**Comment by xmy20051643** [comment]
?useSSL=false  url里加上这个试试？

**Comment by melodicdeath** [comment]
> ?useSSL=false url里加上这个试试？

谢谢大神，以解决。
