### ISSUE TITLE
如何提升datax导入效率？

### ISSUE THREAD

**Issue by QJpd** [alibaba/DataX#1324]
{
	"job": {
		"content": [{
			"reader": {
				"name": "oraclereader",
				"parameter": {
					"column": [
						"*"
					],
					"where": "",
					"connection": [{
						"jdbcUrl": ["${readjdbc}"],
						"table": ["${tablebusiness}"]
					}],
					"password": "${readpassword}",
					"username": "${readuser}"
				}
			},
			"writer": {
				"name": "mysqlwriter",
				"parameter": {
					"column": [
					  "*"
					],
					"connection": [{
						"jdbcUrl": "${writejdbc}",
						"table": ["${tablebak}"]
					}],
					"password": "${writepassword}",
					"preSql": [],
					"postSql": [],
					"session": [],
					"username": "${writeuser}",
					"writeMode": "update"
				}
			}
		}],
		"setting": {
			"speed": {
					"channel": "${threadsNum}"
			}
		}
	}
}
================
任务启动时刻                    : 2022-03-21 14:29:21
任务结束时刻                    : 2022-03-21 14:39:12
任务总计耗时                    :                590s
任务平均流量                    :            1.32MB/s
记录写入速度                    :          17456rec/s
读出记录总数                    :            10299200
读写失败总数                    :                   0
=================

以上是我的脚本，具体场景是由oracle数据库读取一张大表的数据导入mysql数据库。经过多次尝试改变datax的参数与脚本中speed的参数均无法实现导入速度的大幅提升。速度稳定在 1.32MB/s左右。后来我采用了并发的形式，就是同时启动多个datax脚本，读取多张表的数据进行同步，这样从总量上看两边的读、写速度均提升较大，单个的datax任务速度限制是什么？

**Comment by TrafalgarLuo** [comment]
你需要配置切分列， splitPk 参数，让reader插件根据splitPk列做自动切片并发读取即可。

你现在配置多个任务，本质上是人工多并发任务读取了，另外， splitPk 建议配置 整形 的有索引列为最佳实践
