### ISSUE TITLE
是否支持IPV6？？

### ISSUE THREAD

**Issue by Ormand1bd** [alibaba/DataX#1328]
Datax是否支持IPV6，还有在国产系统上兼容性如何

**Comment by zmbaliqq** [comment]
> Datax是否支持IPV6，还有在国产系统上兼容性如何

同问

**Comment by TrafalgarLuo** [comment]
目前内部测试看，大多数数据源是支持ipv6的。 比如配置一个MySQL数据同步，jdbcUrl中填写 ipv6 格式是可以使用的
