### ISSUE TITLE
ftpreader会把文件读取到本地文件，如何修改本地的temp目录

### ISSUE THREAD

**Issue by tsonghua** [alibaba/DataX#1331]
如何设置本地的临时目录地址？

**Comment by TrafalgarLuo** [comment]
使用的是 txtfile writer插件吗， 这个插件本身是可以配置 path 参数控制数据写出目标磁盘。

如果是 jdk 的的临时文件目录，是环境变量 datax.py job.json  --jvm="-Djava.io.tmpdir=/path/to/tmpdir"
