### ISSUE TITLE
当源表主键为联合主键时，splitPk 应该如何设置 

### ISSUE THREAD

**Issue by YangFW** [alibaba/DataX#1334]

**Comment by gavin-xxx** [comment]
可以不设置splitPK。如果要设置，splitPK对类型是有要求的

**Comment by TrafalgarLuo** [comment]
根据索引的最左匹配原则，建议选择索引左侧的列作为切分列

**Comment by moxuan12138** [comment]
> 根据索引的最左匹配原则，建议选择索引左侧的列作为切分列

联合主键也没有效果，会出现成功重复数据怎么解决的
