### ISSUE TITLE
Goodrain开源社区合作申请

### ISSUE THREAD

**Issue by zzzhangqi** [alibaba/DataX#1342]
您好，我来自开源社区 [Goodrain](https://github.com/goodrain)，我们所运营的开源项目是[Rainbond](https://github.com/goodrain/rainbond)，我们的[官网](https://www.rainbond.com/)

我们有许多用户在使用 DataX，因此我们通过 Rainbond 自身的应用市场机制为这些用户提供了一种选择，一键部署生产可用的 DataX 集群，这种部署方式很受社区用户的欢迎。所以特此提出一种合作的可能，我们愿意提交一份一键部署 DataX 的文档到您的仓库中，帮助更多同时需要云原生应用管理平台和 DataX 的用户了解到这种可能性以及其带来的便利性。

可以参考我们以往与 [Nacos](https://nacos.io/zh-cn/blog/use-nacos-with-rainbond.html)、[Apollo](https://www.apolloconfig.com/#/zh/deployment/third-party-tool-rainbond) 的合作方式。

期待您的答复😚！

**Comment by TrafalgarLuo** [comment]
您好，您的信息我们已经收到了，我们讨论下再和您反馈哈

**Comment by zzzhangqi** [comment]
感谢您的答复，期待我们的合作！

**Comment by zzzhangqi** [comment]
@TrafalgarLuo 请问后续有何答复呀 😁

**Comment by TrafalgarLuo** [comment]
@zzzhangqi 请问怎么单独联系到您，需要线下沟通下细节

**Comment by zzzhangqi** [comment]
@TrafalgarLuo 您可以通过 zhangq@goodrain.com 邮箱将WeChat发我，或者您提供邮箱，我发您我的WeChat

**Comment by TrafalgarLuo** [comment]
@zzzhangqi  信息收到了，我线下联系您
