### ISSUE TITLE
No enum constant com.aliyun.odps.OdpsType.TIMESTAMP

### ISSUE THREAD

**Issue by anchorl** [alibaba/DataX#1352]
ob-》odps exception：No enum constant com.aliyun.odps.OdpsType.TIMESTAMP

**Comment by TrafalgarLuo** [comment]
近期会更新新版本，支持多个新特性，包括 maxcompute 2.0类型的支持（包括 timestamp）

**Comment by TrafalgarLuo** [comment]
这个是 maxcompute 2.0类型支持问题，目前最新版本已经支持了， 可以基于最新源码构建，或者在首页下载打包好的二进制执行包
