### ISSUE TITLE
自检脚本python3环境下运行错误--打印错误

### ISSUE THREAD

**Issue by ghost** [alibaba/DataX#1375]
方法一、直接下载DataX工具包：[DataX下载地址](http://datax-opensource.oss-cn-hangzhou.aliyuncs.com/datax.tar.gz)

下载后解压至本地某个目录，进入bin目录，即可运行同步作业：

$ cd  {YOUR_DATAX_HOME}/bin
$ python datax.py {YOUR_JOB.json}
自检脚本：    python {YOUR_DATAX_HOME}/bin/datax.py {YOUR_DATAX_HOME}/job/job.json

环境：Linux，python3.9.7
错误信息：
```
$ python bin/datax.py job/job.json 
  File "/home/wst/software/datax/bin/datax.py", line 114
    print readerRef
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(readerRef)?
```

**Comment by TrafalgarLuo** [comment]
这个是 python 版本不对导致的，二进制镜像中需要 python 2.x版本。 近期会更新镜像，新镜像同时支持 python 2.x、python 3.x

你也可以先使用 python 2.x版本解决问题
