### ISSUE TITLE
请问下datax支持一列变为多列吗？

### ISSUE THREAD

**Issue by tlxfif** [alibaba/DataX#1385]
我们需要解析某个字段，然后写成多个字段

比如 

```
读取 id,name,extra
写入id,name,aaa,bbb
```
#### 请问下如何实现呢？感谢感谢🤗

**Comment by tlxfif** [comment]
我现在知道可以用
`record.setColumn()`
来设置，但是这个地方可以动态新增列吗？
如果列与源数据结构不一致会不会出现这个错误呢？
`[您的配置错误.].  - 列配置信息有错误. 因为您配置的任务中，源头读取字段数:2 与 目的表要写入的字段数:3 不相等. 请检查您的配置并作出修改`

**Comment by VVeaker** [comment]
record.addColumn();这个可以添加一列，默认添加到最后一列

**Comment by tlxfif** [comment]
好的多谢
