### ISSUE TITLE
传参出现问题 ？

### ISSUE THREAD

**Issue by h812755591** [alibaba/DataX#1390]
"-Ddf=' SELECT COUNT(*) as dects_num, 'xsss' as lot_no,1 as loc FROM z_1_debris zd' "

然后到达执行的时候 sql变为 
SELECT COUNT(*) as dects_num, xsss as lot_no,1 as loc FROM z_1_debris zd

**Comment by TrafalgarLuo** [comment]
这个问题是因为linux 命令行参数转义导致的， 你可以在传参时增加 \ 转义，多调试几次即可。

参数经过linux shell后，给到datax时少了一些 单引号、或者双引号

**Comment by h812755591** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/DataX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月13日(星期一) 晚上9:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/DataX] 传参出现问题 ？ (Issue #1390)





 
这个问题是因为linux 命令行参数转义导致的， 你可以在传参时增加 \ 转义，多调试几次即可。
 
参数经过linux shell后，给到datax时少了一些 单引号、或者双引号
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.




各种方法都试了 但是实际上都没什么效果 包括加\ 转义
