### ISSUE TITLE
get started 报错及可能的处理办法

### ISSUE THREAD

**Issue by ya-dao** [alibaba/DataX#1394]
### 问题描述
按照get started操作, 会提示如下报错:
> 2022-06-10 11:07:20.837 [main] WARN  ConfigParser - 插件[streamreader,streamwriter]加载失败，1s后重试... Exception:Code:[Common-00], Describe:[您提供的配置文件存在错误信息，请检查您的作业配置 .] - 配置信息错误，您提供的配置文件[/home/datax/temp/datax/plugin/reader/._hbase094xreader/plugin.json]不存在. 请检查您的配置文件. 
2022-06-10 11:07:21.841 [main] ERROR Engine - 
经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[Common-00], Describe:[您提供的配置文件存在错误信息，请检查您的作业配置 .] - 配置信息错误，您提供的配置文件[/home/datax/temp/datax/plugin/reader/._hbase094xreader/plugin.json]不存在. 请检查您的配置文件.

### 解决办法
进入`plugin`目录, 删除`reader`和`writer`目录下的隐藏文件:
```shell
cd [YOUR PATH]/datax
rm -rf ./plugin/reader/.*
rm -rf ./plugin/writer/.*
```

**此操作只能保证get started能够正常跑起来, 不太了解这个工具, 不清楚此删除操作会不会影响到正常功能**

**Comment by TrafalgarLuo** [comment]
已经解决，可以下载最新的，地址： https://datax-opensource.oss-cn-hangzhou.aliyuncs.com/20220530/datax.tar.gz

在 https://github.com/alibaba/DataX 也可以找到最新地址（不定期更新）。
