### ISSUE TITLE
地址有误&链接过期

### ISSUE THREAD

**Issue by jefftlin** [alibaba/DataX#1395]
1、QuickStart的[DataX下载地址](http://datax-opensource.oss-cn-hangzhou.aliyuncs.com/datax.tar.gz)打不开
2、6个交流群中前五个过期，第6个满500人进不去

**Comment by TrafalgarLuo** [comment]
感谢您的反馈，我确认看下

**Comment by TrafalgarLuo** [comment]
QuickStart 地址，我尝试了下，是可以下载的， 这个点击是触发软件包下载
http://datax-opensource.oss-cn-hangzhou.aliyuncs.com/datax.tar.gz

**Comment by TrafalgarLuo** [comment]
钉钉群暂时没有资源扩容，问题先通过issue解答吧
