### ISSUE TITLE
如果有多张不同类型的表需要同步，在一个任务内应该怎么实现呢

### ISSUE THREAD

**Issue by njian-github** [alibaba/DataX#1399]
有需求是将多张不同类型的mongodb表同步到不同的Elasticsearch的索引内，在一个任务内应该怎么实现呢，是否有demo可以参考

**Comment by MacrossGithub-coder** [comment]
json里的content不是个list吗，可以试下放在一起。

**Comment by njian-github** [comment]
> json里的content不是个list吗，可以试下放在一起。

已经测试过，content里面放多个配置，仅有第一个会生效，其他的同步配置并没有执行，请问是不支持吗

**Comment by qq29oo** [comment]
自己魔改下mongo db reader 呗，或者执行多次任务，不同表的数据分别update到es里就好了啊

**Comment by dingxiaobo** [comment]
需要配置多个任务
