### ISSUE TITLE
关系型数据库 querySql  不支持别名

### ISSUE THREAD

**Issue by relaxyabc** [alibaba/DataX#140]
由于 querysql  写在 connection 外部,所以误以为不支持别名,建议 文档中加入说明:  使用  querysql  时,应该是  job.json 中应该是 数组,看日志信息一直没看明了,看源码才处理好

**Comment by luckylocode** [comment]
querySql   并没有忽略 table  属性
![qq 20180717085838](https://user-images.githubusercontent.com/22515554/42790895-e5748ce2-899f-11e8-8fcf-85138801f32b.png)
