### ISSUE TITLE
两表字段数量不相等，通过transformer处理可以写入吗

### ISSUE THREAD

**Issue by LIKEGAKKI** [alibaba/DataX#1417]
A表有五个字段：id,u1,u2,u3,u4;
B表有两个字段：id,u;

从A表读出数据，然后将u1+..+u4的值计算出来，吧A的id写入B的id，算出来的值写入B的u字段

例子：
A： a1,1,2,3,4 =>  B: a1,10

**Comment by leehom** [comment]
https://www.toutiao.com/article/7109709746328060431/，可以看一下这个

**Comment by LIKEGAKKI** [comment]
> [https://www.toutiao.com/article/7109709746328060431/，可以看一下这个](https://www.toutiao.com/article/7109709746328060431/%EF%BC%8C%E5%8F%AF%E4%BB%A5%E7%9C%8B%E4%B8%80%E4%B8%8B%E8%BF%99%E4%B8%AA)
我敲！大佬！有仓库吗！能让我耍一下嘛

**Comment by leehom** [comment]
> > [https://www.toutiao.com/article/7109709746328060431/，可以看一下这个](https://www.toutiao.com/article/7109709746328060431/%EF%BC%8C%E5%8F%AF%E4%BB%A5%E7%9C%8B%E4%B8%80%E4%B8%8B%E8%BF%99%E4%B8%AA)
> > 我敲！大佬！有仓库吗！能让我耍一下嘛

文中有源码下载链接，要收点费，代码里的reader/writer实现的是图图同步，但转换组件是独立的，也适用关系转关系；文章也写了设计，自己实现也不难

**Comment by LIKEGAKKI** [comment]
> 



> > > [https://www.toutiao.com/article/7109709746328060431/，可以看一下这个](https://www.toutiao.com/article/7109709746328060431/%EF%BC%8C%E5%8F%AF%E4%BB%A5%E7%9C%8B%E4%B8%80%E4%B8%8B%E8%BF%99%E4%B8%AA)
> > > 我敲！大佬！有仓库吗！能让我耍一下嘛
> 
> 文中有源码下载链接，要收点费，代码里的reader/writer实现的是图图同步，但转换组件是独立的，也适用关系转关系；文章也写了设计，自己实现也不难

我通过在transformer里返回一个我自己构建的recoder实现的

**Comment by leehom** [comment]
> > 
> 
> > > > [https://www.toutiao.com/article/7109709746328060431/，可以看一下这个](https://www.toutiao.com/article/7109709746328060431/%EF%BC%8C%E5%8F%AF%E4%BB%A5%E7%9C%8B%E4%B8%80%E4%B8%8B%E8%BF%99%E4%B8%AA)
> > > > 我敲！大佬！有仓库吗！能让我耍一下嘛
> > 
> > 
> > 文中有源码下载链接，要收点费，代码里的reader/writer实现的是图图同步，但转换组件是独立的，也适用关系转关系；文章也写了设计，自己实现也不难
> 
> 我通过在transformer里返回一个我自己构建的recoder实现的

实现Transformer不难，但考虑通用性，不可能每个record改变，每个column改变去实现一个Transformer，基于规则的转换，只需配个规则，不需要实现新的Transformer
