### ISSUE TITLE
自定义在transformer在多任务下，报错：[Description:[Transformer name has existed]]

### ISSUE THREAD

**Issue by LIKEGAKKI** [alibaba/DataX#1423]
有四个任务，每个任务好像去初始化一下我自定义的transformer，第一个任务会初始化transformer成功，但是后面三个任务都会初始化失败。
但是流程还是走下去了，只是我四个任务的意义就没有了，因为都是在用一个transformer处理数据。速度还是慢了
请问有什么解决办法吗？

我的transforms是放置在\datax\local_storage\transformer文件夹下，属于运行时加载的那种。没有直接写死注册到TransformerRegistry

**Comment by wangweng155** [comment]
我也碰到了这个问题，请问解决了吗

**Comment by shaow-h** [comment]
这个bug到现在还不解决？

**Comment by xqls-ng** [comment]
我也遇到了, 这个问题解决了吗
