### ISSUE TITLE
一个关于数据中有类似编码的问题

### ISSUE THREAD

**Issue by DeepSpace732423** [alibaba/DataX#1430]
我用datax从mysql数据库中抽数，如果表中某列数据类似这样'0x001FE51AEE9C3ED68A159BDBCF1CEC29', datax在写入文件的时候就会将其识别为UTF-8格式的原始编码，所以结果文件中就会显示这条为‘�6�1I�K�D%’, 我该怎样解决这个问题？

**Comment by jimmyc2006** [comment]
看样子你这个字段在mysql里是字节数组类型的，比如：blob类型，而0x001FE51AEE9C3ED68A159BDBCF1CEC29正是这个字节数组的16进制表示形式。datax在将数据写入文件的时候，需要转换成字符串。你需要先确认下你这个blob是怎么编码的。如果这个知道编码方式，可以在text中设置encoding参数来指定。比如GBK.

**Comment by jimmyc2006** [comment]
当然，如果你这个字段本来存的就不是一个能转化成字符串的数据，比如文件流转成的字节数组，或者图片等。那么你需要做的仅仅是把数据转移到文件，并不能在文件里读取，可以选在iso-8859-1来保存，这样不会出现乱码，不会丢失精度，但是人也不能识别。
