### ISSUE TITLE
writer写入数据时是否支持函数？

### ISSUE THREAD

**Issue by aixinyongheng** [alibaba/DataX#1435]
使用writer写入到数据库时，是否支持使用数据库的函数？

**Comment by TrafalgarLuo** [comment]
reader端支持函数，writer端不支持函数。 不过你这边表建表的时候， 如果列的dufault值，可以是函数， 同步时没有同步对应列，这个是可以的（其实是数据库的特性）。

**Comment by SinyoWong** [comment]
你好，我们在使用mysqlreader的时候，使用querySql，有groupby操作，发现sum()函数的值无法传递给目标表字段，其他函数例如min max count都可以正常传递。
datax版本：最新master分支
