### ISSUE TITLE
多线程同时执行返回日志是相同的

### ISSUE THREAD

**Issue by lihjChina** [alibaba/DataX#1437]
我使用xxl调度datax做数据抽取时候，我设置5个任务，同时执行，查看日志返回都是相同的。
![image](https://user-images.githubusercontent.com/16425311/177783376-e4e8c878-609b-43fe-9721-f0f9d1781eb7.png)

**Comment by lihjChina** [comment]
20:40:03.034 logback [taskGroup-1450] INFO  c.j.e.c.taskgroup.TaskGroupContainer - taskGroup[1450] taskId[0] is successed, used[1204]ms
20:40:03.034 logback [taskGroup-1420] INFO  c.j.e.c.taskgroup.TaskGroupContainer - taskGroup[1420] taskId[0] is successed, used[1205]ms
20:40:03.035 logback [taskGroup-1420] INFO  c.j.e.c.taskgroup.TaskGroupContainer - taskGroup[1420] completed it's tasks.
20:40:03.035 logback [taskGroup-1450] INFO  c.j.e.c.taskgroup.TaskGroupContainer - taskGroup[1450] completed it's tasks.
20:40:03.064 logback [137-1370-0-reader] INFO  c.j.e.r.r.CommonRdbmsReader$Task - Finished read record by Sql: [] jdbcUrl:[].
20:40:03.134 logback [taskGroup-1370] INFO  c.j.e.c.taskgroup.TaskGroupContainer - taskGroup[1370] taskId[0] is successed, used[1305]ms
20:40:03.135 logback [taskGroup-1370] INFO  c.j.e.c.taskgroup.TaskGroupContainer - taskGroup[1370] completed it's tasks.
20:40:03.235 logback [taskGroup-1400] INFO  c.j.e.c.taskgroup.TaskGroupContainer - taskGroup[1400] taskId[0] is successed, used[1405]ms
20:40:03.235 logback [taskGroup-1400] INFO  c.j.e.c.taskgroup.TaskGroupContainer - taskGroup[1400] completed it's tasks.
20:40:05.246 logback [143-1430-0-reader] INFO  c.j.e.r.r.CommonRdbmsReader$Task - Finished read record by Sql: [] jdbcUrl:[].
20:40:05.337 logback [taskGroup-1430] INFO  c.j.e.c.taskgroup.TaskGroupContainer - taskGroup[1430] taskId[0] is successed, used[3507]ms
20:40:05.337 logback [taskGroup-1430] INFO  c.j.e.c.taskgroup.TaskGroupContainer - taskGroup[1430] completed it's tasks.
20:40:06.643 logback [136-1360-0-reader] INFO  c.j.e.r.r.CommonRdbmsReader$Task - Finished read record by Sql: [] jdbcUrl:[].
20:40:06.938 logback [taskGroup-1360] INFO  c.j.e.c.taskgroup.TaskGroupContainer - taskGroup[1360] taskId[0] is successed, used[5109]ms
20:40:06.939 logback [taskGroup-1360] INFO  c.j.e.c.taskgroup.TaskGroupContainer - taskGroup[1360] completed it's tasks.
20:40:11.827 logback [job-136] INFO  c.j.e.c.s.c.c.j.StandAloneJobContainerCommunicator - Total 26054 records, 10063686 bytes | Speed 982.78KB/s, 2605 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 2.328s |  All Task WaitReaderTime 9.462s | Percentage 600.00%
20:40:11.828 logback [job-136] INFO  c.j.e.c.j.s.AbstractScheduler - Scheduler accomplished all tasks.
20:40:11.828 logback [job-140] INFO  c.j.e.c.s.c.c.j.StandAloneJobContainerCommunicator - Total 26054 records, 10063686 bytes | Speed 982.78KB/s, 2605 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 2.328s |  All Task WaitReaderTime 9.462s | Percentage 600.00%
20:40:11.828 logback [job-142] INFO  c.j.e.c.s.c.c.j.StandAloneJobContainerCommunicator - Total 26054 records, 10063686 bytes | Speed 982.78KB/s, 2605 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 2.328s |  All Task WaitReaderTime 9.462s | Percentage 600.00%
20:40:11.828 logback [job-143] INFO  c.j.e.c.s.c.c.j.StandAloneJobContainerCommunicator - Total 26054 records, 10063686 bytes | Speed 982.78KB/s, 2605 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 2.328s |  All Task WaitReaderTime 9.462s | Percentage 600.00%
20:40:11.828 logback [job-137] INFO  c.j.e.c.s.c.c.j.StandAloneJobContainerCommunicator - Total 26054 records, 10063686 bytes | Speed 982.78KB/s, 2605 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 2.328s |  All Task WaitReaderTime 9.462s | Percentage 600.00%
20:40:11.828 logback [job-145] INFO  c.j.e.c.s.c.c.j.StandAloneJobContainerCommunicator - Total 26054 records, 10063686 bytes | Speed 982.78KB/s, 2605 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 2.328s |  All Task WaitReaderTime 9.462s | Percentage 600.00%

**Comment by TrafalgarLuo** [comment]
看任务执行日志， jobId 是不同的，是不同的datax同步进程。 是碰巧这几个任务的数据量比较一致？

**Comment by lihjChina** [comment]
并非几个任务数据量一致，每个表的数据是不一致的。我是启动了4个同步任务，同时读取4个表中的数据，同一秒同时启动多个任务后就可以出现这个问题了，必现问题。

**Comment by Y-evil** [comment]
这是个单机版的DataX，单机的意思就是：任务必须是串行处理的，处理完一个后接着下一个，不能同时进行。原因是他的配置读取和汇总统计信息不是根据jobId来区分的。如果一步步跟下去，会发现信息汇集在core工程下的LocalTGCommunicationManage类的静态变量taskGroupCommunicationMap上，这个map的key是taskGroupId而不是jobId。
可以在这里改下，新增一个以jodId为key的map，仿照他的逻辑来新增。当然不止改这一个类，看下LocalTGCommunicationManage这个类如何汇聚数据的逻辑，依葫芦画瓢就行。
还有core工程的LoadUtil.bind()也记得改下，这个方法是个单机版的，不改的话下个任务的配置会覆盖掉上一个任务的配置，导致任务只能一个个执行。
