### ISSUE TITLE
odpswriter分区配置问题

### ISSUE THREAD

**Issue by lxk403216058** [alibaba/DataX#1439]
如果分区配置是"partition": "dt"这样话会默认填一个yyyyMMdd格式的当前日期作为dt的值，如果我想要一个yyyyMM格式的当前月份作为dt的值该怎么配置

**Comment by TrafalgarLuo** [comment]
"partition": "dt=${dt}"

datax.py job.json -p"-Ddt=202207"

类似这种，可以从外层传递参数，给代码json中的配置进行参数替换
