### ISSUE TITLE
mysqlwriter 是否支持分库分表后的写入

### ISSUE THREAD

**Issue by panqizhen** [alibaba/DataX#1447]
数据库使用了shardingsphere-proxy版本5.1.2, 分库分表, 写入的时候不知道为什么会读取到分片算法. 按道理应该是insert的时候,shardingsphere自己判断写入哪个分表.
![image](https://user-images.githubusercontent.com/22044790/178869959-66ff40db-b2f7-4edf-a57c-62e994e41f5d.png)

**Comment by panqizhen** [comment]
发现是我分片规则用%取模,有时候不能正确判断数字, 后来换成mod取模就可以了

**Comment by starsun2013** [comment]
你好，请问下mysqlwriter 分表写入的规则在哪里配置呢
