### ISSUE TITLE
[compile] mvn 编译单个插件报错

### ISSUE THREAD

**Issue by HanibalGK** [alibaba/DataX#145]
Information:
-------------------------------------------------------------------------------------------------------------------
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building gpdbwriter 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.alibaba.datax:datax-common:jar:0.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.alibaba.datax:plugin-rdbms-util:jar:0.0.1-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.259 s
[INFO] Finished at: 2018-07-17T23:46:13+08:00
[INFO] Final Memory: 8M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project gpdbwriter: Could not resolve dependencies for project com.alibaba.datax:gpdbwriter:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: com.alibaba.datax:datax-common:jar:0.0.1-SNAPSHOT, com.alibaba.datax:plugin-rdbms-util:jar:0.0.1-SNAPSHOT: Could not find artifact com.alibaba.datax:datax-common:jar:0.0.1-SNAPSHOT -> [Help 1]
-------------------------------------------------------------------------------------------------------------------

在给单独的插件打包的时候会报错，这个是什么情况，所有的依赖都有。
![image](https://user-images.githubusercontent.com/16936713/42829600-76a51d9a-8a1c-11e8-9a4f-91959b2b94d4.png)
麻烦问一下这个是因为什么？谢谢

**Comment by xxz7694** [comment]
兄弟你是不是把依赖项也给注释了, 这三个东西不要注释
![image](https://user-images.githubusercontent.com/38748747/92425590-4316cc00-f1ba-11ea-8331-260d6efb132b.png)

**Comment by TrafalgarLuo** [comment]
依赖的其他模块在本机没有install导致的。 可以把公共模块 mvn install到本地，然后再单独打包单个插件应该即可
