### ISSUE TITLE
编译tdenginereader报错

### ISSUE THREAD

**Issue by uuask** [alibaba/DataX#1451]
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://maven.aliyun.com/repository/central/com/alibaba/datax/tdenginewriter/tdenginewriter/0.0.1-SNAPSHOT/maven-metadata.xml
Downloading from central: https://maven.aliyun.com/repository/central/com/alibaba/datax/tdenginewriter/tdenginewriter/0.0.1-SNAPSHOT/tdenginewriter-0.0.1-SNAPSHOT.pom
[WARNING] The POM for com.alibaba.datax.tdenginewriter:tdenginewriter:jar:0.0.1-SNAPSHOT is missing, no dependency information available
Downloading from central: https://maven.aliyun.com/repository/central/com/alibaba/datax/tdenginewriter/tdenginewriter/0.0.1-SNAPSHOT/tdenginewriter-0.0.1-SNAPSHOT.jar
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Skipping datax-all
[INFO] This project has been banned from the build due to previous failures.
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] datax-all 0.0.1-SNAPSHOT ........................... SUCCESS [  0.100 s]
[INFO] datax-common ....................................... SUCCESS [  2.106 s]
[INFO] datax-transformer .................................. SUCCESS [  0.886 s]
[INFO] datax-core ......................................... SUCCESS [  2.224 s]
[INFO] plugin-rdbms-util .................................. SUCCESS [  0.387 s]
[INFO] tdenginereader ..................................... FAILURE [  0.861 s]
[INFO] plugin-unstructured-storage-util 0.0.1-SNAPSHOT .... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.752 s
[INFO] Finished at: 2022-07-21T15:28:25+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project tdenginereader: Could not resolve dependencies for project com.alibaba.datax:tdenginereader:jar:0.0.1-SNAPSHOT: Could not find artifact com.alibaba.datax.tdenginewriter:tdenginewriter:jar:0.0.1-SNAPSHOT in central (https://maven.aliyun.com/repository/central) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :tdenginereader

**Comment by TrafalgarLuo** [comment]
目前相关问题已经fix，感谢您的反馈
