### ISSUE TITLE
File "/my/datax/bin/datax.py", line 114

### ISSUE THREAD

**Issue by DreamPWJ** [alibaba/DataX#1472]
print readerRef
    ^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

python3 versin

cd /my/datax/bin && python3 datax.py /my/datax/job/datax_job.json

**Comment by DreamPWJ** [comment]
使用的python3.10

**Comment by dingxiaobo** [comment]
启动脚本未适配python3，
请使用 python2
