### ISSUE TITLE
mysql数据迁移到tdengine

### ISSUE THREAD

**Issue by dev007-art** [alibaba/DataX#1476]
int类型数据迁移时报错
ERROR StdoutPluginCollector - 脏数据:
{"exception":"invalid column type: LONG","record":[{"byteSize":1,"index":0,"rawData":4,"type":"LONG"},{"byteSize":6,"index":1,"rawData":"dasdsa","type":"STRING"},{"byteSize":8,"index":2,"rawData":1660042031000,"type":"DATE"}],"type":"writer"}

**Comment by dingxiaobo** [comment]
@dev007-art 

感谢反馈，问题已修复： #1541

在下一个release之前，可以先自行从 master 打包使用
