### ISSUE TITLE
version 4.0.3 Where 不支持复杂or条件

### ISSUE THREAD

**Issue by caomeng05** [alibaba/DataX#1477]
适用column从kudu集群之间同步数据，发现where条件中如果存在or条件，则数据只会同步前半部分条件对应的数据；

**Comment by dingxiaobo** [comment]
请问源端是什么类型？

**Comment by caomeng05** [comment]
Hi：
    您好，感谢回复；用datax抽取的源端是kudu源，用or条件会导致漏数据，和实际用sql查出来的数据不一致；
     where部分为：((time_key >= '2022M08' and time_key <= '2022M08' ) or (time_key >= '2022W40' and time_key <= '2022W45'))
望回复，谢谢！


***@***.***
 
发件人： dingxiaobo
发送时间： 2022-10-12 16:58
收件人： alibaba/DataX
抄送： caomeng05; Author
主题： Re: [alibaba/DataX] version 4.0.3 Where 不支持复杂or条件 (Issue #1477)
请问源端是什么类型？
―

**Comment by dingxiaobo** [comment]
> Hi： 您好，感谢回复；用datax抽取的源端是kudu源，用or条件会导致漏数据，和实际用sql查出来的数据不一致； where部分为：((time_key >= '2022M08' and time_key <= '2022M08' ) or (time_key >= '2022W40' and time_key <= '2022W45')) 望回复，谢谢！ ***@***.*** 发件人： dingxiaobo 发送时间： 2022-10-12 16:58 收件人： alibaba/DataX 抄送： caomeng05; Author 主题： Re: [alibaba/DataX] version 4.0.3 Where 不支持复杂or条件 (Issue #1477) 请问源端是什么类型？ ― Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

DataX 未提供 kudu 抽取的插件，请检查是不是自己实现的kudu插件有bug？
