### ISSUE TITLE
hdfswriter无法正常写入

### ISSUE THREAD

**Issue by ljl0303** [alibaba/DataX#1488]
<img width="2340" alt="image" src="https://user-images.githubusercontent.com/33050576/186086656-16bcbca2-f465-4e1a-85a1-52b40e7b2c71.png">
<img width="574" alt="image" src="https://user-images.githubusercontent.com/33050576/186086740-804a922b-3544-42ff-8a7f-c66199196f5d.png">

**Comment by dingxiaobo** [comment]
defaultFS 配置成 "hdfs://192...9000"

**Comment by ljl0303** [comment]
> 

woc我试下看看,我是重新自己写了下hdfs插件了- -
