### ISSUE TITLE
使用datax如何通过时间戳进行增量数据的捞取?为何运行一段时间后老是会漏数据？

### ISSUE THREAD

**Issue by ZhiXingHeYiApple** [alibaba/DataX#15]
基于时间戳字段利用datax来捞取增量数据，我每次都是以脚本执行起始时刻作为下一次捞取增量数据的依据？至于漏数据，目前能想到的有以下两种可能原因：
1. 数据库节点和datax节点的时间没有校准，存在误差。
2. mysql数据库的主从同步延迟因素没有考虑进来。
除了上述因素，如果还有其他因素可能导致这种情况，还请不吝赐教。
让时间窗口存在一定叠加（部分数据会存在重复捞取），不知能否解决这个问题？

**Comment by binaryWorld** [comment]
1、统一时钟问题确实存在，建议你数据库机器与执行DataX机器 使用同一的时钟；
2、主备延迟问题：你可以在mysqlreader的presql中写一些主备同步是否完成的检测语句，这样检测通过后才会支持后续同步

**Comment by wajika** [comment]
> 1、统一时钟问题确实存在，建议你数据库机器与执行DataX机器 使用同一的时钟；
> 2、主备延迟问题：你可以在mysqlreader的presql中写一些主备同步是否完成的检测语句，这样检测通过后才会支持后续同步

增量功能是怎么实现的？

**Comment by youzipi** [comment]
> 1、统一时钟问题确实存在，建议你数据库机器与执行DataX机器 使用同一的时钟；
> 2、主备延迟问题：你可以在mysqlreader的presql中写一些主备同步是否完成的检测语句，这样检测通过后才会支持后续同步

@binaryWorld 我看了下代码，目前（2020-10-15）mysqlreader 的 presql 功能是还没有支持吗？
如果自己实现的话，我要怎么才能终止 后续操作呢？
