### ISSUE TITLE
达梦数据库读取数据读错数据库了

### ISSUE THREAD

**Issue by llingfeng** [alibaba/DataX#1508]
达梦数据库读取数据时，如果数据库用户下有多个数据库（schema），配置完成后，datax读取的是数据库（schema）是对应连接用户同名的数据库，而不是jdbcurl指定的数据库。

> "parameter": {
                        "username": "test_user",
                        "password": "12345qwert",
                        "column": [
                            "id",
                            "name"
                        ],
                        "connection": [
                            {
                                "table": [
                                    "student"
                                ],
                                "jdbcUrl": [
                                  "jdbc:dm://192.168.0.81:5236/KAIFA"
                                ]
                            }
                        ],
                        "fetchSize": 1024,
                        "where": "1 = 1"
                    }

例如上面代码：我其实是想连接kAIFA这个数据库，结果连接之后发现读取的是用户test_user同名的数据库test_user。
我目前的解决方案是在table指定数据库名称：
`"table": [
                                    "KAIFA.student"
                                ],
`
不知道这是不是个bug，还是说我配置文件写的有问题。

**Comment by dingxiaobo** [comment]
达梦的JDBC URL定义有点特殊，以`"jdbc:dm://192.168.0.81:5236/KAIFA"` 为例，KAIFA并不是达梦SCHEMA，

在新版本的达梦8驱动中，指定SCHEMA的方式是这样的：`"jdbc:dm://192.168.0.81:5236?schemaName=KAIFA"`，我也觉得这个设计很让人费解。

DataX暂未升级达梦驱动，就按照 `"table": [ "KAIFA.student" ]` 继续用吧。
