### ISSUE TITLE
channel 配置不起作用

### ISSUE THREAD

**Issue by XhivaW** [alibaba/DataX#151]
如题
在从Oracle导入hdfs过程中，使用oraclereader中的“table“参数配置  column选择全部 无论Oracle
源表数据量多少 不管怎么手动修改channel 运行起来依然只有一个task 想问一下是否正常？如果不是 该如何修改？

**Comment by XhivaW** [comment]
@VincentSleepless 谢谢解惑

**Comment by xubing88** [comment]
@XhivaW  你可以设置splitPk，选择合适的splitPk就会加快同步效率，会有分片的

**Comment by Sowevo** [comment]
当时用querysql查询时，SPLITPK应该如何设置呢

**Comment by Tu-maimes** [comment]
配置splitPK为id设置六个通道不生效求解
