### ISSUE TITLE
oraclereader 在读取的资料时，会将字段内容的空格给 trim 掉

### ISSUE THREAD

**Issue by kuo0528** [alibaba/DataX#1515]
测试使用 oraclereader 读 「AAA 」 含空格的资料内容，并以 streamwriter 做 print 输出，发现输出结果为 「AAA」，空格不见了...

**Comment by dingxiaobo** [comment]
DataX 不会 trim 驱动返回的数据，可以自己用 ojdbc 驱动测试下看看是不是驱动返回的数据就是 trim 后的。
