### ISSUE TITLE
如何实现脏数据精确过滤、识别、采集、展示

### ISSUE THREAD

**Issue by qianleijava** [alibaba/DataX#1517]
在官方介绍中提到了，提供脏数据探测功能，请问如何实现脏数据探测？

官方介绍原文：
DataX 3.0六大核心优势
提供脏数据探测

在大量数据的传输过程中，必定会由于各种原因导致很多数据传输报错(比如类型转换错误)，这种数据DataX认为就是脏数据。DataX目前可以实现脏数据精确过滤、识别、采集、展示，为用户提供多种的脏数据处理模式，让用户准确把控数据质量大关！

**Comment by yaoleifly** [comment]
同问

**Comment by dingxiaobo** [comment]
本项目默认提供了日志输出脏数据收集器，在日志输出中展示脏数据内容以及脏数据的原因：`com.alibaba.datax.core.statistics.plugin.task.StdoutPluginCollector#collectDirtyRecord`

有外部展示需求的，也可以自实现 `com.alibaba.datax.core.statistics.plugin.task.AbstractTaskPluginCollector`，
修改 `core.statistics.collector.plugin.taskClass` 配置，切换脏数据收集器。
