### ISSUE TITLE
开源的，也是你们阉割的东西，还是带货思路，真没劲，

### ISSUE THREAD

**Issue by yaoleifly** [alibaba/DataX#1528]
。。。。。。。。。

**Comment by dingxiaobo** [comment]
商业版致力于提供复杂网络环境下、丰富的异构数据源之间高速稳定的数据移动能力，以及繁杂业务背景下的数据同步解决方案，

我们不会故意阉割功能，我们会根据阿里巴巴开源合规的规范定期发布功能到开源DataX，请放心使用。

**Comment by mozhe24** [comment]
开源的datax3，是不是不支持distributed模式呢？

**Comment by dingxiaobo** [comment]
> 开源的datax3，是不是不支持distributed模式呢？

不支持，分布式模式是依赖管控服务协调的，管控服务没法开源
