### ISSUE TITLE
你们开源却不维护，那能不能交给大家维护。

### ISSUE THREAD

**Issue by Y-evil** [alibaba/DataX#1531]

**Comment by LitteCandy0511** [comment]
你是在使用的过程中遇到了什么问题吗？

**Comment by dingxiaobo** [comment]
开源DataX由开源社区的大家和阿里巴巴共同维护。

我们会根据阿里巴巴开源合规的规范定期发布功能到开源DataX。

看到你为其他人答疑解惑👍🏻，感谢你的付出。
