### ISSUE TITLE
Datax读取Mysql数据是先把数据全部查询后再写入RecordSender吗

### ISSUE THREAD

**Issue by krz1997** [alibaba/DataX#1539]
如题，目前遇见一个较大数据量的全表查询。Datax是否是先select * 全量数据后再写入channel吗，是否会有效率问题

**Comment by dingxiaobo** [comment]
是流式读取MySQL数据的，边读边写入channel的

**Comment by krz1997** [comment]
> 是流式读取MySQL数据的，边读边写入channel的

好的谢谢。 我看了源码设置了fetchSize。
