### ISSUE TITLE
ClassNotFoundException: com.alibaba.datax.plugin.writer.hologreswriter.HologresWriter

### ISSUE THREAD

**Issue by codingxmh** [alibaba/DataX#1547]
hologresjdbcwriter/plugin.json
hologresjdbcwriter/plugin_job_template.json
配置错误，导致执行报错

正确的应该是
{
  "name": "hologresjdbcwriter",
  "class": "com.alibaba.datax.plugin.writer.hologresjdbcwriter.HologresJdbcWriter",
  "description": "",
  "developer": "alibaba"
}

**Comment by dingxiaobo** [comment]
感谢反馈，已修复：#1549
