### ISSUE TITLE
 About the problem of using datax to read source data to falsely report dirty data, resulting in failure to read database data

### ISSUE THREAD

**Issue by JJiacheng** [alibaba/DataX#1563]
<img width="675" alt="image" src="https://user-images.githubusercontent.com/108396409/197331993-884f51b7-bf74-4f2b-9c29-257710762645.png">

**Comment by dingxiaobo** [comment]
建议使用 zeroDateTimeBehavior 解决此问题，`jdbc:mysql://host:3306/test?zeroDateTimeBehavior=convertToNull`

**Comment by JJiacheng** [comment]
datax中默认zeroDateTimeBehavior=convertToNull属性，针对0000-00-00 12:00:00这种带时分秒的数据处理并没有生效，会抛出上图异常。

**Comment by JJiacheng** [comment]
<img width="199" alt="image" src="https://user-images.githubusercontent.com/108396409/197388840-6fc4fe6f-7114-4a85-9c78-86fc89650edc.png">
源端如果时分秒不是00:00:00这种的话 还是会抛出异常
