### ISSUE TITLE
抽取mysql的数据，如果最合适的切分键有一半null值，有什么能提高效率的办法吗？

### ISSUE THREAD

**Issue by ZaneZ7** [alibaba/DataX#1566]

**Comment by dingxiaobo** [comment]
暂时没有好办法

“如果最合适的切分键有一半null值”，
得看看这业务使用MySQL是否合适、是否正确了

**Comment by ZaneZ7** [comment]
> 

主要是主键id用的varchar类型，splitPk似乎现在不支持int以外的类型

**Comment by dingxiaobo** [comment]
可以用多个任务

每个任务的where条件设置的不一样

比如 

任务1  id like 'a%' or id like 'b%'
任务2  id like 'c%' or id like 'd%'

... 类推
