### ISSUE TITLE
希望 postgresqlreader 插件可以支持读取 UUID 类型的字段

### ISSUE THREAD

**Issue by kaelmeepo** [alibaba/DataX#1574]
通过 `postgresqlreader` 读取数据时提示：

Code:[DBUtilErrorCode-12], Description:[不支持的数据库类型. 请注意查看 DataX 已经支持的数据库类型以及数据库版本.].  - 您的配置文件中的列配置信息有误. 因为DataX 不支持数据库读取这种字段类型. 字段名:[id], 字段名称:[1111], 字段Java类型:[java.util.UUID]. 请尝试使用数据库函数将其转换datax支持的类型 或者不同步该字段 .

不知道可不可以帮忙支持读取 `UUID` 类型的字段，谢谢！

**Comment by dingxiaobo** [comment]
可以在 column 里直接写pg函数，把uuid转成varchar

**Comment by kaelmeepo** [comment]
确实可以，感谢大佬！
