### ISSUE TITLE
mysql导入数据导doris报错，找不出原因，是doriswriter有问题吗

### ISSUE THREAD

**Issue by mgua1998** [alibaba/DataX#1579]
2022-10-28 17:49:36.140 [job-0] INFO  StandAloneJobContainerCommunicator - Total 23619 records, 2680280 bytes | Speed 261.75KB/s, 2361 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.109s |  All Task WaitReaderTime 0.217s | Percentage 0.00%
2022-10-28 17:49:36.140 [job-0] ERROR JobContainer - 运行scheduler 模式[standalone]出错.
2022-10-28 17:49:36.141 [job-0] ERROR JobContainer - Exception when job run
com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-05], Description:[往您配置的写入表中写入数据时失败.].  - java.lang.RuntimeException: Writing records to Doris failed.
        at com.alibaba.datax.plugin.writer.doriswriter.DorisWriterManager.close(DorisWriterManager.java:113)
        at com.alibaba.datax.plugin.writer.doriswriter.DorisWriter$Task.post(DorisWriter.java:150)
        at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:65)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Writing records to Doris failed.
        at com.alibaba.datax.plugin.writer.doriswriter.DorisWriterManager.checkFlushException(DorisWriterManager.java:189)
        at com.alibaba.datax.plugin.writer.doriswriter.DorisWriterManager.waitAsyncFlushingDone(DorisWriterManager.java:150)
        at com.alibaba.datax.plugin.writer.doriswriter.DorisWriterManager.flush(DorisWriterManager.java:98)
        at com.alibaba.datax.plugin.writer.doriswriter.DorisWriterManager.close(DorisWriterManager.java:111)
        ... 3 more
Caused by: java.io.IOException: java.io.IOException: Unable to flush data to Doris: unknown result status.
        at com.alibaba.datax.plugin.writer.doriswriter.DorisWriterManager.asyncFlush(DorisWriterManager.java:170)
        at com.alibaba.datax.plugin.writer.doriswriter.DorisWriterManager.access$000(DorisWriterManager.java:19)
        at com.alibaba.datax.plugin.writer.doriswriter.DorisWriterManager$1.run(DorisWriterManager.java:134)
        ... 1 more
Caused by: java.io.IOException: Unable to flush data to Doris: unknown result status.
        at com.alibaba.datax.plugin.writer.doriswriter.DorisStreamLoadObserver.streamLoad(DorisStreamLoadObserver.java:66)
        at com.alibaba.datax.plugin.writer.doriswriter.DorisWriterManager.asyncFlush(DorisWriterManager.java:163)
        ... 3 more
 - java.lang.RuntimeException: Writing records to Doris failed.
        at com.alibaba.datax.plugin.writer.doriswriter.DorisWriterManager.close(DorisWriterManager.java:113)
        at com.alibaba.datax.plugin.writer.doriswriter.DorisWriter$Task.post(DorisWriter.java:150)
        at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:65)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Writing records to Doris failed.
        at com.alibaba.datax.plugin.writer.doriswriter.DorisWriterManager.checkFlushException(DorisWriterManager.java:189)
        at com.alibaba.datax.plugin.writer.doriswriter.DorisWriterManager.waitAsyncFlushingDone(DorisWriterManager.java:150)
        at com.alibaba.datax.plugin.writer.doriswriter.DorisWriterManager.flush(DorisWriterManager.java:98)
        at com.alibaba.datax.plugin.writer.doriswriter.DorisWriterManager.close(DorisWriterManager.java:111)
        ... 3 more

**Comment by mgua1998** [comment]
doris版本 1.1.2 dataX是 release 202210 是版本兼容问题吗

**Comment by mgua1998** [comment]
已解决

**Comment by ppooii123** [comment]
> 已解决

兄弟你这个怎么处理的

**Comment by wy281704862** [comment]
怎么解决的？ 遇到了同样的问题。

**Comment by wy281704862** [comment]
数据量太大，改小maxBatchRows的配置

**Comment by mgua1998** [comment]
> > 已解决
> 
> 兄弟你这个怎么处理的

doris建表的字段大小给小了，有些长文本

**Comment by shadong1** [comment]
doriswriter的出现报错时，就总是报Writing records to Doris failed.也不报具体是方面的错误，例如常见的字段中的数据中存在特殊符号，也报不出来是那个字段的那个特殊字符导致的，就回导致排查原因 起来特别麻烦，会浪费大量时间
