### ISSUE TITLE
mysql到es 遇到es的403报错

### ISSUE THREAD

**Issue by chengzhen123** [alibaba/DataX#1583]
mysql5.7
elasticsearch 7.14
从mysql同步数据到es时，报错。报错内容是：

经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[ESWriter-03], Description:[The mappings error.].  - Request PUT http://ip:9001/indexname?master_timeout=5m HTTP/1.1 yielded text/html, should be json: HTTP/1.1 403 Forbidden - java.io.IOException: Request PUT http://ip:9001/indexname?master_timeout=5m HTTP/1.1 yielded text/html, should be json: HTTP/1.1 403 Forbidden

**Comment by dingxiaobo** [comment]
es有账号密码，但是任务没配吧？

**Comment by yhzWinchester** [comment]
配置了accessId 和 accessKey 还是403

**Comment by yhzWinchester** [comment]
使用curl -u accessId:accessKey 可以访问
