### ISSUE TITLE
按照业务中定义的标记字段做增量更新，如何更新源的标记字段

### ISSUE THREAD

**Issue by pythonzhu** [alibaba/DataX#1587]
由于业务的特性，还有老项目的情况。
每个业务表都有一个flag标记是否需要同步，reader读取flag=0的记录，然后同步至目标数据。
现在需求是 writer后，根据主键更新源表的flag=1.

**Comment by dingxiaobo** [comment]
datax不具备这个功能，可以自行用脚本等方式解决。
