### ISSUE TITLE
date类型往MySQL导入数据没有时分秒

### ISSUE THREAD

**Issue by southerly22** [alibaba/DataX#1591]
场景：hdfs上的csv文件的日期格式：2022-10-11T21:29:57.000+08:00，导入到mysql 里面变成了 2022-10-11 00：00：00，期望格式：2022-10-11 21:29:57

主要json如下：
"reader": {
                    "name": "hdfsreader",
                    "parameter": {
                        "path": "/mysqldata/type_list/*",
                        "defaultFS": "hdfs://192.168.xx:8020",
                        "column": [
                               {
                                "index": 0,
                                "type": "Long"
                               },
                               {
                                "index": 1,
                                "type": "String"
                               },
                               {
                                "index": 2,
                                "type": "date"
                               }
                        ],
			            "fileType": "csv",
                        "encoding": "UTF-8",
                        "fieldDelimiter": ",",
                        "skipHeader": "true"
                    }

                },
               	"writer": {

				"name": "mysqlwriter",
				"parameter": {
					"writeMode": "insert",
					"username": "root",
					"password": "123456",
					"batchSize":"100000",
                                       "dateFormat":"yyyy-MM-dd HH:mm:ss",
					"column": [
						"id",
						"type_name",
                                                "create_time"
					],
csv文件：
id  type_name   create_time
1   AT_pe   2022-10-11T21:29:57.000+08:00

**Comment by dingxiaobo** [comment]
改读端配置，加format参数

```
[
    {
        "index": 0,
        "type": "Long"
    },
    {
        "index": 1,
        "type": "String"
    },
    {
        "index": 2,
        "type": "date",
        "format": "yyyy...."
    }
]
```
