### ISSUE TITLE
如何解决导入Mssql，ID自增问题

### ISSUE THREAD

**Issue by ShieldYu** [alibaba/DataX#1620]
因为ID是自增，所以向sql server中导入自增id的值时，会报不能插入自增ID的报错。尝试了在presql中执行关闭自增。应该是多个task，起的不同的连接，无法作用于插入的语句，因此报错。想知道大家是怎么解决这个问题的

**Comment by didostream** [comment]
自增ID不要read也不要write，自己会生成出来的。当然如果你是通过ID关联，这个就没招了
