### ISSUE TITLE
java.lang.ClassCastException: com.alibaba.fastjson.JSONObject cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by yiliou** [alibaba/DataX#1633]
迁移脚本示例：
{
    "job": {
        "setting": {
            "speed": {
                "channel": 8
            },
            "errorLimit": {
                "record": 0,
                "percentage": 0.02
            }
        },
        "content": [{
            "reader": {
                "name": "mysqlreader",
                "parameter": {
                    "username": "xxx",
                    "password": "xxx",
                    "connection": [{
                        "querySql": [
                            "SELECT
										ID,
										
										( CASE CZBZ WHEN '1' THEN "{'dy':'1'}" END ) CZBZ,
										
									 
									FROM
										test "
                        ],
                        "jdbcUrl": [
                            "xxxx"
                        ]
                    }]
                }
            },
            "writer": {
                "name": "mysqlwriter",
                "parameter": {
                    "writeMode": "update(id)",
                    "username": "xxxx",
                    "password": "xxxx",
                    "column": [
								ID,
								
						       CZBZ
                        
                    ],
                    "connection": [{
                        "jdbcUrl": "xxxxx",
                        "table": [
                            "test"
                        ]
                    }]
                }
            }
        }]
    }
}

**Comment by riruigit** [comment]
老哥 解决了吗 ？  我也遇到这个问题了

**Comment by yiliou** [comment]
解决了
解决方案：( CASE CZBZ WHEN '1' THEN '{''dy'':''1''}' END ) CZBZ,
