### ISSUE TITLE
多表同步数据问题

### ISSUE THREAD

**Issue by txhan0703** [alibaba/DataX#1680]
datax一个job.json内是否可以通过配置的方式多表对多表传输？

**Comment by bodhibudd** [comment]
好像是不支持的，写入的时候已经指定了columns中同步写入的字段，除非多个表中同步的字段都是一样的

**Comment by dingxiaobo** [comment]
> 好像是不支持的，写入的时候已经指定了columns中同步写入的字段，除非多个表中同步的字段都是一样的

正解~
