### ISSUE TITLE
datax 读取 hive分区的数据，读数会变少

### ISSUE THREAD

**Issue by yqzdy1207** [alibaba/DataX#1694]
现象：datax 读取 hive分区的数据，读数会变少。原本6亿数据，变成了3亿
自测方案：我找了个2千万的小表。测试同样少了一部分，经过自查问题。
测试后：当hdfs的文件大小大于blocksize的时候，会有丢数据的问题。

**Comment by yqzdy1207** [comment]
找到了，是这个问题。

**Comment by yqzdy1207** [comment]
https://github.com/alibaba/DataX/pull/262/commits/e2dcbcd532bebdb46992ab58b53ae37f1477cec0

**Comment by dingxiaobo** [comment]
#262 修复了这个问题，可以自行从master 代码编译使用哈
