### ISSUE TITLE
mysql8.0的支持

### ISSUE THREAD

**Issue by maliqiang** [alibaba/DataX#172]
mysql8.0的covertToNull已经改写为COVERT_TO_NULL，Driver路径改变，需要支持

**Comment by Sod-Momas** [comment]
同遇到这个问题,驱动需要更新,并且还要指定
`serverTimezone=UTC`
你解决了吗?

**Comment by maliqiang** [comment]
> 同遇到这个问题,驱动需要更新,并且还要指定
> `serverTimezone=UTC`
> 你解决了吗?

解决了，自己改了源码升级了驱动。需要制定UTC这个是的，在url加上就行

**Comment by bingryan** [comment]
mysql8 之后，mysql的读写插件都要更新为最新的j a r

**Comment by bingryan** [comment]
datax维护者是否可以更新一下，编译后的直接下Download [DataX下载地址](http://datax-opensource.oss-cn-hangzhou.aliyuncs.com/datax.tar.gz)上面的一些插件和j a r

**Comment by liqingrikeiikyeong** [comment]
还 有oracle 12c

**Comment by tmljob** [comment]
> datax维护者是否可以更新一下，编译后的直接下Download [DataX下载地址](http://datax-opensource.oss-cn-hangzhou.aliyuncs.com/datax.tar.gz)上面的一些插件和j a r

现在支持 mysql 8了吗？这个“[DataX下载地址](http://datax-opensource.oss-cn-hangzhou.aliyuncs.com/datax.tar.gz)”都打不开了？

**Comment by dingxiaobo** [comment]
DataX 现已支持，欢迎使用新版本
