### ISSUE TITLE
读oraclereader是正常的,oraclewriter报驱动找不到

### ISSUE THREAD

**Issue by zenas001** [alibaba/DataX#1723]
![image](https://user-images.githubusercontent.com/10783723/226506902-6e9b1647-3c7d-4ce8-a2a3-bdd3b91d0af3.png)
这是我的配置
![image](https://user-images.githubusercontent.com/10783723/226506979-c41dbfa0-d564-475a-a814-76fffb9bc8cd.png)

**Comment by zenas001** [comment]
版本v202210

**Comment by dingxiaobo** [comment]
oracle jdbc url 前缀配的不对
