### ISSUE TITLE
ADSReader

### ISSUE THREAD

**Issue by huangyu2021** [alibaba/DataX#1737]
有计划出ADSReader吗？

**Comment by dingxiaobo** [comment]
使用 mysql reader 即可。

**Comment by huangyu2021** [comment]
但是一旦ads数据量过大，同步一段时间之后，解析字段就会出问题，会将多个字段合并成一个字段，然后数据类型转换就会报错。 @dingxiaobo

**Comment by huangyu2021** [comment]
[https://github.com/alibaba/DataX/issues/1599](url)
比如这个问题。 @dingxiaobo
