### ISSUE TITLE
mysql读读取关键字报错

### ISSUE THREAD

**Issue by ifansay** [alibaba/DataX#1745]
mysqlreader和mysqlwriter时，表有condition列，使用`condition`查询在解析中报错，但另一个mysqlreader+starrockswriter没有问题

**Comment by ifansay** [comment]
配置的querySql "select  `condition` , `_MASK_FROM_V2`, `amazon_order_id`, `amount_per_unit`  from e_compensate_info;"
报错信息 com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'condition,_MASK_FROM_V2,amazon_order_id,amount_per_unit' at line 1

**Comment by dingxiaobo** [comment]
修改任务配置

"column": ["`condition `", ... ]
