### ISSUE TITLE
writer为mysql时 如何自动create 和reader数据库一样的table 

### ISSUE THREAD

**Issue by effieHAN** [alibaba/DataX#1747]
将数据从sql server 迁移到mysql 但是mysql中没有对应的空表格 就会报错 试过了在preSql 里写CREATE TABLE bas_hisdistribution like ggbase.bas_hisdistibution;
但是datax 仍返回 经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[MYSQLErrCode-04], Description:[表不存在，请检查表名或者联系DBA确认该表是否存在].  - 表名为：bas_hisdistribution 执行的SQL为:select * from bas_hisdistribution where 1=2 具体错误信息为：com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'ggbase.bas_hisdistribution' doesn't exist

**Comment by weishuai8888** [comment]
您好，您的问题解决了吗？我遇到的问题和您的类似。我也想迁移表结构，但不知道如何操作！

**Comment by effieHAN** [comment]
需要自己提前在mysql 建好新表格的schema 我用了mysql workbench 自带的migration wizard

weishuai ***@***.***> 于2023年5月22日周一 16:31写道：

**Comment by weishuai8888** [comment]
明白！十分感谢分享经验😊

**Comment by Y-evil** [comment]
可以自己写prehandle阶段的插件.在JobContainer.start()方法中,init()方法执行时就会检测数据库中是否有对应的表,所以建表操作只能在init()前执行,即prehandle()方法中.
prehandle()方法在执行时会去加载对应的prehandle插件,然后执行插件的preHandler()方法,当前DataX并未提供对应的prehandle插件,需要自己写.

**Comment by czxin788** [comment]
我想用datax做AB表切换，遇到和你同样的问题。
写了presql，但是datax并不是先执行presql里面的语句，而是先判断"connection": [{
                        "jdbcUrl": "jdbc:mysql://127.0.0.1:3306/dota2_databank",
                        "table": ["tb_dmp_requser"]
                    }]
里面的table是否存在。
这个不符合我的需求，怎么能让datax先不要判断connection里面的表是否存在，直接先执行presql，然后再判断connection里面的表是否存在呢
