### ISSUE TITLE
有计划支持GaussDB(openGauss)吗？

### ISSUE THREAD

**Issue by hyjlmj** [alibaba/DataX#1758]
最近数据迁移会使用GaussDB(openGauss)，请问有计划支持么？

**Comment by LitteCandy0511** [comment]
已经支持了

**Comment by IBeihe** [comment]
@jtchen-study 我看最新版包插件里没有gauss的啊

**Comment by zhoutian94** [comment]
> @jtchen-study 我看最新版包插件里没有gauss的啊

https://github.com/alibaba/DataX/releases/tag/datax_v202309
下载后需要mvn编译

并且使用的时候如果提示java.lang.ClassNotFoundException: com.alibaba.datax.plugin.writer.gaussdbwriter.GaussDbWriter$Job，就修改下这个插件下的plugin.json，把类名改为"com.alibaba.datax.plugin.reader.gaussdbwriter.GaussDbWriter",因为我这里对应类的实际全类名是这个。
