### ISSUE TITLE
datax 自己开发新增加的插件模块无法本地打断点debug

### ISSUE THREAD

**Issue by wangxiang93** [alibaba/DataX#1766]
datax中新增加了一个插件 如kafkareader，本地想debug调试，发现这个kafka的reader无法打断点debug，其他原因模块如mysqlreader则可以进去打断点debug

**Comment by ilaotan** [comment]
有没有可能没调用到。。。。

**Comment by FuYouJ** [comment]
自己写了插件 自己要重新打包再运行
