### ISSUE TITLE
无法支持mysql函数

### ISSUE THREAD

**Issue by zuzhaoyue** [alibaba/DataX#177]
mysql数据库，在writer的postsql里写了replace()函数，同步没有报错，但是该函数没有奏效，writer配置如下 
"writer":{
                                "name":"mysqlwriter",
                                "parameter":{
                                        "column":[
                                                "\*"
                                        ],
                                        "connection":[
                                                {
                                                        "jdbcUrl":"jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF8",
                                                        "table":[
                                                                "user_listTemp"
                                                        ]
                                                }
                                        ],
                                        "password":"****",
                                        "postSql":[
                                                "update user_listTemp set email =replace(email,email,'\*')"
                                        ],
                                        "preSql":[],
                                        "session":[],
                                        "username":"root"
                                }
                        }

**Comment by aaronhadoop** [comment]
just do it yourself.
