### ISSUE TITLE
为什么自己本地测试的mysql->msyql的速度这么慢呢?

### ISSUE THREAD

**Issue by yangmeng66** [alibaba/DataX#1776]
我的tonggd通道是1, 但是我自己测试的速度和官网doc下的速度差很多, 这是什么原因呢?

![image](https://user-images.githubusercontent.com/51857567/236091198-8c884a09-58be-42cb-abe5-e8761c29c3f8.png)

![image](https://user-images.githubusercontent.com/51857567/236091118-3fc5819c-8070-4af4-94fd-b7e88cb675dc.png)

**Comment by zfq314** [comment]
是不是和机器性能有关

**Comment by FuYouJ** [comment]
速度和机器配置有关系的，尤其是写入
