### ISSUE TITLE
仓库还有人维护吗?

### ISSUE THREAD

**Issue by INBreezefall** [alibaba/DataX#1797]
开源老版本源码, 结果 PR 不接收, 分支混乱 自己内部维护自己的 datax 版本, 整合到 dataworks 里卖商业产品. 开源社区还卖个名声.只更新阿里自己用的 writer reader 插件. 这不是纯纯的 ex 人? 和 Apache 高下立判.

**Comment by ilaotan** [comment]
哈哈 主要卖产品。

**Comment by ColinChenX** [comment]
2023.05.25   看了一下，有874个issue是open的，最早的那个是2018.02.05的。汗 -_-||

**Comment by daxwang** [comment]
楼主明白人，大家散了吧

**Comment by jiaoyang3** [comment]
讲的很对，这么好的项目凉了

**Comment by Jinyun-Liu** [comment]
kpi项目
