### ISSUE TITLE
准备开发一个写neo4j的插件了，有需求的可以留言到这里

### ISSUE THREAD

**Issue by FuYouJ** [alibaba/DataX#1804]
在公司搞了半年的数据同步，但是主要是增量更新。
公司内部的版本是更新、新增都会使用，neo4j是一个具有事务的数据库，更新会有锁竞争，所以公司内部的版本是解决了锁竞争的问题的（死锁检查加重试）。
考虑到开源版本，大家都是用来新增吧，所以不打算处理锁竞争的问题。
有啥意见可以提，我近期准备动手写代码了

**Comment by FuYouJ** [comment]
[pull request](https://github.com/alibaba/DataX/pull/1814)

**Comment by daxwang** [comment]
写完neo4jwriter，求大佬再写一个nebula wirter

**Comment by FuYouJ** [comment]
> 写完neo4jwriter，求大佬再写一个nebula wirter

公司本来是预计下半年有一个nebula的迁移，应对客户需求，但是迟迟不下来，所以这个在计划中，取决于公司项目推进的速度咋样。

**Comment by FuYouJ** [comment]
> 写完neo4jwriter，求大佬再写一个nebula wirter

差不多 搞完了你可以直接拉我仓库打包就行

**Comment by daxwang** [comment]
neo4jwriter已经merge，大佬抽个时间搞下nebula writer呗

**Comment by FuYouJ** [comment]
> neo4jwriter已经merge，大佬抽个时间搞下nebula writer呗

后面项目用到了nebula我就会搞，工作所在公司有这个计划的

**Comment by daxwang** [comment]
大佬有想过跳槽不? 来我们公司啊
