### ISSUE TITLE
请问DataX支持在mysql->mysql 的update模式中根据某个字段更新记录吗？

### ISSUE THREAD

**Issue by hesenbai** [alibaba/DataX#1805]

**Comment by FuYouJ** [comment]
这个不是根据自己写的sql的关系吗，update on duplicate key update 语法

**Comment by hesenbai** [comment]
@FuYouJ 可是这个不也是根据主键来的嘛，我是想根据某个字段例如userId这种来更新。

**Comment by FuYouJ** [comment]
> @FuYouJ 可是这个不也是根据主键来的嘛，我是想根据某个字段例如userId这种来更新。

那你这样更新就很慢了呀

**Comment by hesenbai** [comment]
@FuYouJ 慢都还好可以，毕竟是定时去执行的，满足不了条件就很致命了，所以我最后选择了kettle。。
