### ISSUE TITLE
datax同步数据时，如果where字段没索引，对数据库压力大吗？

### ISSUE THREAD

**Issue by ilaotan** [alibaba/DataX#1809]
rt  代码里用Statement一个一个读的，每次读取都会受索引影响吗？ 还是说只影响第一次？

**Comment by ilaotan** [comment]
测试了下不走索引时，开始几分钟会卡住（根据数据量 可能时间会长），条数都是0，数据库cpu飙升，应该是慢查询轮全库的效果，只有一次，后面数据跑起来，cpu和iops就下来了

**Comment by WilliamTan778** [comment]
这个跟datax无关, 是您的where条件导致的, 如果没有索引,肯定效率低,对数据库压力大.
