### ISSUE TITLE
java.sql.SQLException: No suitable driver found for jdbc:hive2: #1028

### ISSUE THREAD

**Issue by eijintao** [alibaba/DataX#1819]
本地有两个hadoop集群(102集群和107集群)。hive版本是3.1.2   hadoop版本是3.2.2.。。准备从107集群读数据时报错了：
经DataX智能分析,该任务最可能的错误原因是:
23/06/28 15:03:21 INFO datax-web logger: >>> 2023-06-28 15:03:21 [AnalysisStatistics.analysisStatisticsLog-55] com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].  - 数据库连接失败. 因为根据您配置的连接信息,无法从:jdbc:hive2://192.168.10.107:10000/sensors 中找到可连接的jdbcUrl. 请检查您的配置并作出修改. - java.lang.Exception: DataX无法连接对应的数据库，可能原因是：1) 配置的ip/port/database/jdbc错误，无法连接。2) 配置的username/password错误，鉴权失败。请和DBA确认该数据库的连接信息是否正确。

但是我确定我的账号密码还有端口等等都是正确的。另外，通过读mysql ，写到102集群中。是可以成功的。
所以，我就郁闷了，为什么读不可以，写确是可以的。另外，针对这个问题，有什么好的解决方式吗？

**Comment by FuYouJ** [comment]
为什么读不可以，写确是可以的。很可能读写插件是两个人写的。
解决办法就是本地调试试试：看看是什么原因。
远程调试：https://cloud.tencent.com/developer/article/2085988
本地调试：https://blog.csdn.net/b452608/article/details/128805082

**Comment by eijintao** [comment]
> 为什么读不可以，写确是可以的。很可能读写插件是两个人写的。 解决办法就是本地调试试试：看看是什么原因。 远程调试：https://cloud.tencent.com/developer/article/2085988 本地调试：https://blog.csdn.net/b452608/article/details/128805082

好的，感谢感谢！

**Comment by LitteCandy0511** [comment]
目前开源社区没有集成 hive读写驱动, 尚不支持直读hive
