### ISSUE TITLE
mysql写入速度为0

### ISSUE THREAD

**Issue by Luharu** [alibaba/DataX#1824]
想要实现oracle到mysql的功能，第一天全部正常。第二天mysql的写入速度突然降低为0，但是使用命令行直接运行是没有问题的。测试结果oracle和mysql的读取功能也是正常的。求大佬指导

**Comment by Luharu** [comment]
[https://img-mid.csdnimg.cn/release/static/image/mid/ask/224134590886177.png?x-oss-process=image/auto-orient,1/resize,w_320,m_lfit](url)

**Comment by FuYouJ** [comment]
这个现象原因有很多，难说。重启能解决问题吗？

**Comment by penglin358** [comment]
请检查网络以及数据库负载
