### ISSUE TITLE
关于插件疑问

### ISSUE THREAD

**Issue by yangmeng66** [alibaba/DataX#1831]
你好, 
首先dataX是一款很优秀的异构数据源同步数据工具, 经过一段时间使用, 我有以下两点疑问, 期待你的回复
1 我们公司有自己的自研数据库, 也想开发dataX的读写插件合入社区, 请问有啥条件吗(比如: 代码规范, 用例测试通过等等)?
2 dataworks能不能直接用datax的插件? 我们后续也想对接dataworks来合作

**Comment by LitteCandy0511** [comment]
1、欢迎给 DataX贡献新插件，相关代码规范请参考： dataxPluginDev.md 
2、dataworks 数据集成是商业版 datax, 欢迎合作
