### ISSUE TITLE
datax速率问题请教

### ISSUE THREAD

**Issue by wanglaozhe** [alibaba/DataX#185]
我同步50万条数据，用了一分钟，请问下怎么提速啊？datax改变同步速率的参数是哪些？下面是日志信息
![_20170419162128](https://cloud.githubuse任务启动时刻                    : 2017-04-19 16:17:13
任务结束时刻                    : 2017-04-19 16:18:13
任务总计耗时                    :                 60s
任务平均流量                    :          132.60KB/s
记录写入速度                    :           9898rec/s
读出记录总数                    :              593920
读写失败总数                    :                   0rcontent.com/assets/18594841/25170306/a1464742-251c-11e7-88a7-53c674b944f1.png)

**Comment by wanglaozhe** [comment]
![_20170419162128](https://cloud.githubusercontent.com/assets/18594841/25170408/00f7efce-251d-11e7-8f4a-765d480d0ac7.png)

**Comment by wanglaozhe** [comment]
"speed": {
   "channel": 5,
   "byte": 1048576,
   "record": 10000
}
这些参数都改过并测试过，但是效率还是没有变

**Comment by ayinghaha** [comment]
你好，这个问题我也遇到了，请问你是怎么解决的。
