### ISSUE TITLE
adbmysqlwriter没有打包

### ISSUE THREAD

**Issue by xbk-hula** [alibaba/DataX#1867]
datax的下载包（https://datax-opensource.oss-cn-hangzhou.aliyuncs.com/202303/datax.tar.gz）中没有adbmysqlwriter，看了下是因为package.xml中没有包含，还请更新下

**Comment by FuYouJ** [comment]
可以试试自己本地编译。
1：打开package.xml，注释掉所有的插件。只留下自己需要的读写插件和datax核心模块[core,common,transform]，缺的也可以自己补一下。
2: pom文件也把那些注释掉。
3：运行 mvn -U clean package assembly:assembly -Dmaven.test.skip=true
