### ISSUE TITLE
oracle writer 卡死，一直刷下面的打印，帮忙看下什么问题？

### ISSUE THREAD

**Issue by williamliu111** [alibaba/DataX#1880]
oracle 11 正常reader没问题，writer卡死，一直刷下面的打印，帮忙看下什么问题？

[job-xxx] ERROR StandAloneJobContainerCommunicator - xxx
[job-xxx] INFO  StandAloneJobContainerCommunicator - Total 1 records, 4 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Transfermor Success 1 records | Transformer Error 0 records | Transformer Filter 0 records | Transformer usedTime 1.127s | Percentage 0.00%
[job-xxx] ERROR StandAloneJobContainerCommunicator - xxx
[job-xxx] INFO  StandAloneJobContainerCommunicator - Total 1 records, 4 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Transfermor Success 1 records | Transformer Error 0 records | Transformer Filter 0 records | Transformer usedTime 1.127s | Percentage 0.00%

**Comment by FuYouJ** [comment]
这种问题经常有，原因有很多。可能是数据库卡住了，也可能代码某处卡住了。重启解决

**Comment by LitteCandy0511** [comment]
需要打下 jstack看看卡在哪里了
