### ISSUE TITLE
使用hbase11xwriter时，导入数据到hbase时，是否可以增加一个参数，用于开启：当表名不存在时，自动创建该表

### ISSUE THREAD

**Issue by liuzepp** [alibaba/DataX#1888]
![image](https://github.com/alibaba/DataX/assets/68575125/ce265c56-989c-436e-8e90-5bd5078d68fa)

**Comment by LitteCandy0511** [comment]
datax 尚不具备自动建表的功能，商业版数据集成有结构迁移的功能
