### ISSUE TITLE
插件开发的流程是？

### ISSUE THREAD

**Issue by wangweihb** [alibaba/DataX#198]
我想问一下，如果自己开发datax插件的时候，步骤是不是如下（小白看了官网插件开发文档，还是不确定）：
1、将datax的源码import到idea里面去，然后在项目中新建一个自己需要开发的插件的moudle。
2、代码写完了之后，使用maven的assembly插件将新开发的moudle打包。
3、最后将自己开发的插件按照datax里面的要求拷贝到datax项目中的plugin中去

开发的流程是不是类似如上操作？？感谢大牛的解答

**Comment by TrafalgarLuo** [comment]
编译命令：
mvn clean package -U -DskipTests assembly:assembly

使用最新代码可以正常编译，注意使用 jdk >= 1.8

会得到完整的datax 二进制结果包
