### ISSUE TITLE
plugin.json文件不存在，请检查您的配置文件

### ISSUE THREAD

**Issue by dear-Alice-moon** [alibaba/DataX#20]
问题一：
`
com.alibaba.datax.common.exception.DataXException: Code:[Common-00], Describe:[您提供的配置文件存在错误信息，请检查您的作业配置 .] - 配置信息错误，您提供的配置文件[/Users/Test/Desktop/DataX-master/core/target/datax/plugin/writer/streamwriter/plugin.json]不存在. 请检查您的配置文件.
`

当我在"/Users/Test/Desktop/DataX-master/core/target/datax/plugin/writer/streamwriter"目录下，创建plugin.json信息后，又回出现如问题二所述的问题。

-----------------------------------------------------

问题二
`
经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[Framework-12], Description:[DataX插件初始化错误, 该问题通常是由于DataX安装错误引起，请联系您的运维解决 .].  - 插件加载失败,存在重复插件:/Users/Test/Desktop/DataX-master/core/target/datax/plugin/writer/streamwriter/plugin.json

`
说是存在重复插件plugin.json!!!!!

------------------------------------------------------

在这里，需要特别说明的是，/Users/Test/Desktop/DataX-master/core/target/datax/文件夹下的plugin文件夹及其里面的子文件夹、.json文件均为我个人创建。
之所以会创建这些文件，是因为在我想启动DataX项目时，报出一些错误，之后我按照提示，一步步的建立plugin文件夹及其里面的子文件夹、文件。

**Comment by gooree** [comment]
我在mac下运行示例作业报出同样的错误，请参见附件截图。
![image](https://user-images.githubusercontent.com/1580066/49776150-d85f0500-fd35-11e8-82b2-a6e65ac2ee24.png)

可不可以从配置文件或环境变量设定DATAX_HOME路径？！

**Comment by gagaboy** [comment]
> 我在mac下运行示例作业报出同样的错误，请参见附件截图。
> ![image](https://user-images.githubusercontent.com/1580066/49776150-d85f0500-fd35-11e8-82b2-a6e65ac2ee24.png)
> 
> 可不可以从配置文件或环境变量设定DATAX_HOME路径？！

这个和环境变量没关系
原因是你操作过reader目录的内容，mac系统会自动生成一个.DS_Store的系统文件，不可见
而dataX默认plugin/render都是文件夹，没有做操作系统这种层面的差异处理
所以你需要手动把错误路径下的.DS_Store文件删除即可

**Comment by ytfei** [comment]
`datax find ./ -name '.DS_Store' -print0 | xargs -0 rm -fr`

**Comment by weaksloth** [comment]
> 

我在linux下利用dolphin调度也会出现这个问题，刚下载的包，我就好奇这个目录是哪里来的..不会是打包的人没注意放在里面的吧，当然`sudo rm -rf ._*` 之后就可以使用，但是仍然觉得很离谱

**Comment by TrafalgarLuo** [comment]
已经解决，可以下载最新的，地址： https://datax-opensource.oss-cn-hangzhou.aliyuncs.com/20220530/datax.tar.gz

在 https://github.com/alibaba/DataX 也可以找到最新地址（不定期更新）。

**Comment by yzhang921** [comment]
2023年下载的DataX (DATAX-OPENSOURCE-3.0), From Alibaba !
依然有这个问题
