### ISSUE TITLE
支持对数据库分表的简化处理

### ISSUE THREAD

**Issue by gl2001wl** [alibaba/DataX#20]
可以支持表名后缀区间配置方式，例如
test_table[0~1023]
代表test_table0, test_table1....test_table1023的1024张表

**Comment by TrafalgarLuo** [comment]
这个是已经支持的特性，你配置作业的表时配置table_name[1-1024]这种即可

**Comment by swit1983** [comment]
根据什么规则分表如何配置啊

**Comment by alwayslovejava** [comment]
分库分表的读和写的json配置能给下吗？具体的分库分表规则，datax是如何配置的？

**Comment by 1092134160** [comment]
查看源码，发现如果多表情况下，writer分的任务可能不等于reader分的任务。
