### ISSUE TITLE
关于 mysqlreader 一直连接不上 mysql 8.0.X，提醒连接失败

### ISSUE THREAD

**Issue by nemosail** [alibaba/DataX#204]
根据项目首页文档，下载datax，填写mysqlreader的配置json，尝试连接 mysql 8.0 版本，一直提示连接失败，检查用户名和密码等等，其实是datax下的mysqlreader/mysqlwriter的 mysql-connector-java-5.1.34.jar 驱动版本太老了，需要更新到5.1.47+ 或者 8.0.0， 官方会重新编译或者覆盖吗？

**Comment by jiaomb** [comment]
pom文件改驱动版本号，同时mysql8.x和5.x的driver路径不一样，源码里也要修改，可以自己改了重新编译

**Comment by nemosail** [comment]
> 
> 
> pom文件改驱动版本号，同时mysql8.x和5.x的driver路径不一样，源码里也要修改，可以自己改了重新编译

需要修改pom文件 + 源码 来重新编译才行吗？

**Comment by jiaomb** [comment]
是的

**Comment by nemosail** [comment]
ok， close issue, 谢谢哈

**Comment by For-yung** [comment]
> pom文件改驱动版本号，同时mysql8.x和5.x的driver路径不一样，源码里也要修改，可以自己改了重新编译

您好，请问在哪里改drive呢

**Comment by xmsqh** [comment]
> 根据项目首页文档，下载datax，填写mysqlreader的配置json，尝试连接 mysql 8.0 版本，一直提示连接失败，检查用户名和密码等等，其实是datax下的mysqlreader/mysqlwriter的 mysql-connector-java-5.1.34.jar 驱动版本太老了，需要更新到5.1.47+ 或者 8.0.0， 官方会重新编译或者覆盖吗？

见 [另一个issue下的回答, 自己改pom.xml文件, 自己编译](https://github.com/alibaba/DataX/issues/146#issuecomment-522013519)

**Comment by xiongfei0709** [comment]
> 是的

你好？请问路径是在什么位置修改？我一直卡到这块了
