### ISSUE TITLE
mongodbreader支持的mongodb版本问题，是否支持6.0

### ISSUE THREAD

**Issue by LinkinW92** [alibaba/DataX#2045]
目前使用datax同步mongodb数据到doris，mongodb版本是v6.0.3,但执行同步任务时报错：Query failed with error code 352 and error message 'Unsupported OP_QUERY command: find. The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal' on server x.x.x.x:27017

**Comment by LinkinW92** [comment]
已经解决，修改mongodbreader下的mongo-java-driver版本到3.12.2，就可以正常读取mongo6.的数据，之前的是3.2.2版本应该是过低了。

**Comment by tianyuqingfang** [comment]
谢谢，根据你的经验，解决了我的问题

**Comment by zhangbin-hangzhou** [comment]
3.12正好不会报错，我还以为要升到4.x呢。感谢

**Comment by Cmiiii** [comment]
您好，我同样有从MongoDB迁移到Doris的需求，在确定连接没有问题后，我遇到了java.lang.NullPointerException: null的问题，请问datax不能处理空字段吗？还有一点想请假一下，您使用的是mysql的writer还是直接使用doris的writer呢？谢谢！
