### ISSUE TITLE
求帮忙解答对clickhouse进行数据迁移报错：Truncated chunk (expected size :32768;actual size : 4816)该如何解决？

### ISSUE THREAD

**Issue by yedelong** [alibaba/DataX#2047]
![Uploading ad6afda60ca64a540a0aef53d2330c8.png…]()

**Comment by yedelong** [comment]
![Uploading a019a38ccbdcc4350a4e2cbac3a6e44.png…]()

**Comment by GarveyZuo** [comment]
Have ever you solve this issue？

**Comment by GarveyZuo** [comment]
I meet the same problem

**Comment by bblueStar** [comment]
我也遇到一样的问题 后面解决了吗
