### ISSUE TITLE
配置信息错误，您提供的配置文件[datax/plugin/writer/sybasewriter/plugin.json]不存在

### ISSUE THREAD

**Issue by wjdxw** [alibaba/DataX#2127]
使用最近master 分支进行打包，运行后报这个错，如何解决？

**Comment by wjdxw** [comment]
把对应文件放在编译后的文件里就好了

**Comment by superkaja** [comment]
把对应文件放到编译后文件里也不行，报错变成”插件加载失败,存在重复插“

**Comment by wjdxw** [comment]
> 把对应文件放到编译后文件里也不行，报错变成”插件加载失败,存在重复插“

你是不是有文件重复了？

**Comment by superkaja** [comment]
> > 把对应文件放到编译后文件里也不行，报错变成”插件加载失败,存在重复插“
> 
> 你是不是有文件重复了？

mac不行很奇怪，我换到centos是可以的，谢谢
