### ISSUE TITLE
[bug]sybasewriter的打包文件 package.xml配置错误，打包出的插件没有plugin.json等文件

### ISSUE THREAD

**Issue by saligia-tju** [alibaba/DataX#2138]
<img width="1219" alt="image" src="https://github.com/alibaba/DataX/assets/59411536/da36d198-94f8-4ef0-bcff-ea78531bf24d">

<img width="925" alt="image" src="https://github.com/alibaba/DataX/assets/59411536/8c120961-8a5b-4485-b2fa-29c8363fab8c">

**Comment by FuYouJ** [comment]
我还是提一下PR吧

**Comment by saligia-tju** [comment]
https://github.com/alibaba/DataX/pull/2141#issuecomment-2185737494
