### ISSUE TITLE
是否可以实现Disruptor的RingBuffer的Channel实现

### ISSUE THREAD

**Issue by gl2001wl** [alibaba/DataX#22]
目前channel是ArrayBlockingQueue的实现，ringbuffer应该性能更佳（没有阻塞）

**Comment by TrafalgarLuo** [comment]
你说的是循环缓冲吧，缓冲区的大小是有限的，如果环形队列满了还是有阻塞的，缓冲区的大小也是不能无限大的。
之前曾经使用过2个缓冲区交替使用，buffer1、buffer2，其实和循环缓冲类似的。不过datax3废弃了，效果不明显，而且代码更复杂。
