### ISSUE TITLE
build error!

### ISSUE THREAD

**Issue by soliwolf** [alibaba/DataX#221]
[INFO] otsreader ......................................... SUCCESS [2.877s]
**_[INFO] otsstreamreader ................................... FAILURE [0.029s]_**
[INFO] plugin-unstructured-storage-util .................. SKIPPED
[INFO] txtfilereader ..................................... SKIPPED
[INFO] hdfsreader ........................................ SKIPPED

在otsstreamreader依赖com.alibaba.datax:simulator:jar:0.0.1-SNAPSHOT，但是没有下载到该dependence。

**Comment by joeyhacker** [comment]
把不需要的module在pom.xml中注释掉！

**Comment by mpatsis** [comment]
I have the same issue. Could you please give an answer in English?

**Comment by soliwolf** [comment]
Ok, if i remove the sub-module from pom, it really works. But when i want to use the otsstreamreader, what should i do?
