### ISSUE TITLE
mongodbreader相应的问题

### ISSUE THREAD

**Issue by wangsibo1993** [alibaba/DataX#23]
您好，我是位初学者，在使用datax的时候，使用mongodbreader，存放到mysql中，发现channel数大于1后，他分段查询数量貌似有点问题。就是感觉skip没有生效，第一次是1到100，第二次应该是101到200，但是感觉好像还是0开始。还有就是有没有那个模版的参数的全部介绍，channel是线程的数量么？源码我跟的时候有的地方可能没太理解，希望您能大概指点一下，万分感谢

**Comment by binaryWorld** [comment]
@wangsibo1993  每个插件都有文档说明的

**Comment by binaryWorld** [comment]
@wangsibo1993 channel是线程的数量  插件文档地址：https://github.com/alibaba/DataX/wiki/DataX-all-data-channels
