### ISSUE TITLE
无公网IP数据同步：两端都处于各自子网

### ISSUE THREAD

**Issue by hailiu08** [alibaba/DataX#23]
数据读写两端位于不同的子网，例如，从A子网的mysql同步数据集到B网的oracle。
DataX就没法使用了吧，他的reader和wirte插件都是本地JDBC远程连接，这样DataX就没法部署
我只是简单浏览了下，官方介绍，不足之处请指正。
还是可以这样做：

  数据源1---->代理1----->reader插件1---->DataX--->write插件2---->代理2----->数据源2                        
             A子网                                          公网                                 B子网

在两个同步的数据源出部署代理，采集数据到Datax相应的插件，插件在Framework管理下同样导入写入数据源

**Comment by binaryWorld** [comment]
是的 目前的模式DataX部署机器需要同时连通reader、writer数据源；
你的思路是可行的，也可以中间搞一个共享存储，中转
