### ISSUE TITLE
txtfilewriter 使用"writeMode": "truncate" 没有删除目录的文件

### ISSUE THREAD

**Issue by liuzhliang** [alibaba/DataX#252]
txtfilewriter 使用"writeMode": "truncate" 没有删除目录的文件  是我配置不对？还是怎么回事？
writer": {
                    "name": "txtfilewriter",
                    "parameter": {
                        "path": "/tmp/lzl",
                        "fileName": "account",
                        "writeMode": "truncate",
                        "fileFormat":"csv",
                        "writeMode": "append",
                        "dateFormat": "yyyy-MM-dd",
                        "fieldDelimiter": "|",
                        "nullFormat": ""

**Comment by LanstonWu** [comment]
用"writeMode": "truncate"写入,参数说明如下:
truncate，写入前清理目录下一fileName前缀的所有文件。
append，写入前不做任何处理，DataX TxtFileWriter直接使用filename写入，并保证文件名不冲突。
nonConflict，如果目录下有fileName前缀的文件，直接报错。
详细的文档在:[DataX TxtFileWriter 说明](https://github.com/alibaba/DataX/blob/master/txtfilewriter/doc/txtfilewriter.md)

**Comment by liuzhliang** [comment]
我看文档了 我用truncate模式 应该清空fileName前缀的所有文件 但实际没有

**Comment by LanstonWu** [comment]
注意确认如下问题:
1 你上面的配置有两个writeMode参数,有可能是后面的参数覆盖了前面的参数值.
2 你的datax是多少版本?
3 提供文件权限和目录权限?

**Comment by liuzhliang** [comment]
看到了 谢谢
