### ISSUE TITLE
DataX完全覆盖Sqoop功能？

### ISSUE THREAD

**Issue by kingzone** [alibaba/DataX#26]
请问，DataX能完全覆盖Sqoop1和Sqoop2的功能吗？有哪些需要注意的点呢？
DataX用于离线数据同步，有在线数据同步这种说法吗？有相应的开源产品吗？

**Comment by binaryWorld** [comment]
没有完全覆盖Sqoop功能，目前正在补全

**Comment by kingzone** [comment]
有没有详细的功能点对比呢？

**Comment by kingzone** [comment]
Sqoop从hdfs导出到mysql需要先在mysql中创建表，DataX支持自动创建表吗？

**Comment by TrafalgarLuo** [comment]
datax 不支持自动建表，目前只做数据同步。
