### ISSUE TITLE
otsstreamreader插件pom依赖编译报错

### ISSUE THREAD

**Issue by hongyi110** [alibaba/DataX#273]
插件的pom文件中对**tablestore-streamclient**的依赖版本，官方仓库中不存在**1.0.0-SNAPSHOT**，只存在release版**1.0.0**
> 
<dependency>

           <groupId>com.aliyun.openservices</groupId>
           <artifactId>tablestore-streamclient</artifactId>
           <version>1.0.0-SNAPSHOT</version>
</dependency>

**Comment by TrafalgarLuo** [comment]
编译命令：
mvn clean package -U -DskipTests assembly:assembly

使用最新代码可以正常编译，注意使用 jdk >= 1.8
