### ISSUE TITLE
本地编译报错Could not find artifact com.aliyun.openservices:tablestore-streamclient:jar:1.0.0-SNAPSHOT 

### ISSUE THREAD

**Issue by Dior222** [alibaba/DataX#29]
Could not find artifact com.aliyun.openservices:tablestore-streamclient:jar:1.0.0-SNAPSHOT

**Comment by PostgreSQL1989** [comment]
vim ${DataX_source_code_home}/otsstreamreader/pom.xml
`        <dependency>`
`            <groupId>com.aliyun.openservices</groupId>`
`            <artifactId>tablestore-streamclient</artifactId>`
`            <version>1.0.0-SNAPSHOT</version>`
`        </dependency>`
此处把`            <version>1.0.0-SNAPSHOT</version>
`改成`            <version>1.0.0</version>
`

**Comment by rongxuning** [comment]
就是这个问题

**Comment by TrafalgarLuo** [comment]
编译命令：
mvn clean package -U -DskipTests assembly:assembly

使用最新代码可以正常编译，注意使用 jdk >= 1.8
