### ISSUE TITLE
datax从oracle导数据到hdfs

### ISSUE THREAD

**Issue by ywyang2016** [alibaba/DataX#29]
问题1：将使用oraclereader将数据从oracle中读取出来，使用hdfswriter 将数据写入hdfs 但是如果oracle中的表的字段的的值是null的话hdfs写入数据就会报错 请问怎么解决

问题2：使用hdfswriter将数据写入hdfs中，和hive中的表关联，但是如果hive中的表是分区分桶的怎么办。

问题3：怎么控制datax网络传输的速度，我通过seting 里的 speed ：{byte :} 没有什么效果，可以调节每个channel的速度吗，还有一次读取的record数 默认是10000条？

**Comment by binaryWorld** [comment]
@ywyang2016  1.下个版本会修复，你也可以自己修复；2.目前写入hive是直接写文件的方式，分区桶目前不支持，你可以自己实现，并贡献；3，可以配置speed和channel数量来调节，不支持调节每个channel的速度，oraclereader fetch size默认为1024.
