### ISSUE TITLE
DataX支持Vertica吗

### ISSUE THREAD

**Issue by NicoTangTYZ** [alibaba/DataX#298]
Vertica本身支持JDBC的，但是我使用Datax的rdbmswriter插件无法访问Vertica数据库

**Comment by An-DJ** [comment]
@NicoTangTYZ 有解决方案了嘛hxd，我现在也遇到这个需求~

**Comment by NicoTangTYZ** [comment]
有的，我这里开发好插件了。&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/DataX"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月13日(星期二) 下午4:27
收件人:&nbsp;"alibaba/DataX"<DataX@noreply.github.com&gt;;
抄送:&nbsp;"醉在水中央"<136976318@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/DataX] DataX支持Vertica吗 (#298)





 
@NicoTangTYZ 有解决方案了嘛hxd，我现在也遇到这个需求~

**Comment by An-DJ** [comment]
> 有的，我这里开发好插件了。&nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alibaba/DataX" <notifications@github.com&gt;; 发送时间:&nbsp;2020年10月13日(星期二) 下午4:27 收件人:&nbsp;"alibaba/DataX"<DataX@noreply.github.com&gt;; 抄送:&nbsp;"醉在水中央"<136976318@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [alibaba/DataX] DataX支持Vertica吗 (#298) @NicoTangTYZ 有解决方案了嘛hxd，我现在也遇到这个需求~ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

@NicoTangTYZ 开源吗hxd，江湖救急 😄
