### ISSUE TITLE
datax做通用radbms数据迁移 【连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).]. No suitable driver found 错误

### ISSUE THREAD

**Issue by smallstarv5** [alibaba/DataX#299]
datax做通用radbms数据迁移，【连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).]. 
- 具体错误信息为：java.sql.SQLException: No suitable driver found for ["jdbc:dm://127.0.0.1:5236/XXX"]。

通用RDBMS 同步到 通用RDBMS 
Reader的数据库是 Available jdbcUrl，
Writer就会报上面的错误；但write的jdbc是字符串格式的---jdbcUtl :"jdbc:dm://127.0.0.1:5236/XXX"字符串格式的；
数据库换成sqlserver同步是可以的，sql server同步到达梦却不可以，同一个数据库下达梦同步到达梦可以，不同数据库的达梦同步到达梦也是报这个错

数据库本身、 配置的连接信息 没有问题 ，那报这个错又是什么问题导致的？

**Comment by nzxCoder** [comment]
你好，请我你这问题解决了吗？我也遇到写入达梦数据找不到驱动。。。

**Comment by nzxCoder** [comment]
找不到驱动

**Comment by JohnHuang93** [comment]
> 你好，请我你这问题解决了吗？我也遇到写入达梦数据找不到驱动。。。

需要将驱动jar包放在datax安装目录的libs目录下

**Comment by AlexLi1990** [comment]
> > 你好，请我你这问题解决了吗？我也遇到写入达梦数据找不到驱动。。。
> 
> 需要将驱动jar包放在datax安装目录的libs目录下
是直接将DmJdbcDriver18.jar 包放入libs下吗？ 还是需要怎么操作？

**Comment by JohnHuang93** [comment]
上次的问题解决了，您可以按照如下方式尝试解决：
1、注册驱动（datax/plugin/writer/rdbmswriter/plugin.json）
增加达梦数据库驱动（我之前是HANA，驱动为“com.sap.db.jdbc.Driver”）

{
    "name": "rdbmswriter",
    "class": "com.alibaba.datax.plugin.reader.rdbmswriter.RdbmsWriter",
    "description": "useScene: prod. mechanism: Jdbc connection using the database, execute select sql, retrieve data from the ResultSet. warn: The more you know about the database, the less problems you encounter.",
    "developer": "alibaba",
    "drivers":["dm.jdbc.driver.DmDriver", "com.sybase.jdbc3.jdbc.SybDriver", "com.edb.Driver", "com.sap.db.jdbc.Driver"]
}

2、将驱动jar包放在datax/plugin/writer/rdbmswriter/libs目录
3、将驱动jar包放在datax/lib目录（此步骤在GitHub官方文档版本中未提及）



***@***.***
 
发件人： AlexLi1990
发送时间： 2021-03-19 11:15
收件人： alibaba/DataX
抄送： JohnHuang93; Comment
主题： Re: [alibaba/DataX] datax做通用radbms数据迁移 【连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).]. No suitable driver found 错误 (#299)
你好，请我你这问题解决了吗？我也遇到写入达梦数据找不到驱动。。。
需要将驱动jar包放在datax安装目录的libs目录下
是直接将DmJdbcDriver18.jar 包放入libs下吗？ 还是需要怎么操作？

**Comment by zhchzh10000** [comment]
![image](https://user-images.githubusercontent.com/34513382/114847910-c8c5be80-9e10-11eb-8bff-c57baa0a2fdc.png)
通过这种直接写入到达梦是可以的，为何从mysql导入到达梦就出现【连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).]. No suitable driver found 错误
#299

**Comment by philipf-chen** [comment]
> datax做通用radbms数据迁移，【连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].
> 
> * 具体错误信息为：java.sql.SQLException: No suitable driver found for ["jdbc:dm://127.0.0.1:5236/XXX"]。
> 
> 通用RDBMS 同步到 通用RDBMS Reader的数据库是 Available jdbcUrl， Writer就会报上面的错误；但write的jdbc是字符串格式的---jdbcUtl :"jdbc:dm://127.0.0.1:5236/XXX"字符串格式的； 数据库换成sqlserver同步是可以的，sql server同步到达梦却不可以，同一个数据库下达梦同步到达梦可以，不同数据库的达梦同步到达梦也是报这个错
> 
> 数据库本身、 配置的连接信息 没有问题 ，那报这个错又是什么问题导致的？

rdbmswriter中jdbcUrl参数不能是List，
"jdbcUrl": ["jdbc:sap://xxxx:30215" ] -- 错误
"jdbcUrl": "jdbc:sap://xxxx:30215"  -- 正确

**Comment by TrafalgarLuo** [comment]
@keith-ch  单反馈是正确的，  reader端jdbcUrl配置为数组格式，是为了支持主备库场景

writer端jdbcUrl只有一个是因为写数据只能写主库

**Comment by liuzwei** [comment]
> 上次的问题解决了，您可以按照如下方式尝试解决： 1、注册驱动（datax/plugin/writer/rdbmswriter/plugin.json） 增加达梦数据库驱动（我之前是HANA，驱动为“com.sap.db.jdbc.Driver”） { "name": "rdbmswriter", "class": "com.alibaba.datax.plugin.reader.rdbmswriter.RdbmsWriter", "description": "useScene: prod. mechanism: Jdbc connection using the database, execute select sql, retrieve data from the ResultSet. warn: The more you know about the database, the less problems you encounter.", "developer": "alibaba", "drivers":["dm.jdbc.driver.DmDriver", "com.sybase.jdbc3.jdbc.SybDriver", "com.edb.Driver", "com.sap.db.jdbc.Driver"] } 2、将驱动jar包放在datax/plugin/writer/rdbmswriter/libs目录 3、将驱动jar包放在datax/lib目录（此步骤在GitHub官方文档版本中未提及） ***@***.*** 发件人： AlexLi1990 发送时间： 2021-03-19 11:15 收件人： alibaba/DataX 抄送： JohnHuang93; Comment 主题： Re: [alibaba/DataX] datax做通用radbms数据迁移 【连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).]. No suitable driver found 错误 (#299) 你好，请我你这问题解决了吗？我也遇到写入达梦数据找不到驱动。。。 需要将驱动jar包放在datax安装目录的libs目录下 是直接将DmJdbcDriver18.jar 包放入libs下吗？ 还是需要怎么操作？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

It's works for me !  Thanks very much !
