### ISSUE TITLE
hdfsreader不支持hdfs HA

### ISSUE THREAD

**Issue by qiulp** [alibaba/DataX#3]
在hdfs是HA情况下，defaultFS：hdfs://nameservice1  不识别

**Comment by binaryWorld** [comment]
@qiulp  目前hdfsreader是不支持hdfs HA

**Comment by qiulp** [comment]
后边有计划吗？

**Comment by qiulp** [comment]
搞定了，将xml配置文件放入resource打包即可。比较麻烦，建议将ha的几个参数注入json配置。

**Comment by binaryWorld** [comment]
@qiulp 支持ha需要排期，欢迎贡献源码

**Comment by fandaqin** [comment]
datax 写数据到hdfs目录文件中失败，我这边的hadoop版本是hadoop2.6,请问这个是什么原因，也是在HA的情况下不能操作么？

**Comment by binaryWorld** [comment]
@fandaqin  目前hdfs reader和writer都不支持HA
