### ISSUE TITLE
windows cmd中文乱码。chcp 65001没有用

### ISSUE THREAD

**Issue by doyus** [alibaba/DataX#303]
windows安装过程中cmd中文乱码。python2环境也该过cmd编码但是无效，怎么会回事呢

**Comment by doyus** [comment]
sDateType=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=fal
tchedStatements=true]
2019-03-29 23:45:32.109 [job-0] ERROR RetryUtil - Exception when cal
e, 鍗冲皢灏濊瘯鎵ц绗?娆￠噸璇?鏈閲嶈瘯璁″垝绛夊緟[2000]ms,瀹
000]ms, 寮傚父Msg:[Code:[DBUtilErrorCode-10], Description:[杩炴帴鏁版
 璇锋鏌ユ偍鐨?璐﹀彿銆佸瘑鐮併€佹暟鎹簱鍚嶇О銆両P銆丳ort鎴栬€呭
眰甯姪(娉ㄦ剰缃戠粶鐜).].  -  鍏蜂綋閿欒淇℃伅涓猴細java.sql
n: No suitable driver found for ["jdbc:mysql://127.0.0.1:3306/d_date
sDateType=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=fal
tchedStatements=true]
Traceback (most recent call last):
  File "datax.py", line 225, in <module>
    (stdout, stderr) = child_process.communicate()
  File "C:\Python26\lib\subprocess.py", line 688, in communicate
    self.wait()
  File "C:\Python26\lib\subprocess.py", line 883, in wait
    _subprocess.INFINITE)
KeyboardInterrupt

**Comment by doyus** [comment]
解决了

**Comment by zhuyandong** [comment]
怎么解决的？

**Comment by lizhichao999** [comment]
> 解决了

怎么解决的

**Comment by simuhunluo** [comment]
参考 https://blog.csdn.net/WANTAWAY314/article/details/111036461
1. cmd输入chcp 65001
2. 参考教程改注册表
