### ISSUE TITLE
qq群：547027960（datax交流群）

### ISSUE THREAD

**Issue by processdatatech** [alibaba/DataX#37]
我建了一个datax的qq群：547027960，希望使用datax的伙伴们加入，大家更方便互相讨论，分享

**Comment by processdatatech** [comment]
datax 开发人员，真切的希望你们能加入该群

**Comment by binaryWorld** [comment]
@processdatatech  不建议用qq群交流，建议直接提issue，或者  加入官方 DataX开源旺旺群 ，旺旺群号：1585662022
