### ISSUE TITLE
mysql数据同步时json字段类型中文乱码

### ISSUE THREAD

**Issue by kuantian-zhang** [alibaba/DataX#390]
mysql数据同步时，如果mysql的字段类型为json时，如果字段内存在中文，到出的字段会有中文乱码

**Comment by xxxieb** [comment]
jdbcUrl加上useUnicode=true&characterEncoding=utf-8试试

**Comment by kuantian-zhang** [comment]
> jdbcUrl加上useUnicode=true&characterEncoding=utf-8试试

不是这个问题引起的，是jdbc版本bug引起的，useUnicode=true&characterEncoding=utf-8这是代码规范，必须加的，字段类型为varchar、text是正常的，字段类型为json就乱码了

**Comment by CodeDestiny** [comment]
遇到同样的问题，尝试升级reader和writer插件中的mysql驱动，结果直接启动报错……

**Comment by CodeDestiny** [comment]
报错原来是mac系统的问题，只要升级对应插件的mysql驱动，乱码问题得到解决

**Comment by smartfly** [comment]
同样遇到这个问题，有人解决吗？

**Comment by smartfly** [comment]
> 同样遇到这个问题，有人解决吗？

已经解决，由于我使用dataX的mysql驱动版本为：mysql-connector-java-5.1.34.jar，将plugin里面mysql reader/writer驱动版本换成mysql-connector-java-5.1.40.jar, 完美解决该问题。

**Comment by qixiaobo** [comment]
https://bugs.mysql.com/file.php?id=24154&bug_id=80631

**Comment by qixiaobo** [comment]
ResultSet.getString() sometimes returned garbled data for
       columns of the JSON data type. This was because JSON data
       was binary encoded by MySQL using the utf8mb4 character
       set, but decoded by Connector/J using the ISO-8859-1
       character set. This patch fixes the decoding for JSON
       data. Thanks to Dong Song Ling for contributing to the
       fix.

**Comment by qixiaobo** [comment]
https://bugs.mysql.com/bug.php?id=80631

**Comment by qixiaobo** [comment]
upgrade to 5.1.40+ can solve this

**Comment by HuangZL-github** [comment]
datax中mysql驱动换成8.0.21，然后采集版本为5.7.35的mysql的json类型字段，为什么json类型字段还是乱码；然后把驱动改为5.1.47后，json类型就不乱码了
