### ISSUE TITLE
mongodbreader hdfswriter 不能写入

### ISSUE THREAD

**Issue by suhao123** [alibaba/DataX#40]
INFO  StandAloneJobContainerCommunicator - Total 287904 records, 18794630 bytes | Speed 38.12KB/s, 601 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.067s |  All Task WaitReaderTime 1,103.343s | Percentage 0.00% 一直打印这个信息,没有进度

**Comment by TrafalgarLuo** [comment]
WaitWriterTime 0.067s | All Task WaitReaderTime 1,103.343s  说明是你的数据源头mongodb读的慢，排查下mongodb方面的性能、网络链路问题吧

**Comment by suhao123** [comment]
看了看抽数的实现方式，有sort，skip效率都不高。对于我们来说sort应该没有必要。我的表大概有7千万的数据量，第一次我希望抽取全量。小表就没问题。
