### ISSUE TITLE
MongoDB 读取数据写入hdfs，丢失字段

### ISSUE THREAD

**Issue by liujie-yt** [alibaba/DataX#41]
MongoDB 的列是参差不齐的，使用mongodbReader读取，写到hdfs上，当碰到不存在的字段就被丢掉了，也没有使用分隔符占位，导致写出的数据impala读取时会字段不全、列对应不上

**Comment by xjr7670** [comment]
老哥，请教下，你这个问题是怎么解决的呢？
我现在也遇到同样的问题了。下载源码编译时总遇到各种依赖找不到的问题，不知道要怎么搞了
