### ISSUE TITLE
编译的时候报错

### ISSUE THREAD

**Issue by hzhili** [alibaba/DataX#423]
Execution make-assembly of goal org.apache.maven.plugins:maven-assembly-plugin:2.2-beta-5:attached failed: For artifact {null:null:null:jar}: The groupId cannot be empty.

用源码编译打包的时候提示这个错误,检查了下pom文件和package文件都没有错误

**Comment by TrafalgarLuo** [comment]
编译命令：
mvn clean package -U -DskipTests assembly:assembly

使用最新代码可以正常编译，注意使用 jdk >= 1.8
