### ISSUE TITLE
嵌入式jar包

### ISSUE THREAD

**Issue by jamee-wang** [alibaba/DataX#426]
可否deploy编译好的 jar 包到 maven 中央仓库，这样我们可以通过代码集成，我想把他做成一个定时任务，而不是一个工具运行一次就结束了

**Comment by TrafalgarLuo** [comment]
datax 打包后是一个可执行程序，建议以子进程的方式调用 datax程序，父进程可以感知子进程的状态，子进程的日志也可以重定向到其他需要的IO流。

datax 本身是java进程， 会有多个依赖并且需要cpu memory资源， 如果datax和父进程在同一个jvm空间，可能会对父jvm进程有干扰（资源，类加载等）
