### ISSUE TITLE
请问有人知道datax mongodbreader里面的query查询语句应该写成什么格式呢？

### ISSUE THREAD

**Issue by NewStartMe** [alibaba/DataX#445]

**Comment by richaredFS** [comment]
类似于这样："query":"{created_at:{ $gte: '''${begin_time}''', $lte: '''${end_time}''' }}",
begintime和endtime是我定义在外面的变量，亲测有效

**Comment by QiYuanGit** [comment]
"column": [
              {
                                "index":0,
                "name": "_id",
                "type": "string"
              },
              {
                                "index":1,
                "name": "uid",
                "type": "String"
              },
              {
                                "index":2,
                "name": "taskCode",
                "type": "string"
              },
                          {
                                "index":3,
                "name": "taskName",
                "type": "string"
              },
              {
                                "index":4,
                "name": "rewardType",
                "type": "Int"
              },
              {
        "index":5,
                "name": "rewardContentId",
                "type": "string"
              },
              {
        "index":6,
                "name": "terminal",
                "type": "Int"
              },
              {
        "index":7,
                "name": "desc",
                "type": "string"
              },
              {
        "index":8,
                "name": "createTime",
                "type": "Date"
              }
            ],
          "query":"{createTime:{ $gte: ${t1}, $lte: ${t2} }}"
          }

你好，我模仿了你的写法，但是一条数据都没有查出来，mogodb是ISOdate格式，${t1}取得的值是1622995200101，我t1的变量这样直接用时间戳可以吗，现在一条数据也没有查到...求助

**Comment by QiYuanGit** [comment]
> 类似于这样："query":"{created_at:{ $gte: '''${begin_time}''', $lte: '''${end_time}''' }}",
> begintime和endtime是我定义在外面的变量，亲测有效

**Comment by haha541514** [comment]
> 

这个变量怎么在外面定义的？ 
我需要做一个增量同步，
mongo语句是这样的
db.getCollection('site_resource_learn_time_behavior').aggregate([{$match:{$expr:{$gt:["$createTime",{$subtract:[ "$$NOW", 86400000] }]}}}])
这个query怎么填？

**Comment by haha541514** [comment]
> > 类似于这样："query":"{created_at:{ $gte: '''${begin_time}''', $lte: '''${end_time}''' }}",
> > begintime和endtime是我定义在外面的变量，亲测有效



> > 类似于这样："query":"{created_at:{ $gte: '''${begin_time}''', $lte: '''${end_time}''' }}",
> > begintime和endtime是我定义在外面的变量，亲测有效
这个变量怎么在外面定义的？
我需要做一个增量同步，
mongo语句是这样的
db.getCollection('site_resource_learn_time_behavior').aggregate([{$match:{$expr:{$gt:["$createTime",{$subtract:[ "$$NOW", 86400000] }]}}}])
这个query怎么填？

**Comment by dingxiaobo** [comment]
query查询时间样例： 
```
"query":"{'operationTime':{'$gte':ISODate('2022-10-22T00:00:00.424+0800')}}"
```
