### ISSUE TITLE
oracle导入es指定id问题

### ISSUE THREAD

**Issue by xukanwen00** [alibaba/DataX#450]
我指定了id。不起作用。另外怎么让id指定为表中的某一列              
  "writer": {
                    "name": "elasticsearchwriter",
                    "parameter": {
                      "endpoint":"http://47.110.127.70:9200",
                      "accessId": "123123",
                      "accessKey": "21323",
                      "index": "esiktest", 
                      "type": "ik",  
					  "id": "aaa",
                      "cleanup": false,  
                      "discovery":false, 
					  "column": [  
                          {
                            "name": "name",  
                            "type": "text",
							"analyzer": "ik_max_word"
                          }
						  ]
                    }
                }

**Comment by lpong** [comment]
这个怎么解决的呢n
