### ISSUE TITLE
rdbmsreader hiveserver2 No suitable driver found

### ISSUE THREAD

**Issue by lordk911** [alibaba/DataX#454]
I want to use rdbmsreader to connect to hiveserver2 , I've add the jdbc driver jars to the plugin lib and regist 'org.apache.hive.jdbc.HiveDriver' to  plugin.json , but when I run a job the DBUtil when run to line : Class.forName(dataBaseType.getDriverClassName());  throw Exception ：
java.sql.SQLException: No suitable driver found for jdbc:hive2:．．

**Comment by lordk911** [comment]
I've found the problem . The Driver version I used can't be registed by DriverManager automatically , after change to another version driver , all works fine.

**Comment by liushuainudt** [comment]
how to change the version driver?
