### ISSUE TITLE
HdfsHelper.java  line  449

### ISSUE THREAD

**Issue by yakirChen** [alibaba/DataX#46]
```java
String rowData = column.getRawData().toString();
if (null != column.getRawData() && StringUtils.isNotBlank(rowData)) {
```
这里做了判断 ` null != column.getRawData()` 是不是没什么意义 ，

>  String rowData = column.getRawData().toString();

这个时候已经拿过一次了 是null 的时候 toString() 就抛异常了

**Comment by binaryWorld** [comment]
是的，这bug 已经fix 下个版本会一起推上来
