### ISSUE TITLE
mysql datetime类型字段  写到 Hive 中对应的timestamp字段，数据不对 

### ISSUE THREAD

**Issue by gcnote** [alibaba/DataX#462]
mysql datetime类型字段  写到 Hive 中对应的timestamp字段，数据不对 

使用场景：mysql reader, hivewriter
mysql datetime类型字段  写到 hive 中,  hive中对应的字段分别使用了string, date, timestamp 3种类型测试，发现数据同步 都不对
mysql 原数据：              2019-05-05 14:29:03  (datetime)

同步后hive中对应的值： 2019-05-06 06:29:03 （string）
                                        2019-05-05 04:00:00  (date)
                                        2019-05-05 13:29:03 (timestamp)

**Comment by IMYR666** [comment]
我也遇到这个问题，请问你解决了吗
