### ISSUE TITLE
datax 写hdfs与写hive的区别？

### ISSUE THREAD

**Issue by wwbbcjeyc** [alibaba/DataX#465]
为啥我看datax写hdfs和写hive的配置一模一样哈。我按hdfswriter 写hive的数据不能被hive直接读取

**Comment by jasonmba** [comment]
不能被读取是因为你没有location进hive吧，对datax来说，hive和hdfs确实是一样的

**Comment by wwbbcjeyc** [comment]
嗯嗯，感谢。这两个都是导入数据到hdfs。hive的话还需要msck repair






在 2019-10-16 17:47:02，"jasonmba" <notifications@github.com> 写道：


不能被读取是因为你没有location进hive吧，对datax来说，hive和hdfs确实是一样的
