### ISSUE TITLE
咨询下，请问支持mysql入库到hive么

### ISSUE THREAD

**Issue by boboChina** [alibaba/DataX#47]
大体思路如下  canal解析binlog 解析成 datax支持的类型 然后datax入库hive

**Comment by boboChina** [comment]
感觉 cannl otter datax有一些概念或者功能重复了 - - 求阿里内部大神整合一下  同时研究三个项目好心塞

**Comment by miaoever** [comment]
@boboChina  dataX 有 mydql reader 插件，不需要再解析 mysql binlong。三者使用场景不一样。
