### ISSUE TITLE
DataX数据导入至Kudu

### ISSUE THREAD

**Issue by wangsvip** [alibaba/DataX#474]
由于Sqoop只支持数据导入至HDFS，要使用Kudu还需用Impala将数据导入至Kudu,这个多增加一个流程，迫切的需要DataX能将关系数据库数据导入到Kudu,能实现这个功能将是一大壮举！

**Comment by V-I-C-T-O-R** [comment]
@wangsvip Hi，自用修改了一个Datax的[Kudu写插件](https://github.com/V-I-C-T-O-R/datax-kudu)，有需要你可以暂时先用一下(注意修改参数)，等官方正式发布Kudu插件之后再用官方的。

**Comment by wangsvip** [comment]
很是感谢！！




------------------ 原始邮件 ------------------
发件人: "Victor"<notifications@github.com>;
发送时间: 2019年10月15日(星期二) 上午9:37
收件人: "alibaba/DataX"<DataX@noreply.github.com>;
抄送: "I am not me"<1040492846@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [alibaba/DataX] DataX数据导入至Kudu (#474)




@wangsvip Hi，自用修改了一个Datax的Kudu写插件，有需要你可以暂时先用一下(注意修改参数)，等官方正式发布Kudu插件之后再用官方的。

**Comment by V-I-C-T-O-R** [comment]
@wangsvip 被你发现了-_-，希望对你有用
