### ISSUE TITLE
maven编译不通过 有大佬帮忙看下是什么原因吗?

### ISSUE THREAD

**Issue by yanzhi008** [alibaba/DataX#49]
Downloading: http://maven.aliyun.com/nexus/content/groups/public/eigenbase/eigenbase-properties/1.1.4/eigenbase-properties-1.1.4.pom
[WARNING] The POM for eigenbase:eigenbase-properties:jar:1.1.4 is missing, no dependency information available
Downloading: http://maven.aliyun.com/nexus/content/groups/public/org/pentaho/pentaho-aggdesigner-algorithm/5.1.5-jhyde/pentaho-aggdesigner-algorithm-5.1.5-jhyde.pom
[WARNING] The POM for org.pentaho:pentaho-aggdesigner-algorithm:jar:5.1.5-jhyde is missing, no dependency information available
Downloading: http://maven.aliyun.com/nexus/content/groups/public/eigenbase/eigenbase-properties/1.1.4/eigenbase-properties-1.1.4.jar
Downloading: http://maven.aliyun.com/nexus/content/groups/public/org/pentaho/pentaho-aggdesigner-algorithm/5.1.5-jhyde/pentaho-aggdesigner-algorithm-5.1.5-jhyde.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.276 s
[INFO] Finished at: 2018-03-27T16:59:14+08:00
[INFO] Final Memory: 14M/240M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project hdfsreader: Could not resolve dependencies for project com.alibaba.datax:hdfsreader:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: org.pentaho:pentaho-aggdesigner-algorithm:jar:5.1.5-jhyde, eigenbase:eigenbase-properties:jar:1.1.4: Failure to find org.pentaho:pentaho-aggdesigner-algorithm:jar:5.1.5-jhyde in http://repo1.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of maven-net-cn has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

Process finished with exit code 1

**Comment by yitiaoxian** [comment]
咦，org.pentaho:pentaho-aggdesigner-algorithm:jar:5.1.5-jhyde, eigenbase:eigenbase-properties:jar:1.1.4: Failure to find org.pentaho:pentaho-aggdesigner-algorithm:jar:5.1.5-jhyde 这几个依赖哪用了？

**Comment by yanzhi008** [comment]
hdfsreader插件中
orderEntry type="library" name="Maven: org.pentaho:pentaho-aggdesigner-algorithm:5.1.5-jhyde" level="project"

**Comment by yanzhi008** [comment]
已经成功编译了. 但是现在启动报错了
[root@master bin]# python datax.py ../job/testjob.json 

DataX (DATAX-OPENSOURCE-3.0), From Alibaba !
Copyright (C) 2010-2017, Alibaba Group. All Rights Reserved.


2018-03-27 03:21:35.675 [main] WARN  ConfigParser - 插件[ftpreader,ftpWriter]加载失败，1s后重试... Exception:Code:[Framework-12], Description:[DataX插件初始化错误, 该问题通常是由于DataX安装错误引起，请联系您的运维解决 .].  - 插件加载失败，未完成指定插件加载:[ftpWriter, ftpreader] 
2018-03-27 03:21:36.704 [main] ERROR Engine - 

经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[Framework-12], Description:[DataX插件初始化错误, 该问题通常是由于DataX安装错误引起，请联系您的运维解决 .].  - 插件加载失败，未完成指定插件加载:[ftpWriter, ftpreader]
        at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26)
        at com.alibaba.datax.core.util.ConfigParser.parsePluginConfig(ConfigParser.java:142)
        at com.alibaba.datax.core.util.ConfigParser.parse(ConfigParser.java:63)
        at com.alibaba.datax.core.Engine.entry(Engine.java:137)
        at com.alibaba.datax.core.Engine.main(Engine.java:204)

**Comment by nextleave** [comment]
怎么编译成功的？那两个jar包一直下不下来。

**Comment by yanzhi008** [comment]
我手动配置了3个源

        <mirror>
            <id>alimaven</id>
            <mirrorOf>central</mirrorOf>
            <name>aliyun maven</name>
            <url>http://maven.aliyun.com/nexus/content/repositories/central/</url>
        </mirror>
    
        
        <mirror>
            <id>repo1</id>
            <mirrorOf>central</mirrorOf>
            <name>Human Readable Name for this Mirror.</name>
            <url>http://repo1.maven.org/maven2/</url>
        </mirror>
    
        
        <mirror>
            <id>repo2</id>
            <mirrorOf>central</mirrorOf>
            <name>Human Readable Name for this Mirror.</name>
            <url>http://repo2.maven.org/maven2/</url>
        </mirror>

**Comment by blkfhusky** [comment]
@yanzhi008 请问具体是哪里不一样，方便描述下吗

**Comment by yanzhi008** [comment]
检查你使用的插件目录下的模版json文件, 里面配置的插件name要和你自己定义使用的json文件插件name保持一致就可以了

**Comment by belary** [comment]
感谢，遇到了同样的问题

**Comment by zhangnew** [comment]
把 `~/.m2/settings.xml` 里面的 `mirror` 都注释掉就好了

**Comment by chenhen715** [comment]
我手动加了：    <mirror>
        <id>alimaven</id>
        <mirrorOf>central</mirrorOf>
        <name>aliyun maven</name>
        <url>http://maven.aliyun.com/nexus/content/repositories/central/</url>
    </mirror>

    
    <mirror>
        <id>repo1</id>
        <mirrorOf>central</mirrorOf>
        <name>Human Readable Name for this Mirror.</name>
        <url>http://repo1.maven.org/maven2/</url>
    </mirror>

    
    <mirror>
        <id>repo2</id>
        <mirrorOf>central</mirrorOf>
        <name>Human Readable Name for this Mirror.</name>
        <url>http://repo2.maven.org/maven2/</url>
    </mirror>

可还是无法通过编译

**Comment by chenhen715** [comment]
我手动加了：
 <mirror>
        <id>alimaven</id>
        <mirrorOf>central</mirrorOf>
        <name>aliyun maven</name>
        <url>http://maven.aliyun.com/nexus/content/repositories/central/</url>
    </mirror>

    
    <mirror>
        <id>repo1</id>
        <mirrorOf>central</mirrorOf>
        <name>Human Readable Name for this Mirror.</name>
        <url>http://repo1.maven.org/maven2/</url>
    </mirror>

    
    <mirror>
        <id>repo2</id>
        <mirrorOf>central</mirrorOf>
        <name>Human Readable Name for this Mirror.</name>
        <url>http://repo2.maven.org/maven2/</url>
    </mirror>
可还是无法通过编译

**Comment by chenhen715** [comment]
我手动配置了以上提供的3个源，可还是无法通过编译

**Comment by freezhan** [comment]
无法通过 +1 只是加了个依赖

```xml
        <dependency>
            <groupId>org.apache.hive</groupId>
            <artifactId>hive-exec</artifactId>
            <version>1.1.0</version>
            <scope>compile</scope>
        </dependency>
```

奇怪的是升级 hive 依赖随意编译。

**Comment by yinjianjie** [comment]
> 问题已经解决. 原因是 git下来的代码和说明文档所描述的插件名称大小写不一样 导致无法加载插件

具体在哪个文件里呢

**Comment by numbernumberone** [comment]
解决了吗？

**Comment by lwl888** [comment]
添加三个仓库源，还是无法通过编译

**Comment by TrafalgarLuo** [comment]
编译命令：
mvn clean package -U -DskipTests assembly:assembly

使用最新代码可以正常编译，注意使用 jdk >= 1.8

**Comment by BinTaoMa** [comment]
> 编译命令： mvn clean package -U -DskipTests assembly:assembly
> 
> 使用最新代码可以正常编译，注意使用 jdk >= 1.8
还是无法编译
![image](https://github.com/alibaba/DataX/assets/91652521/949312bb-7b7b-462c-8ac9-645159ea681b)
