### ISSUE TITLE
DataX把数据从一个mysql数据表导入到另一个mysql数据表报错

### ISSUE THREAD

**Issue by zyxzyxzyx** [alibaba/DataX#500]
如题，报错：Description:[数据库用户名或者密码错误，请检查填写的账号密码或者联系DBA确认账号和密码是否正确].  - 该数据库用户名为：root 具体错误信息为：java.sql.SQLException: Access denied for user 'root'@'localhost'.
本人已确认用户名和密码没有错误，但还是会报这个错误，请大神们指点！

**Comment by Tu-maimes** [comment]
远程访问权限


来自 魅族 PRO 7

-------- 原始邮件 --------
发件人：Zhang Yexing <notifications@github.com>
时间：2019年11月9日 22:35
收件人：alibaba/DataX <DataX@noreply.github.com>
抄送：Subscribed <subscribed@noreply.github.com>
主题：[alibaba/DataX] DataX把数据从一个mysql数据表导入到另一个mysql数据表报错 (#500)

**Comment by zyxzyxzyx** [comment]
> 远程访问权限 来自 魅族 PRO 7
> […](#)
> -------- 原始邮件 -------- 发件人：Zhang Yexing <notifications@github.com> 时间：2019年11月9日 22:35 收件人：alibaba/DataX <DataX@noreply.github.com> 抄送：Subscribed <subscribed@noreply.github.com> 主题：[alibaba/DataX] DataX把数据从一个mysql数据表导入到另一个mysql数据表报错 (#500)
> 如题，报错：Description:[数据库用户名或者密码错误，请检查填写的账号密码或者联系DBA确认账号和密码是否正确]. - 该数据库用户名为：root 具体错误信息为：java.sql.SQLException: Access denied for user 'root'@'localhost'. 本人已确认用户名和密码没有错误，但还是会报这个错误，请大神们指点！ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.￼ [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "#500?email_source=notifications\u0026email_token=AHNPXWHHFDEOTAPK7GXYL63QS3DC7A5CNFSM4JLHMXW2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HYFLEGQ", "url": "#500?email_source=notifications\u0026email_token=AHNPXWHHFDEOTAPK7GXYL63QS3DC7A5CNFSM4JLHMXW2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HYFLEGQ", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

并不是远程访问权限的问题，不过已经解决了，还是很感谢你的回复。

**Comment by jiangleifree** [comment]
老哥,我也是这个问题, 你是怎么解决的那

**Comment by eijintao** [comment]
我现在遇到了这个问题，一直解决不了，具体时怎么解决的啊？

**Comment by penglin358** [comment]
请检查访问权限

**Comment by eijintao** [comment]
> 请检查访问权限

谢谢您的回复！我昨晚搞了很长时间，用排除法慢慢缩小范围后，今天早上，终于知道了原因。在此背景下跟各位说下：我是mysql到hive的。系统是windows系统，mysql是5.6的版本。读取mysql连接时，一直报这个错误。我仔细检查了我的用户名和密码，还有权限后，确定没有任何问题，百分之一百的没有任何问题。但是客观事实确实有问题后，在最后实在没有办法的情况下，我把json中的mysqlreader中的密码由密文改成明文后，直接可以了。。。。。这种情况简直让我大跌眼镜，因为datax之前一直跑在客户的测试环境和生产环境中，read模块的密码都是密文的，一点事情也没有。而且，我还把客户测试环境的datax拿出来，在自己的linux中运行，也是一点问题都没有，偏偏，在当前版本中（2023年7月拉取master分支后），居然密文不行，必须要明文！！！！。
