### ISSUE TITLE
用rdbmsreader抽取mysql库，报错内存不足

### ISSUE THREAD

**Issue by hsq1233211234567** [alibaba/DataX#510]
我调整datax.py的内存为4G，在抽取一个400w数据量的表时候出现
java.lang.OutOfMemoryError: GC overhead limit exceeded的错误
难道datax读取时候是一次性把所有数据读到内存？

**Comment by hsq1233211234567** [comment]
?useCursorFetch=true&defaultFetchSize=512
在URL上加上限制

**Comment by coder-shihua** [comment]
这个url是加在哪里的
