### ISSUE TITLE
设计思路的探讨——datax整体设计非常优秀，不过有一点不是很明白，为什么没有对配置进行对像化？

### ISSUE THREAD

**Issue by jebiao** [alibaba/DataX#512]
**datax**的设计非常简洁以及高效的，可我阅读代码，有一点不是很明白，为什么不把配置属性进行对象化处理呢，而是使用一个全局的**Configuration**去装载这些配置呢？

1. 对象化处理的好处。

- 有利于代码阅读者，方便理解、维护；
- 方便第三方直接将datax作为插件进行调用；
- 规范Configuration。

so, 这个**Configuration**肯定会有更深层次的考虑，请赐教。

**Comment by wen-hemin** [comment]
我理解这个json格式不太适合对象化，因为json结构的粒度都比较小。我做调度系统对接开发时，也考虑过对象化，那样会有N个对象嵌套，不利于开发和阅读，最后直接JSONObject处理了

**Comment by jebiao** [comment]
> 我理解这个json格式不太适合对象化，因为json结构的粒度都比较小。我做调度系统对接开发时，也考虑过对象化，那样会有N个对象嵌套，不利于开发和阅读，最后直接JSONObject处理了

**Comment by jebiao** [comment]
理解，确实，编码都在各种合适与不合适之间的权衡，👍。感谢答复
