### ISSUE TITLE
《DataX插件开发宝典》有勘误，“功过”应为“通过”

### ISSUE THREAD

**Issue by waylau** [alibaba/DataX#53]
https://github.com/alibaba/DataX/wiki/DataX%E6%8F%92%E4%BB%B6%E5%BC%80%E5%8F%91%E5%AE%9D%E5%85%B8

《DataX插件开发宝典》有勘误，在“如何处理脏数据”一节“在Reader.Task和Writer.Task中，功过AbstractTaskPlugin.getPluginCollector()可以拿到一个TaskPluginCollector”中，“功过”应改为“通过”

**Comment by binaryWorld** [comment]
是的，谢谢
