### ISSUE TITLE
mysqlreader不支持mysql8.x版本吗

### ISSUE THREAD

**Issue by jiangleifree** [alibaba/DataX#556]
配置好任务之后,连接不上数据库
![image](https://user-images.githubusercontent.com/35941598/71444413-fbdfcc80-274b-11ea-816a-986b88183631.png)
![image](https://user-images.githubusercontent.com/35941598/71444425-0f8b3300-274c-11ea-85fc-495fed791ff5.png)

**Comment by dingxiaobo** [comment]
DataX 现已支持，欢迎使用新版本
