### ISSUE TITLE
使用DataX 从MySQL向Elasticsearch同步数据的时候映射错误

### ISSUE THREAD

**Issue by Natsu-Lee** [alibaba/DataX#581]
com.alibaba.datax.common.exception.DataXException: Code:[ESWriter-03], Description:[mappings错误.].  - java.lang.IllegalArgumentException: Illegal character in scheme name at index 0: 192.168.198.128:9200/atest

经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[ESWriter-03], Description:[mappings错误.].  - java.lang.IllegalArgumentException: Illegal character in scheme name at index 0: 192.168.198.128:9200/atest

表中只有一个varchar的testid 

配置文件如下
{
	"job": {
		"setting": {
			"speed": {
				"channel": 3
			},
			"errorLimit": {
				"record": 0,
				"percentage": 0.02
			}
		},
		"content": [
			{
				"reader": {
					"name": "mysqlreader",
					"parameter": {
						"username": "root",
						"password": "66778899",
						"column": [
							"testid"
						],
						"connection": [
							{
								"table": [
									"testa"
								],
								"jdbcUrl": [
									"jdbc:mysql://192.168.198.128:3306/test"
								]
							}
						]
					}
				},
				"writer": {
					"name": "elasticsearchwriter",
					"parameter": {
						"endpoint": "192.168.198.128:9200",
						"index": "atest",
						"type": "default",
						"cleanup": true,
						"accessId": "test",
						"accessKey": "test",
						"settings": {
							"index": {
								"number_of_shards": 5,
								"number_of_replicas": 1
							}
						},
						"discovery": false,
						"batchSize": 1000,
						"splitter": ",",
						"column": [
							{
								"name": "testid",
								"type": "ip"
							}
						]
					}
				}
			}
		]
	}
}

**Comment by RaiToKU** [comment]
加上http试试 提示的是非法字符
