### ISSUE TITLE
一个job怎么实现多个表同步？

### ISSUE THREAD

**Issue by iweisi** [alibaba/DataX#59]
同一个job，怎么配置实现多个表，不同字段进行同步呢？

**Comment by ztommyc** [comment]
解决了吗？我也想知道答案

**Comment by lishu2006ll** [comment]
同上

**Comment by zhujingling** [comment]
问题关闭了，是解决了嘛？

**Comment by iweisi** [comment]
> 问题关闭了，是解决了嘛？

是不想解决了，我直接一个job一个表

**Comment by Valdanitooooo** [comment]
持续关注:laughing:

**Comment by tianqing108** [comment]
还没解决吗？

**Comment by iweisi** [comment]
> 还没解决吗？

再写多几个job

**Comment by tianqing108** [comment]
只能写多个，单个job不支持多表发自我的荣耀手机-------- 原始邮件 --------发件人： "465272694@qq.com" <notifications@github.com>日期： 2020年12月16日周三 上午10:34收件人： alibaba/DataX <DataX@noreply.github.com>抄送： tianqing108 <tianqing108@126.com>, Comment <comment@noreply.github.com>主    题： Re: [alibaba/DataX] 一个job怎么实现多个表同步？ (#59)



还没解决吗？



再写多几个job

**Comment by meifu2027** [comment]
如果一个job只能配一张表的话，那是不是只有一个Task和一个task group，channel配置再多也只能用到1个，可以这么理解吗？

**Comment by tianqing108** [comment]
是的，datax只适合做简单的数据同步，如果涉及到数据转换、合并这些，还是自行开发一个脚本靠谱点













在 2021-04-01 09:02:07，"meifu" ***@***.***> 写道：

如果一个job只能配一张表的话，那是不是只有一个Task和一个task group，channel配置再多也只能用到1个，可以这么理解吗？

**Comment by guziqiu** [comment]
看着里面https://github.com/alibaba/DataX/blob/master/dataxPluginDev.md

类似通用：遵守同一类型的插件的习惯，比如关系型数据库的connection参数都是如下结构：
{
  "connection": [
    {
      "table": [
        "table_1",
        "table_2"
      ],
      "jdbcUrl": [
        "jdbc:mysql://127.0.0.1:3306/database_1",
        "jdbc:mysql://127.0.0.2:3306/database_1_slave"
      ]
    },
    {
      "table": [
        "table_3",
        "table_4"
      ],
      "jdbcUrl": [
        "jdbc:mysql://127.0.0.3:3306/database_2",
        "jdbc:mysql://127.0.0.4:3306/database_2_slave"
      ]
    }
  ]
}

我用的OceanBase这样配置是可以用的
"content": [
            {
                "reader": {
                    "name": "oceanbasev10reader",
                    "parameter": {
                        "where": "",
                        "readBatchSize": 50,
                        "column":[
                            "*"
                        ],
                        "connection": [
                            {
                                "jdbcUrl": [
                                    "jdbc:oceanbase://ip:2881/SYS"
                                ],
                                "table": [
                                    "OB.T1",
                                    "OB.T2"
                                ]
                            }
                        ],
                        "username": "SYS@oraclet",
                        "password": "111"
                    }
                },

**Comment by MUMU-FOREVER** [comment]
https://github.com/MUMU-FOREVER/DataX/releases
