### ISSUE TITLE
HdfsWriter不支持truncate写入模式吗

### ISSUE THREAD

**Issue by smilly2** [alibaba/DataX#590]
我查看了源代码发现truncate模式被注释了，请问这种模式是有什么问题吗
/**
                 if ("truncate".equals(writeMode) && isExistFile ) {
                 LOG.info(String.format("由于您配置了writeMode truncate, 开始清理 [%s] 下面以 [%s] 开头的内容",
                 path, fileName));
                 hdfsHelper.deleteFiles(existFilePaths);
                 } else
                 */

**Comment by zhongjiajie** [comment]
@smilly2 你可以参考一下我的fork  https://github.com/zhongjiajie/DataX/pull/4
truncate 只会删除以特定符号开头的文件，而不是全部的文件，所以我加了两个操作（truncate和delete）
* `truncate`->删除文件路径下全部的文件
* `delete`->删除文件路径下制定开头的文件

**Comment by smilly2** [comment]
我把源代码注释的那一段取消了，增加了truncate模式，目前运行没有问题
