### ISSUE TITLE
导入到greenplum的时候，如何关闭对gp_max_csv_line_length参数的设置

### ISSUE THREAD

**Issue by javaanddonet** [alibaba/DataX#592]
现在从mysql导入数据到greenplum中，GP的版本是6.1.0，在5.11版本之前的GP中是有这个参数的。datax可以正常导入数据到gp中。现在升级了gp的版本到6.1.0，在新版本的gp去废除了这个参数。在datax中如何关闭对这个参数的设置呢？

datax执行的时候，错误信息如下：
DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-06], Description:[执行数据库 Sql 失败, 请检查您的配置的 column/table/where/querySql或者向 DBA 寻求帮助.].  - 执行的SQL为: set gp_max_csv_line_length = 4194304 具体错误信息为：org.postgresql.util.PSQLException: ERROR: unrecognized configuration parameter "gp_max_csv_line_length"

**Comment by lianjie1229** [comment]
gpdbwriter 是HashDataInc提供的插件，方法如下：
1、下载源码，注释掉那段代码，重新编译下
2、如果不行，我有现成编译好的，可以发给你

**Comment by javaanddonet** [comment]
@lianjie1229
感谢，根据你的提示，我修改了源码，重新编译了一版。问题解决了，感谢～

**Comment by cxin-william** [comment]
@javaanddonet 你好 可以分享一下支持greenplum的datax包吗 学习一下

**Comment by daixuej** [comment]
> gpdbwriter 是HashDataInc提供的插件，方法如下： 1、下载源码，注释掉那段代码，重新编译下 2、如果不行，我有现成编译好的，可以发给你

可以发我一下吗？我这边也报相同错误，34994293@qq.com

**Comment by daixuej** [comment]
> @lianjie1229 感谢，根据你的提示，我修改了源码，重新编译了一版。问题解决了，感谢～

您编译好的可以发我一份吗？34994293@qqcom  谢谢

**Comment by daixuej** [comment]
> gpdbwriter 是HashDataInc提供的插件，方法如下： 1、下载源码，注释掉那段代码，重新编译下 2、如果不行，我有现成编译好的，可以发给你

@lianjie1229 能否发我一封 谢谢

**Comment by MaxCADog** [comment]
删掉gp_max_csv_line_length的代码后，重新编译engine的jar包，更换jar包后，单通道速度由原来的每秒79条数据增加到每秒10000条数据，这个抽取速度，我这目前是够用了。

**Comment by Dannila** [comment]
> @lianjie1229 谢谢，根据你的提示，我修改了源，重新编译了一个版本。问题解决了，～
你好，你编译好的greenplum的datax包可以给我发一份吗，非常感谢！邮箱：cxy1122bl@163.com
我自己也尝试编译过，虽然编译的过程没有报错，但是无法使用，就连mysql都无法读取。。。

**Comment by Dannila** [comment]
> @lianjie1229 感谢，根据你的提示，我修改了源码，重新编译了一版。问题解决了，感谢～

我好，你编译好的greenplum的datax包可以给发一份吗，非常感谢！邮箱：[cxy1122bl@163 .com](mailto:cxy1122bl@163.com)
我自己也试过编译过，虽然编译的过程没有报错，但是无法使用，就连mysql都无法读取。。。

**Comment by ixiekun** [comment]
> 

你好，是否可以发我一份，ixiekun@163.com。目前从HashDataInc下载下来的源码无法编译

**Comment by ixiekun** [comment]
> 

是否可以发一份datax的安装包，感谢。ixiekun@163.com

**Comment by MaxCADog** [comment]
链接：https://pan.baidu.com/s/1EZ8epma-HSszTzG6SFpuLA&nbsp;
提取码：nf4f&nbsp;
--来自百度网盘超级会员V7的分享





ChangLe
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/DataX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月3日(星期一) 晚上7:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/DataX] 导入到greenplum的时候，如何关闭对gp_max_csv_line_length参数的设置 (#592)





   
***@***.***

**Comment by MaxCADog** [comment]
我没有对datax代码进行改动，只是替换了postgresql的数据库驱动


ChangLe
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/DataX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月3日(星期一) 晚上7:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/DataX] 导入到greenplum的时候，如何关闭对gp_max_csv_line_length参数的设置 (#592)





   
***@***.***

**Comment by wanghy8166** [comment]
@MaxCADog  ，百度链接已失效，能否说一下你是用具体哪个版本的Greenplum驱动来替换postgresql的数据库驱动?

**Comment by MaxCADog** [comment]
链接：https://pan.baidu.com/s/1oI7BlZ-wEqwOytLiWSnKyw&nbsp;
提取码：qwfw





ChangLe
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/DataX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月19日(星期四) 下午2:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/DataX] 导入到greenplum的时候，如何关闭对gp_max_csv_line_length参数的设置 (#592)





 
@MaxCADog  ，百度链接已失效，能否说一下你是用具体哪个版本的Greenplum驱动来替换postgresql的数据库驱动?

**Comment by chuzi2923** [comment]
> gpdbwriter 是HashDataInc提供的插件，方法如下： 1、下载源码，注释掉那段代码，重新编译下 2、如果不行，我有现成编译好的，可以发给你

你好！请问能将编译好的发给我参考一下吗，十分感谢，我这边实在是编译不过去

**Comment by chuzi2923** [comment]
> 链接：https://pan.baidu.com/s/1oI7BlZ-wEqwOytLiWSnKyw&nbsp; 提取码：qwfw ChangLe ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alibaba/DataX" ***@***.***&gt;; 发送时间:&nbsp;2023年10月19日(星期四) 下午2:50 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [alibaba/DataX] 导入到greenplum的时候，如何关闭对gp_max_csv_line_length参数的设置 (#592) @MaxCADog ，百度链接已失效，能否说一下你是用具体哪个版本的Greenplum驱动来替换postgresql的数据库驱动? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

你好！请问能发我一份参考下解决方案吗，十分感谢

**Comment by MaxCADog** [comment]
链接：https://pan.baidu.com/s/1QfHKBOVbH1WxiX2-dAhr9A&nbsp;
提取码：ryl8

&nbsp;


ChangLe
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月29日(星期五) 上午9:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/DataX] 导入到greenplum的时候，如何关闭对gp_max_csv_line_length参数的设置 (#592)





  
链接：https://pan.baidu.com/s/1oI7BlZ-wEqwOytLiWSnKyw&nbsp; 提取码：qwfw ChangLe @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alibaba/DataX" @.&gt;; 发送时间:&nbsp;2023年10月19日(星期四) 下午2:50 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [alibaba/DataX] 导入到greenplum的时候，如何关闭对gp_max_csv_line_length参数的设置 (#592) @MaxCADog ，百度链接已失效，能否说一下你是用具体哪个版本的Greenplum驱动来替换postgresql的数据库驱动? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt;
  
你好！请问能发我一份参考下解决方案吗，十分感谢
