### ISSUE TITLE
Datax不支持mysql8

### ISSUE THREAD

**Issue by AlanLongYu** [alibaba/DataX#611]
Datax不支持mysql8

**Comment by WeiYe-Jing** [comment]
datax/plugin/mysqlreader/lib 下面的换下驱动就好了

**Comment by AlanLongYu** [comment]
> datax/plugin/mysqlreader/lib 下面的换下驱动就好了

嗯，是的，换了之后没问题了。没有直接HDFS 到clickhouse的么？

**Comment by WeiYe-Jing** [comment]
clickhouse插件有的，你可以到datax web的用户群里问下

**Comment by dingxiaobo** [comment]
DataX 现已支持，欢迎使用新版本
