### ISSUE TITLE
mysql 多数据源配置

### ISSUE THREAD

**Issue by brucelpt** [alibaba/DataX#622]
![image](https://user-images.githubusercontent.com/37991444/77272775-f2371800-6cec-11ea-87e0-b9c61dea69e4.png)
我在官方文档看到，mysqlreader 这个插件可以配置多数据源，但是根据这个配置他们的账户密码需要一致，如果我的账户密码不一致，应该如何配置 json 呢

**Comment by jimmy-bj** [comment]
这个最终是只连接上了一个数据源，不会三个数据源同时建立连接的

**Comment by brucelpt** [comment]
。。项目已经结束很久了，我查看源码自行修改了源码，已经改成可以连接不同数据库，使用不同密码。
开源版本确实是只能用一个账户密码连接你配置的多个数据库。
