### ISSUE TITLE
编译打包失败   库里面没找到对应的文件

### ISSUE THREAD

**Issue by zxcvjl** [alibaba/DataX#637]
Could not find artifact com.alibaba.datax:datax-common:pom:0.0.1-SNAPSHOT in nexus-aliyun (https://maven.aliyun.com/repository/central)

我找了的  也没发现对应的目录

**Comment by xiaoheimei007** [comment]
我也雨大这个问题了

**Comment by xiaoheimei007** [comment]
我也遇到这个问题了，你解决了吗

**Comment by TrafalgarLuo** [comment]
编译命令：
mvn clean package -U -DskipTests assembly:assembly

使用最新代码可以正常编译
