### ISSUE TITLE
clickhousewriter  这个模块的依赖 simulator 中央库 没有啊

### ISSUE THREAD

**Issue by gaoxiong523** [alibaba/DataX#647]
clickhousewriter  这个模块的依赖 simulator 中央库 没有啊

**Comment by ieayoio** [comment]
我也是编译报这个错

**Comment by TravelerAether** [comment]
我也是编译报这个错

**Comment by kevin-yx** [comment]
我也没找到

**Comment by dukeshiny** [comment]
参考这个肯定可以拉 https://github.com/alibaba/DataX/issues/676

**Comment by xinxinzxc** [comment]
clickhousewriter有支持url的负载么？

**Comment by TrafalgarLuo** [comment]
编译命令：
mvn clean package -U -DskipTests assembly:assembly

使用最新代码可以正常编译
