### ISSUE TITLE
db connection资源没释放

### ISSUE THREAD

**Issue by reachyu** [alibaba/DataX#668]
plugin-rdbms-util\src\main\java\com\alibaba\datax\plugin\rdbms\writer\util\OriginalConfPretreatmentUtil.java

103、105、125行，要释放数据库连接
// 检查列是否都为数据库表中正确的列（通过执行一次 select column from table 进行判断）
                DBUtil.getColumnMetaData(connectionFactory.getConnecttion(), oneTable,StringUtils.join(userConfiguredColumns, ","));

**Comment by dingxiaobo** [comment]
Thanks to  @yifanzheng
