### ISSUE TITLE
mysql8之间数据同步报错

### ISSUE THREAD

**Issue by DreamPWJ** [alibaba/DataX#677]
异常信息
![image](https://user-images.githubusercontent.com/16730031/82017285-6373c580-96b5-11ea-8117-9240a4d9dda5.png)
配置信息
![image](https://user-images.githubusercontent.com/16730031/82017534-f6146480-96b5-11ea-9654-8d364e0519f4.png)

**Comment by RiverLiu** [comment]
datax 默认 mysql 驱动是 `5.1.34` 版本，不支持 mysql 8，升级 mysql 驱动到 8.x.x 版本。
P.S 自测尝试替换 mysql-connector-java-8.0.18，问题解决。

**Comment by DreamPWJ** [comment]
写的jdbcurl地址不是数组 是字符串
