### ISSUE TITLE
otsstreamreader依赖的包找不到

### ISSUE THREAD

**Issue by Mysia** [alibaba/DataX#68]
Could not resolve dependencies for project com.alibaba.datax:otsstreamreader:jar:0.0.1-SNAPSHOT

**Comment by deagon** [comment]
@Mysia  I encountered the same situation as you. And I bypassed it by comment the plugin setting in `pom.xml`.

**Comment by HanawaBanana** [comment]
主要是tablestore-streamclient:1.0.0-SNAPSHOT包找不到，SNAPSHOT是内部包，他们发GitHub没改吧。改成1.0.0就ok了。

怀疑这个github项目没有人维护，这个问题早就出现了，略坑。

**Comment by mdzz9527** [comment]
对的

**Comment by mdzz9527** [comment]
我也遇到了

**Comment by ghost** [comment]
这个问题已经修复了为什么我刚刚下载按照guide编译，还会报同样的错？

**Comment by cxzzx007** [comment]
这个问题已经修复了为什么我刚刚下载按照guide编译，还会报同样的错？

**Comment by mdzz9527** [comment]
都散了吧，没人维护的东西

**Comment by TrafalgarLuo** [comment]
编译命令：
mvn clean package -U -DskipTests assembly:assembly

使用最新代码可以正常编译，注意使用 jdk >= 1.8
