### ISSUE TITLE
读 mongo 如何增加加过滤条件？

### ISSUE THREAD

**Issue by TwoThreeWang** [alibaba/DataX#684]
请问读取 mongo 数据时如何添加过滤条件

**Comment by superJazzy** [comment]
老哥，请问咋加的啊？我想添加时间过滤

**Comment by TwoThreeWang** [comment]
> 老哥，请问咋加的啊？我想添加时间过滤

看源码中有 query 配置项

![image](https://user-images.githubusercontent.com/44668468/83493723-c489fe80-a4e7-11ea-982b-2be227dba83e.png)

**Comment by JazzyZhou** [comment]
感谢！

**Comment by superJazzy** [comment]
> > 老哥，请问咋加的啊？我想添加时间过滤
> 
> 看源码中有 query 配置项
> 
> ![image](https://user-images.githubusercontent.com/44668468/83493723-c489fe80-a4e7-11ea-982b-2be227dba83e.png)
感谢！
