### ISSUE TITLE
错误: 找不到或无法加载主类 com.alibaba.datax.core.Engine

### ISSUE THREAD

**Issue by guozhen168** [alibaba/DataX#69]
我在win7 64位系统下部署datax后，在cmd下运行python datax.py ./job/job.json命令后，报错误: 找不到或无法加载主类 com.alibaba.datax.core.Engine

**Comment by guozhen168** [comment]
与 #67 问题一样，已经解决

**Comment by dhgrz** [comment]
怎么解决的？
