### ISSUE TITLE
master分支编译报错

### ISSUE THREAD

**Issue by springCat** [alibaba/DataX#698]
(1)master分支引用的org.apache.common.lang包不存在,看pom应该是要改为引用org.apache.commons.lang3的包,本地修改
(2) 包simulator不存在,maven仓库不存在这个包,可能是阿里内部的包,看scope应该只是在test时引用,注释掉
(3) ClickhouseWriter.java 中的import ru.yandex.clickhouse.ClickHouseTuple 不存在这个包,而且代码中也没有应用,删除
完成上面3步之后运行指导文档上的
mvn -U clean package assembly:assembly -Dmaven.test.skip=true 终于才成功.

**Comment by jzdayz** [comment]
Nice

**Comment by TrafalgarLuo** [comment]
编译命令：
mvn clean package -U -DskipTests assembly:assembly

使用最新代码可以正常编译
