### ISSUE TITLE
hdfswriter缺少truncate删除模式

### ISSUE THREAD

**Issue by zhaojungithub** [alibaba/DataX#7]
经DataX智能分析,该任务最可能的错误原因是:
com.alibaba.datax.common.exception.DataXException: Code:[HdfsWriter-02], Description:[您填写的参数值不合法.]. - 仅支持append, nonConflict两种模式, 不支持您配置的 writeMode 模式 : [truncate]

现在只能支持append和nonConflict两种模式 ,这样如果要覆盖一张表的数据的时候就没法支持了

**Comment by zhaojungithub** [comment]
hdfswriter文当中配置示例如下
                        "writeMode": "truncate",
                        "fieldDelimiter": "\t",
                        "compress":"NONE"
但是使用的时候发现不支持truncate

**Comment by binaryWorld** [comment]
@zhaojungithub 文档中已经说明目前不支持truncate，truncate涉及数据删除，需要用户自己操作～
