### ISSUE TITLE
打包失败，Could not resolve dependencies for project com.alibaba.datax:hdfsreader:jar:0.0.1-SNAPSHOT

### ISSUE THREAD

**Issue by Lydia27hub** [alibaba/DataX#704]
报错
[INFO] --------------------< com.alibaba.datax:hdfsreader >--------------------
[INFO] Building hdfsreader 0.0.1-SNAPSHOT                               [16/55]
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from alimaven: http://maven.aliyun.com/nexus/content/repositories/central/eigenbase/eigenbase-properties/1.1.4/eigenbase-properties-1.1.4.pom
Downloading from nexus-aliyun: http://maven.aliyun.com/nexus/content/groups/public/eigenbase/eigenbase-properties/1.1.4/eigenbase-properties-1.1.4.pom
[WARNING] The POM for eigenbase:eigenbase-properties:jar:1.1.4 is missing, no dependency information available
Downloading from alimaven: http://maven.aliyun.com/nexus/content/repositories/central/org/pentaho/pentaho-aggdesigner-algorithm/5.1.5-jhyde/pentaho-aggdesigner-algorithm-5.1.5-jhyde.pom
Downloading from nexus-aliyun: http://maven.aliyun.com/nexus/content/groups/public/org/pentaho/pentaho-aggdesigner-algorithm/5.1.5-jhyde/pentaho-aggdesigner-algorithm-5.1.5-jhyde.pom
[WARNING] The POM for org.pentaho:pentaho-aggdesigner-algorithm:jar:5.1.5-jhyde is missing, no dependency information available
Downloading from alimaven: http://maven.aliyun.com/nexus/content/repositories/central/org/pentaho/pentaho-aggdesigner-algorithm/5.1.5-jhyde/pentaho-aggdesigner-algorithm-5.1.5-jhyde.jar
Downloading from alimaven: http://maven.aliyun.com/nexus/content/repositories/central/eigenbase/eigenbase-properties/1.1.4/eigenbase-properties-1.1.4.jar
Downloading from nexus-aliyun: http://maven.aliyun.com/nexus/content/groups/public/org/pentaho/pentaho-aggdesigner-algorithm/5.1.5-jhyde/pentaho-aggdesigner-algorithm-5.1.5-jhyde.jar
Downloading from nexus-aliyun: http://maven.aliyun.com/nexus/content/groups/public/eigenbase/eigenbase-properties/1.1.4/eigenbase-properties-1.1.4.jar
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Skipping datax-all
[INFO] This project has been banned from the build due to previous failures.
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] datax-all 0.0.1-SNAPSHOT ........................... SUCCESS [  0.124 s]
[INFO] datax-common ....................................... SUCCESS [  3.365 s]
[INFO] datax-transformer .................................. SUCCESS [  1.796 s]
[INFO] datax-core ......................................... SUCCESS [  5.071 s]
[INFO] plugin-rdbms-util .................................. SUCCESS [  2.023 s]
[INFO] mysqlreader ........................................ SUCCESS [  1.462 s]
[INFO] drdsreader ......................................... SUCCESS [  1.653 s]
[INFO] sqlserverreader .................................... SUCCESS [  1.904 s]
[INFO] postgresqlreader ................................... SUCCESS [  1.306 s]
[INFO] oraclereader ....................................... SUCCESS [  1.524 s]
[INFO] odpsreader ......................................... SUCCESS [  2.936 s]
[INFO] otsreader .......................................... SUCCESS [  3.122 s]
[INFO] otsstreamreader .................................... SUCCESS [  3.154 s]
[INFO] plugin-unstructured-storage-util ................... SUCCESS [  1.612 s]
[INFO] txtfilereader ...................................... SUCCESS [  4.287 s]
[INFO] hdfsreader ......................................... FAILURE [ 13.307 s]
[INFO] streamreader ....................................... SKIPPED
[INFO] ossreader .......................................... SKIPPED
[INFO] ftpreader .......................................... SKIPPED
[INFO] mongodbreader ...................................... SKIPPED
[INFO] rdbmsreader ........................................ SKIPPED
[INFO] hbase11xreader ..................................... SKIPPED
[INFO] hbase094xreader .................................... SKIPPED
[INFO] tsdbreader ......................................... SKIPPED
[INFO] opentsdbreader ..................................... SKIPPED
[INFO] cassandrareader .................................... SKIPPED
[INFO] gdbreader .......................................... SKIPPED
[INFO] mysqlwriter ........................................ SKIPPED
[INFO] drdswriter ......................................... SKIPPED
[INFO] odpswriter ......................................... SKIPPED
[INFO] txtfilewriter ...................................... SKIPPED
[INFO] ftpwriter .......................................... SKIPPED
[INFO] hdfswriter ......................................... SKIPPED
[INFO] streamwriter ....................................... SKIPPED
[INFO] otswriter .......................................... SKIPPED
[INFO] oraclewriter ....................................... SKIPPED
[INFO] sqlserverwriter .................................... SKIPPED
[INFO] postgresqlwriter ................................... SKIPPED
[INFO] osswriter .......................................... SKIPPED
[INFO] mongodbwriter ...................................... SKIPPED
[INFO] adswriter .......................................... SKIPPED
[INFO] ocswriter .......................................... SKIPPED
[INFO] rdbmswriter ........................................ SKIPPED
[INFO] hbase11xwriter ..................................... SKIPPED
[INFO] hbase094xwriter .................................... SKIPPED
[INFO] hbase11xsqlwriter .................................. SKIPPED
[INFO] hbase11xsqlreader .................................. SKIPPED
[INFO] elasticsearchwriter ................................ SKIPPED
[INFO] tsdbwriter ......................................... SKIPPED
[INFO] adbpgwriter ........................................ SKIPPED
[INFO] gdbwriter .......................................... SKIPPED
[INFO] cassandrawriter .................................... SKIPPED
[INFO] clickhousewriter ................................... SKIPPED
[INFO] hbase20xsqlreader .................................. SKIPPED
[INFO] hbase20xsqlwriter 0.0.1-SNAPSHOT ................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 49.388 s
[INFO] Finished at: 2020-06-02T15:44:21+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project hdfsreader: Could not resolve dependencies for project com.alibaba.datax:hdfsreader:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: org.pentaho:pentaho-aggdesigner-algorithm:jar:5.1.5-jhyde, eigenbase:eigenbase-properties:jar:1.1.4: Could not find artifact org.pentaho:pentaho-aggdesigner-algorithm:jar:5.1.5-jhyde in alimaven (http://maven.aliyun.com/nexus/content/repositories/central/) -> [Help 1]

看到issues #49  有说到添加三个mirror打包成功，但是试了没成功，maven配置了好几个mirror,都没下载到这个包

**Comment by Lydia27hub** [comment]
下载了eigenbase-properties和pentaho-aggdesigner-algorithm相关pom及jar包，放在对应的库目录下，并配置了dependency还是报错
[ERROR] Failed to execute goal on project hdfsreader: Could not resolve dependencies for project com.alibaba.datax:hdfsreader:jar:0.0.1-SNAPSHOT: Could not find artifact org.pentaho:pentaho-aggdesigner-algorithm:jar:5.1.5-jhyde in alimaven (http://maven.aliyun.com/nexus/content/repositories/central/)

**Comment by xxz7694** [comment]
你是不是安装的时候在pom文件中把依赖项注释了, 这几个东西不要注释掉
![image](https://user-images.githubusercontent.com/38748747/92425725-a9035380-f1ba-11ea-9e10-213f170c85cf.png)

**Comment by Martwu** [comment]
我遇到了同样的问题，请问下我可以如何配合debug。

**Comment by Martwu** [comment]
```
[INFO] hdfsreader 0.0.1-SNAPSHOT .......................... FAILURE [ 54.758 s]
[INFO] streamreader 0.0.1-SNAPSHOT ........................ SKIPPED
[INFO] ossreader 0.0.1-SNAPSHOT ........................... SKIPPED
[INFO] ftpreader 0.0.1-SNAPSHOT ........................... SKIPPED
[INFO] mongodbreader 0.0.1-SNAPSHOT ....................... SKIPPED
[INFO] rdbmsreader 0.0.1-SNAPSHOT ......................... SKIPPED
[INFO] hbase11xreader 0.0.1-SNAPSHOT ...................... SKIPPED
[INFO] hbase094xreader 0.0.1-SNAPSHOT ..................... SKIPPED
[INFO] tsdbreader 0.0.1-SNAPSHOT .......................... SKIPPED
[INFO] opentsdbreader 0.0.1-SNAPSHOT ...................... SKIPPED
[INFO] cassandrareader 0.0.1-SNAPSHOT ..................... SKIPPED
[INFO] gdbreader 0.0.1-SNAPSHOT ........................... SKIPPED
[INFO] oceanbasev10reader 0.0.1-SNAPSHOT .................. SKIPPED
[INFO] mysqlwriter 0.0.1-SNAPSHOT ......................... SKIPPED
[INFO] drdswriter 0.0.1-SNAPSHOT .......................... SKIPPED
[INFO] odpswriter 0.0.1-SNAPSHOT .......................... SKIPPED
[INFO] txtfilewriter 0.0.1-SNAPSHOT ....................... SKIPPED
[INFO] ftpwriter 0.0.1-SNAPSHOT ........................... SKIPPED
[INFO] hdfswriter 0.0.1-SNAPSHOT .......................... SKIPPED
[INFO] streamwriter 0.0.1-SNAPSHOT ........................ SKIPPED
[INFO] otswriter 0.0.1-SNAPSHOT ........................... SKIPPED
[INFO] oraclewriter 0.0.1-SNAPSHOT ........................ SKIPPED
[INFO] sqlserverwriter 0.0.1-SNAPSHOT ..................... SKIPPED
[INFO] postgresqlwriter 0.0.1-SNAPSHOT .................... SKIPPED
[INFO] kingbaseeswriter 0.0.1-SNAPSHOT .................... SKIPPED
[INFO] osswriter 0.0.1-SNAPSHOT ........................... SKIPPED
[INFO] mongodbwriter 0.0.1-SNAPSHOT ....................... SKIPPED
[INFO] adswriter 0.0.1-SNAPSHOT ........................... SKIPPED
[INFO] ocswriter 0.0.1-SNAPSHOT ........................... SKIPPED
[INFO] rdbmswriter 0.0.1-SNAPSHOT ......................... SKIPPED
[INFO] hbase11xwriter 0.0.1-SNAPSHOT ...................... SKIPPED
[INFO] hbase094xwriter 0.0.1-SNAPSHOT ..................... SKIPPED
[INFO] hbase11xsqlwriter 0.0.1-SNAPSHOT ................... SKIPPED
[INFO] hbase11xsqlreader 0.0.1-SNAPSHOT ................... SKIPPED
[INFO] elasticsearchwriter 0.0.1-SNAPSHOT ................. SKIPPED
[INFO] tsdbwriter 0.0.1-SNAPSHOT .......................... SKIPPED
[INFO] adbpgwriter 0.0.1-SNAPSHOT ......................... SKIPPED
[INFO] gdbwriter 0.0.1-SNAPSHOT ........................... SKIPPED
[INFO] cassandrawriter 0.0.1-SNAPSHOT ..................... SKIPPED
[INFO] clickhousewriter 0.0.1-SNAPSHOT .................... SKIPPED
[INFO] oscarwriter 0.0.1-SNAPSHOT ......................... SKIPPED
[INFO] oceanbasev10writer 0.0.1-SNAPSHOT .................. SKIPPED
[INFO] hbase20xsqlreader 0.0.1-SNAPSHOT ................... SKIPPED
[INFO] hbase20xsqlwriter 0.0.1-SNAPSHOT ................... SKIPPED
[INFO] kuduwriter 0.0.1-SNAPSHOT .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:41 min
[INFO] Finished at: 2021-06-16T14:26:50Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project hdfsreader: Could not resolve dependencies for project com.alibaba.datax:hdfsreader:jar:0.0.1-SNAPSHOT: Could not find artifact org.pentaho:pentaho-aggdesigner-algorithm:jar:5.1.5-jhyde in central (https://maven.aliyun.com/repository/central) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :hdfsreader
```

**Comment by m769963249** [comment]
我解决了这个问题，详细解决过程：
https://blog.csdn.net/qq_39945938/article/details/117959051

**Comment by Martwu** [comment]
> https://blog.csdn.net/qq_39945938/article/details/117959051?

你发的链接404了。

**Comment by m769963249** [comment]
> > https://blog.csdn.net/qq_39945938/article/details/117959051?
> 
> 你发的链接404了。

刚才改了一下博客，现在貌似还在审核过程中

**Comment by m769963249** [comment]
> > > https://blog.csdn.net/qq_39945938/article/details/117959051?
> > 
> > 
> > 你发的链接404了。
> 
> 刚才改了一下博客，现在貌似还在审核过程中

![image](https://user-images.githubusercontent.com/34156607/122315795-5165f580-cf4d-11eb-8d87-0b1b6b3b568e.png)

**Comment by m769963249** [comment]
> > https://blog.csdn.net/qq_39945938/article/details/117959051?
> 
> 你发的链接404了。

现在可以访问到了

**Comment by mxhellor** [comment]
> 我解决了这个问题，详细解决过程：
> https://blog.csdn.net/qq_39945938/article/details/117959051

解决方案太棒了，主要就是那个包找不到，官方文档，唉，好多官方文档都不能让人一次就整好，总是有这样那样的文通

**Comment by TrafalgarLuo** [comment]
编译命令：
mvn clean package -U -DskipTests assembly:assembly

使用最新代码可以正常编译，注意使用 jdk >= 1.8

**Comment by yqzdy1207** [comment]
第一次使用阿里云setting，加速下载该下载的包。第二次注释掉阿里云maven setting，就好了。整体6分半
