### ISSUE TITLE
现在datax是还未支持splitKey为字符串类型吗，我尝试了pg作为源进行同步报错。

### ISSUE THREAD

**Issue by oushu1miaoqing1** [alibaba/DataX#712]
样例数据：
         id
---------------------
 1997-09-21 12:12:12
 1997-09-21 12:13:12
 1999-09-21 12:13:12
 1999-09-21 22:13:12
 1999-09-21 22:13:14
 1999-09-21 22:13:15
 1999-10-21 22:13:15

==========================

 ERROR ReaderRunner - Reader runner Received Exceptions:
com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-06], Description:[执行数据库 Sql 失败, 请检查您的配置的 column/table/where/querySql或者向 DBA 寻求帮助.].  - 执行的SQL为: select id from testzz  where  ('19987OUcU
                                                       t? dLL'' <= id AND id < '1998<_'UeS~5"')  具体错误信息为：org.postgresql.util.PSQLException: ERROR: syntax error at or near ""
  位置：51

**Comment by oushu1miaoqing1** [comment]
我读了源码，发现按照字符串进行分片的时候，就是会出现这类字符，导致jdbc执行sql时where条件筛选出错。

**Comment by oushu1miaoqing1** [comment]
求大佬解答一下:)

**Comment by zmin1217** [comment]
不支持的，文档Readme中说明了.

**Comment by oushu1miaoqing1** [comment]
好的 感谢回复
