### ISSUE TITLE
master使用mvn打包不成功

### ISSUE THREAD

**Issue by zhang-haichao** [alibaba/DataX#727]
1. gdbwriter和gdbreader模块中缺少依赖com.squareup.javapoet
2. clickhousewriter ： com.alibaba.datax.plugin.writer.clickhousewriter.ClickhouseWriter中引入了不存在的类 import ru.yandex.clickhouse.ClickHouseTuple;

**Comment by joy12825** [comment]
Me too! Master branch can't package to use mvn:
 org.pentaho:pentaho-aggdesigner-algorithm:jar:5.1.5-jhyde, eigenbase:eigenbase-properties:jar:1.1.4: Could not find artifact org.pentaho:pentaho-aggdesigner-algorithm:jar:5.1.5-jhyde in nexus-aliyun (http://maven.aliyun.com/nexus/content/groups/public

**Comment by dingxiaobo** [comment]
新版本已修复，欢迎使用新版本
