### ISSUE TITLE
mysql-mysql成功.oraclereader报错找不到CommonRdbmsReader$Job

### ISSUE THREAD

**Issue by sunzheng89701207** [alibaba/DataX#731]
`{
	"content":[
		{
			"reader":{
				"parameter":{
					"password":"****",
					"connection":[
						{
							"querySql":[
								"select ID_,OP_TIME_,ACTION_,MESSAGE_,TENANT_ID,PROC_INST_ID_,TASK_ID_,USER_ID_ from ACT_APPROVAL_INFO"
							],
							"jdbcUrl":[
								"jdbc:oracle:thin:@172.16.36.225:1521:orcl"
							]
						}
					],
					"username":"risk3"
				},
				"name":"oraclereader"
			},
			"writer":{
				"parameter":{
					"password":"****",
					"session":[
						"set session sql_mode='ANSI';"
					],
					"column":[
						"ID_",
						"OP_TIME_",
						"ACTION_",
						"MESSAGE_",
						"TENANT_ID",
						"PROC_INST_ID_",
						"TASK_ID_",
						"USER_ID_"
					],
					"connection":[
						{
							"jdbcUrl":"jdbc:oracle:thin:@172.16.36.225:1521:orcl",
							"table":[
								"oracleTest"
							]
						}
					],
					"writeMode":"insert",
					"username":"risk3",
					"preSql":[
						"truncate table oracleTest"
					]
				},
				"name":"oraclewriter"
			}
		}
	],
	"setting":{
		"errorLimit":{
			"record":1,
			"percentage":0.01
		},
		"speed":{
			"channel":1
		}
	}
}
`
报错信息:ava.lang.NoClassDefFoundError: com/alibaba/datax/plugin/rdbms/reader/CommonRdbmsReader$Job
	at com.alibaba.datax.plugin.reader.oraclereader.OracleReader$Job.init(OracleReader.java:35) ~[oraclereader-0.0.1-20200106.083639-2.jar:na]
![image](https://user-images.githubusercontent.com/42135193/85109854-937a2f80-b244-11ea-9adf-e60a487f2cbe.png)
打开jar包中也没有对应的class文件

**Comment by sunzheng89701207** [comment]
忘记importjar包了

**Comment by yangtiezhu** [comment]
> 

大佬 这个jar 包有吗
