### ISSUE TITLE
HDFS writer 怎么配置启用HA的HDFS

### ISSUE THREAD

**Issue by zxpbenson** [alibaba/DataX#74]
HDFS writer 怎么配置启用HA的HDFS

**Comment by biansutao** [comment]
这个问题是怎么解决的 ？

**Comment by ZzzzZzreal** [comment]
为什么关键的问题没有答案还要关闭两次，是不打算提供这项服务吗

**Comment by a49a** [comment]
https://github.com/alibaba/DataX/blob/master/hdfswriter/doc/hdfswriter.md
文档里有写
