### ISSUE TITLE
wiki 介绍里面，表格的数据写反了

### ISSUE THREAD

**Issue by waylau** [alibaba/DataX#75]
https://github.com/alibaba/DataX/wiki/DataX-Introduction#datax%E7%9B%AE%E5%89%8D%E6%94%AF%E6%8C%81%E7%9A%84%E6%95%B0%E6%8D%AE%E6%BA%90

中 有两条数据，应该是写反了。SqlServerReader	 PostgresqlWriter 和 	PostgresqlReader	   SqlServerWriter

**Comment by binaryWorld** [comment]
已经更新，谢谢指出

**Comment by zhonghuazhi** [comment]
增加这个插件后 也是一样的 不可使用在 Mac上
