### ISSUE TITLE
开发datax插件如何debug，是否必须通过datax.py启动，如果是、在idea里怎么debug？？

### ISSUE THREAD

**Issue by haiying1991** [alibaba/DataX#769]
开发datax插件如何debug，是否必须通过datax.py启动，如果是、在idea里怎么debug？？

**Comment by WeiYe-Jing** [comment]
> 开发datax插件如何debug，是否必须通过datax.py启动，如果是、在idea里怎么debug？？

参考文档：https://github.com/WeiYe-Jing/datax-web/blob/master/doc/datax-web/idea-start-datax.md

**Comment by TrafalgarLuo** [comment]
开区debug日志的方法，可以在命令行增加参数：
datax.py  job.json  --loglevel=debug

如果想要逐行调试，可以启动远程debug，具体方法是增加 -d 参数：
datax.py  job.json -d

在开发环境中启动远程调整，选择合适的ip，port即可

![image](https://user-images.githubusercontent.com/1905000/173319014-046c40ba-3995-4c17-958b-7f65b32cee34.png)
