### ISSUE TITLE
源码编译失败

### ISSUE THREAD

**Issue by amy108** [alibaba/DataX#773]
clickhousewriter的地方编译错误
![image](https://user-images.githubusercontent.com/48902828/88260179-737fd500-ccf6-11ea-996b-3a8f3dc56197.png)

**Comment by Mlng-ZHang** [comment]
去掉simulator依赖，将ClickhouseWriter无用import删掉，就可以了

**Comment by TrafalgarLuo** [comment]
编译命令：
mvn clean package -U -DskipTests assembly:assembly

使用最新代码可以正常编译
