### ISSUE TITLE
DataX钉钉交流群4也已经满了，是否还有其他交流群可以加入？

### ISSUE THREAD

**Issue by ctyytc** [alibaba/DataX#791]
DataX钉钉交流群4也已经满了，是否还有其他交流群可以加入？

**Comment by WeiYe-Jing** [comment]
> DataX钉钉交流群4也已经满了，是否还有其他交流群可以加入？

已更新群二维码

**Comment by ctyytc** [comment]
@WeiYe-Jing 谢谢

**Comment by xuyixun21** [comment]
看不到二维码图片，发个钉钉号吧@WeiYe-Jing
