### ISSUE TITLE
datax 是否可以添加对tidb对支持？

### ISSUE THREAD

**Issue by yubobo** [alibaba/DataX#799]
datax 是否可以添加对tidb对支持？ @TrafalgarLuo @huyahuioo @lixiaoyu-code

**Comment by yubobo** [comment]
tidb支持mysql协议，是否可以直接使用datax。
如果可以这样的话，是否可以在list中注明。

**Comment by VincentSleepless** [comment]
可以直接回流，我们尝试过了，导了几百亿的数据进去，直接用Mysql相关插件即可

**Comment by VincentSleepless** [comment]
jdbc url你们可以让pincap的工程师给你们一些参数建议，带到jdbcurl后面，会有一些提升.
