### ISSUE TITLE
hdfsreader同步orc格式的文件到mysql失败

### ISSUE THREAD

**Issue by zhaojungithub** [alibaba/DataX#8]
hdfsreader配置字段部分为
			"reader":{
				"name":"hdfsreader",
				"parameter":{
					"column":[
						{
							"index":0,
							"type":"string"
						},
						{
							"index":1,
							"type":"long"
						},
						{
							"index":2,
							"type":"long"
						},
						{
							"index":3,
							"type":"long"
						},
						{
							"index":4,
							"type":"string"
						},
						{
							"index":5,
							"type":"string"
						}
					],
执行同步输出日志片段如下。
INFO: Reading ORC rows from hdfs://192.168.201.51/group_sjpt/hive_db/app.db/a_video_stat_vv_time_d_fact/dt=2016-01-05/site_class=APP/000187_0 with {include: null, offset: 0, length: 9223372036854775807}
Jan 12, 2016 6:01:35 PM org.apache.hadoop.hive.ql.io.orc.RecordReaderFactory getMatchingSchema
INFO: Schema is not specified on read. Using file schema.
2016-01-12 18:01:35.861 [0-0-182-reader] ERROR StdoutPluginCollector - 脏数据: 
{"record":[{"byteSize":11,"index":0,"rawData":"auto_iphone","type":"STRING"},{"byteSize":8,"index":1,"rawData":20160105,"type":"LONG"},{"byteSize":7,"index":2,"rawData":1001446,"type":"LONG"},{"byteSize":6,"index":3,"rawData":291380,"type":"LONG"}],"type":"reader"}
2016-01-12 18:01:35.861 [0-0-182-reader] INFO  Reader$Task - end read source files...
...
...

2016-01-12 18:01:38.062 [job-0] INFO  StandAloneJobContainerCommunicator - Total 2 records, 64 bytes | Speed 0B/s, 0 records/s | Error 2 records, 64 bytes |  All Task WaitWriterTime 0.002s |  All Task WaitReaderTime 0.000s | Percentage 100.00%
2016-01-12 18:01:38.064 [job-0] INFO  JobContainer - 
任务启动时刻                    : 2016-01-12 18:00:55
任务结束时刻                    : 2016-01-12 18:01:38
任务总计耗时                    :                 42s
任务平均流量                    :                0B/s
记录写入速度                    :              0rec/s
读出记录总数                    :                   2
读写失败总数                    :                   2

**Comment by zhaojungithub** [comment]
请问这是什么原因呢。 我同步text格式的hdfs文件到mysql正常。同步orc格式的就报上面的错误

**Comment by binaryWorld** [comment]
@zhaojungithub 日志中已经提示这是脏数据了，你看下这条记录{"record":[{"byteSize":11,"index":0,"rawData":"auto_iphone","type":"STRING"},{"byteSize":8,"index":1,"rawData":20160105,"type":"LONG"},{"byteSize":7,"index":2,"rawData":1001446,"type":"LONG"},{"byteSize":6,"index":3,"rawData":291380,"type":"LONG"}],"type":"reader"} 只有4个字段，但你reader配置了6个字段。

**Comment by zhaojungithub** [comment]
多谢，这个问题已经解决了。是因为我reader的配置里面把分区字段也加进去了。
