### ISSUE TITLE
datax可以不强制要求填写password配置么？

### ISSUE THREAD

**Issue by mangolost** [alibaba/DataX#842]
现在如果不填写，
或者写 "password": null
或者空字符串 "password": ""
或者空白 “password": " "，
都会被弹出需要设置password的错误信息

但是我们数据库设置的就是不需要密码
如果password随便填一个，datax这边过关了，数据库那边会报账号密码错误，导致无法使用

这样这边临时只能让DBA设置下给账户加个密码
但是还是希望框架不要强制用户的设置，允许当用户不配置password时，视作空密码处理来访问数据库

**Comment by wgzhao** [comment]
我也有这样的需求，因此 fork [仓库](https://github.com/wgzhao/DataX) 后，增加了这个功能。
具体你可以看 https://datax.readthedocs.io/zh_CN/latest/reader/rdbmsreader.html

**Comment by ZFyuanbanlin** [comment]
"password": "__null__",

**Comment by dingxiaobo** [comment]
DataX运行至今，未在生产环境实践遇到过不带密码的数据库。

建议让DBA创建一个同步专用账号，带密码。

**Comment by jianghuzai** [comment]
我也遇到了同样的问题，从presto执行sql把结果写入doris
我的处理方案比较粗暴：
1. 下载datax源码
2. 根据错误提示定位的到类`plugin-rdbms-util/src/main/java/com/alibaba/datax/plugin/rdbms/reader/util/OriginalConfPretreatmentUtil.java`29行
3. 注视该行检查password的代码
4. 执行命令`mvn -U clean package  -Dmaven.test.skip=true -pl plugin-rdbms-util -am`
5. 替换掉`$DATAX_HOME/plugin/reader/rdbmsreader/libs/`下的plugin-rdbms-util-0.0.1-SNAPSHOT.jar文件

perfect

**Comment by xieting1990** [comment]
> 我也遇到了同样的问题，从presto执行sql把结果写入doris 我的处理方案比较粗暴：
> 
> 1. 下载datax源码
> 2. 根据错误提示定位的到类`plugin-rdbms-util/src/main/java/com/alibaba/datax/plugin/rdbms/reader/util/OriginalConfPretreatmentUtil.java`29行
> 3. 注视该行检查password的代码
> 4. 执行命令`mvn -U clean package  -Dmaven.test.skip=true -pl plugin-rdbms-util -am`
> 5. 替换掉`$DATAX_HOME/plugin/reader/rdbmsreader/libs/`下的plugin-rdbms-util-0.0.1-SNAPSHOT.jar文件
> 
> perfect

我没有改，直接编译也会报错

![Image](https://github.com/user-attachments/assets/a04421dd-eb62-40dd-8c8e-0b368afa83e7)
