### ISSUE TITLE
 clickclickhouse 的 reader模块有支持吗

### ISSUE THREAD

**Issue by lixiaofengCH** [alibaba/DataX#861]
clickclickhouse 的 reader模块有支持吗？

**Comment by Awezome** [comment]
+1

**Comment by wgzhao** [comment]
我增加了[ClickHouse reader](https://github.com/wgzhao/DataX) 插件

**Comment by lixiaofengCH** [comment]
> 我增加了[ClickHouse reader](https://github.com/wgzhao/DataX) 插件

之前有关注过，点赞！
