### ISSUE TITLE
Oracle同步到MySql的问题

### ISSUE THREAD

**Issue by zhangtaohbwh** [alibaba/DataX#877]
我从Oracle同步到MySql时，遇到Oracle不能连接，是什么问题，我的json配置是：
`{
    "job": {
        "setting": {
            "speed": {
                "byte": 1048576
            }, 
            "errorLimit": {
                "record": 0, 
                "percentage": 0.02
            }
        }, 
        "content": [
            {
                "reader": {
                    "name": "oraclereader", 
                    "parameter": {
                        "username": "yxj", 
                        "password": "yxj123456", 
                        "connection": [
                            {
                                "jdbcUrl": [
                                    "jdbc:oracle:thin:@172.16.9.61:1521:orcltb"
                                ], 
                                "querySql": [
                                    "select * from CTB_CI_1024"
                                ]
                            }
                        ]
                    }
                }, 
                "writer": {
                    "name": "mysqlwriter", 
                    "parameter": {
                        "writeMode": "insert", 
                        "username": "root", 
                        "password": "taf2015", 
                        "column": [
                            "*"
                        ], 
                        "session": [
                            "set session sql_mode='ANSI'"
                        ], 
                        "connection": [
                            {
                                "jdbcUrl": "jdbc:mysql://192.168.53.20:3306/db_assist?useUnicode=true&characterEncoding=utf8", 
                                "table": [
                                    "CTB_CI_1024"
                                ]
                            }
                        ]
                    }
                }
            }
        ]
    }
}`

报错信息是：
2020-11-09 17:21:47.438 [main] INFO  JobContainer - Set jobId = 0
2020-11-09 17:21:52.691 [job-0] INFO  OriginalConfPretreatmentUtil - Available jdbcUrl:jdbc:oracle:thin:@172.16.9.61:1521:orcltb.
2020-11-09 17:22:07.825 [job-0] ERROR RetryUtil - Exception when calling callable, 异常Msg:Code:[MYSQLErrCode-02], Description:[数据库服务的IP地址或者Port错误，请检查填写的IP地址和Port或者联系DBA确认IP地址和Port是否正确。如果是同步中心用户请联系DBA确认idb上录入的IP和PORT信息和数据库的当前实际信息是一致的].  -  具体错误信息为：com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
com.alibaba.datax.common.exception.DataXException: Code:[MYSQLErrCode-02], Description:[数据库服务的IP地址或者Port错误，请检查填写的IP地址和Port或者联系DBA确认IP地址和Port是否正确。如果是同步中心用户请联系DBA确认idb上录入的IP和PORT信息和数据库的当前实际信息是一致的].  -  具体错误信息为：com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

java的版本是：java version "1.8.0_161"
不知道是不是连接Oracle的配置有问题，如果有问题，正确的Oracle的配置是什么呢

**Comment by zhangtaohbwh** [comment]
找到原因了

**Comment by ZRRJDD** [comment]
请问是什么原因，我现在 将mysql 同步到 mysql ，同步到 70%左右，就报类似错误

**Comment by haoTimhu** [comment]
请问是什么原因，我遇到的是部署了两机房多个节点，只有一个机房会报这个错误

**Comment by chf-gh** [comment]
> 不知道是不是连接O

找到原因就说一下嘛，搁着儿玩呢，真二
