### ISSUE TITLE
能做到并行了吗？

### ISSUE THREAD

**Issue by sdboy206207** [alibaba/DataX#9]
惊喜的看到datax2.0 开源了。
详细还没看，先问个简单的问题：
taobaocode上原来开源的是多线程并发的。 
现在的版本做到了多进程并行了吗？job和task是怎么定义的

**Comment by binaryWorld** [comment]
@sdboy206207  准确说这是DataX3.0了，现在是支持多进程；一个同步作业就是一个job，根据并发（json中的channel配置）将一个job划分为多个task；

**Comment by sdboy206207** [comment]
还有几个疑问哈，望不吝赐教
1.一个task是一个进程吗？ 2job的切分，只能是用户自动配置划分么，能自动切分吗？
3.与之前的taobaocode上的版本比较，亮点有哪些？ 有没有各种使用的配置模板可看？

**Comment by binaryWorld** [comment]
@sdboy206207  
1、一个task是一个线程；
2、job的切分优先根据用户的配置去做；
3、相对之前的版本，整体架构进行了重新设计：比如
（1）以前DataX 插件运行接口也没有严格区分定义，在DataX 3对插件接口严格区分了定义，并遵循了新的插件编程模型；
（2）以前版本是一Channel/多Reader多/Writer的模型，我们称之为DefaultSlave模型，在DataX 3中，我们废弃了该线程模型，直接内置支持线程模型，即一个Reader/一个Writer/一个Channel模型。
（3）DataX 3提供作业全链路的流量、数据量、脏数据探测和运行时汇报
其它就不详述了
4、每个插件下都有文档模板： 首页有文档链接的～
https://github.com/alibaba/DataX/wiki/DataX-all-data-channels
