### ISSUE TITLE
DataX写入postgresql主键bigserial类型报错

### ISSUE THREAD

**Issue by earthNoah** [alibaba/DataX#906]
DataX写入postgresql主键bigserial类型报错

`[ExecutorJobHandler.reader-132] 2020-12-08 13:50:05.476 [0-0-0-writer] WARN  CommonRdbmsWriter$Task - 回滚此次写入, 采用每次写入一行方式提交. 因为:Batch entry 0 INSERT INTO coupon.coupon_resource (resource_batch_id,coupon_name,resource_batch_state,responsible_person,responsible_mobile,resource_batch_md5,coupon_desc,icon_url,bookkeeping_type,property,issue_num,issued_num,get_max_limit,use_limit,used_num,is_cash_coupon,threshold_type,coupon_amt,sale_amt,discount_money,discount,coupon_type,start_use_time,end_use_time,send_start_time,send_end_time,available_time,delay_time,receive_flag,center_sequence,center_visible,coupon_category,show_start_time,show_end_time,range_type,unavailable_range_type,available_goods,unavailable_goods,store_type,store_codes,channel_id,unavailable_promotion_type,unavailable_price,unavailable_promotion,send_platform,belong_type,resource_alloc_id,create_time,create_pin_name,approval_time,approval_pin_name,abandon_time,update_time,update_pin,mtenant_id,activity_url,sync_state,third_party,print_template,business_type,sms_template,promotion_title_code,unavailable_erppromotion,supplier_ratio) VALUES('21000'::bigserial,'测试 1元现金券'::varchar,'3'::int4,''::varchar,''::varchar,'5957ac4ba24cbf32d4424a41399346f0'::varchar,NULL::text,'http://pmspic-10004025.image.myqcloud.com/6bca5e60-99d3-4aa7-b874-60b2a26f995c'::varchar,'1'::int4,'64'::int4,'1000'::int4,'0'::int4,'10'::int4,'0'::int4,'0'::int4,'1'::int4,'0'::int4,'100'::int4,'0'::int4,'0'::int4,'0'::int4,'3'::int4,NULL::timestamp,NULL::timestamp,NULL::timestamp,'2018-04-18 14:19:48+08'::timestamp,'604800'::int8,'0'::int8,'0'::int4,'0'::int4,'1'::int4,'0'::int8,'1970-01-01 00:00:00+08'::timestamp,'1970-01-01 00:00:00+08'::timestamp,'0'::int4,'0'::int4,'{"":["0199992091"]}
[ExecutorJobHandler.reader-132] '::text,NULL::text,'1'::int4,'{"t":[8000,8001,8002,8017]}
[ExecutorJobHandler.reader-132] '::text,''::text,'4'::int4,''::text,''::text,''::varchar,'1'::int4,''::text,'2018-04-03 14:19:48+08'::timestamp,'System'::varchar,'2018-04-03 14:20:49+08'::timestamp,'frankie'::varchar,'2020-12-07 00:00:00+08'::timestamp,'2018-05-05 01:33:01+08'::timestamp,'system'::varchar,'6'::varchar,''::varchar,'0'::int2,'0'::int4,''::varchar,'1'::int4,''::varchar,''::varchar,''::varchar,''::varchar) was aborted: ERROR: type "bigserial" does not exist
[ExecutorJobHandler.reader-132]   位置：977  Call getNextException to see other errors in the batch.
[ExecutorJobHandler.reader-132] 2020-12-08 13:50:05.509 [0-0-0-writer] ERROR StdoutPluginCollector - 
[ExecutorJobHandler.reader-132] org.postgresql.util.PSQLException: ERROR: type "bigserial" does not exist
[ExecutorJobHandler.reader-132]   位置：977
[ExecutorJobHandler.reader-132] 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497) ~[postgresql-42.2.8.jar:42.2.8]
[ExecutorJobHandler.reader-132] 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233) ~[postgresql-42.2.8.jar:42.2.8]
[ExecutorJobHandler.reader-132] 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310) ~[postgresql-42.2.8.jar:42.2.8]
[ExecutorJobHandler.reader-132] 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446) ~[postgresql-42.2.8.jar:42.2.8]
[ExecutorJobHandler.reader-132] 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370) ~[postgresql-42.2.8.jar:42.2.8]
[ExecutorJobHandler.reader-132] 	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149) ~[postgresql-42.2.8.jar:42.2.8]
[ExecutorJobHandler.reader-132] 	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:138) ~[postgresql-42.2.8.jar:42.2.8]
[ExecutorJobHandler.reader-132] 	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.doOneInsert(CommonRdbmsWriter.java:395) [plugin-rdbms-util-v1.0.4-hashdata.jar:na]
[ExecutorJobHandler.reader-132] 	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:375) [plugin-rdbms-util-v1.0.4-hashdata.jar:na]
[ExecutorJobHandler.reader-132] 	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:304) [plugin-rdbms-util-v1.0.4-hashdata.jar:na]
[ExecutorJobHandler.reader-132] 	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:332) [plugin-rdbms-util-v1.0.4-hashdata.jar:na]
[ExecutorJobHandler.reader-132] 	at com.alibaba.datax.plugin.writer.postgresqlwriter.PostgresqlWriter$Task.startWrite(PostgresqlWriter.java:85) [postgresqlwriter-v1.0.4-hashdata.jar:na]
[ExecutorJobHandler.reader-132] 	at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56) [datax-core-v1.0.4-hashdata.jar:na]
[ExecutorJobHandler.reader-132] 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_275]`

**Comment by dingxiaobo** [comment]
已修复问题： 08cc6dbdca60d1f193614b5de9ecac95bc42828d
