### ISSUE TITLE
写入记录总数统计错误，splits tasks多少个，最终统计就会多出多少条记录

### ISSUE THREAD

**Issue by Galthen** [alibaba/DataX#907]
![image](https://user-images.githubusercontent.com/16739927/101453753-cdfa9480-396a-11eb-841f-c4a97c7c5271.png)

14:56:26.628 [job-0] INFO  c.a.datax.core.job.JobContainer - DataX Reader.Job [mysqlreader] splits to [16] tasks.
14:56:26.629 [job-0] INFO  c.a.datax.core.job.JobContainer - DataX Writer.Job [gpdbwriter] splits to [16] tasks.

这个写入总数有个规律，有多少个线程，就会多出多少数量。(这个写入记录总数来源于CommunicationTool.WRITE_SUCCEED_RECORDS)

**Comment by dopsieee** [comment]
请问问题解决了么，我这边用的 202205 tag的代码，写入的记录数依旧偏多

**Comment by Galthen** [comment]
> 

我不确定官方有没有解决，问题发生在多task的场景下，我当时自己修改代码处理了下，线上目前没有发生问题。可以关注下：
https://github.com/alibaba/DataX/pull/909
