### ISSUE TITLE
postgresqlwriter

### ISSUE THREAD

**Issue by uncle-hu** [alibaba/DataX#910]
机器：32核64线程，128G
参数：channel 4，bytes：1048576
问题：hive向gaussdb写入用postgresqlwriter插件写入，平均速度10kb-20kb，速度很慢，请问有什么优化的方式，或者postgresqlwriter插件中哪里有什么优化的方法

**Comment by Galthen** [comment]
自己写个插件，使用pg的copy实现。
我之前有个跟你类似的情况，我是写道gp，但是官方没有提供gp插件，我就用pg插件写入的，insert into写入很慢。后来找了个开源的gp插件实现了，用的copy from，速度飞升。

**Comment by uncle-hu** [comment]
> 自己写个插件，使用pg的copy实现。
> 我之前有个跟你类似的情况，我是写道gp，但是官方没有提供gp插件，我就用pg插件写入的，insert into写入很慢。后来找了个开源的gp插件实现了，用的copy from，速度飞升。

大佬，有没有微信或者qq交流一下

**Comment by Galthen** [comment]
> > 自己写个插件，使用pg的copy实现。
> > 我之前有个跟你类似的情况，我是写道gp，但是官方没有提供gp插件，我就用pg插件写入的，insert into写入很慢。后来找了个开源的gp插件实现了，用的copy from，速度飞升。
> 
> 大佬，有没有微信或者qq交流一下

额，联系方式不适合公开啊。你可以关注下我的项目，里面有这个GP插件的。

**Comment by uncle-hu** [comment]
> > > 自己写个插件，使用pg的copy实现。
> > > 我之前有个跟你类似的情况，我是写道gp，但是官方没有提供gp插件，我就用pg插件写入的，insert into写入很慢。后来找了个开源的gp插件实现了，用的copy from，速度飞升。
> > 
> > 
> > 大佬，有没有微信或者qq交流一下
> 
> 额，联系方式不适合公开啊。你可以关注下我的项目，里面有这个GP插件的。

我已经给你发邮件了，看一下邮件，就是你现在这个的邮箱
