### ISSUE TITLE
新建DataX钉钉讨论沟通群

### ISSUE THREAD

**Issue by wangxingjian2004** [alibaba/DataX#92]
datax-opensource-dingding.png里面的钉钉群已经失效不能加入了，大家有谁可以新建一个群，一起讨论沟通遇到的问题吗？

**Comment by goushijie** [comment]
好像有

**Comment by wangshaohan1989** [comment]
datax三群也失效了，新建一个新的群吧

**Comment by Git911** [comment]
谁有新群啊

**Comment by TrafalgarLuo** [comment]
目前暂时没有资源扩容管理钉钉群，麻烦有创意的使用问题在github issue反馈吧， 知识点也能给后面的同学带来帮助。
