### ISSUE TITLE
编译时报错

### ISSUE THREAD

**Issue by liuxm6** [alibaba/DataX#920]
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project datax-core: Compilation failure: Compilation failure:
[ERROR] /Users/liuxiaoming/work/git/DataX/core/src/main/java/com/alibaba/datax/core/transport/transformer/FilterTransformer.java:[20,27] 错误: 对Record的引用不明确
[ERROR]   com.alibaba.datax.common.element 中的接口 com.alibaba.datax.common.element.Record 和 java.lang 中的类 java.lang.Record 都匹配
[ERROR] /Users/liuxiaoming/work/git/DataX/core/src/main/java/com/alibaba/datax/core/transport/transformer/FilterTransformer.java:[20,11] 错误: 对Record的引用不明确
[ERROR]   com.alibaba.datax.common.element 中的接口 com.alibaba.datax.common.element.Record 和 java.lang 中的类 java.lang.Record 都匹配
[ERROR] /Users/liuxiaoming/work/git/DataX/core/src/main/java/com/alibaba/datax/core/transport/transformer/FilterTransformer.java:[72,27] 错误: 对Record的引用不明确
[ERROR]   com.alibaba.datax.common.element 中的接口 com.alibaba.datax.common.element.Record 和 java.lang 中的类 java.lang.Record 都匹配
[ERROR] /Users/liuxiaoming/work/git/DataX/core/src/main/java/com/alibaba/datax/core/transport/transformer/FilterTransformer.java:[72,12] 错误: 对Record的引用不明确
[ERROR]   com.alibaba.datax.common.element 中的接口 com.alibaba.datax.common.element.Record 和 java.lang 中的类 java.lang.Record 都匹配
[ERROR] /Users/liuxiaoming/work/git/DataX/core/src/main/java/com/alibaba/datax/core/transport/transformer/FilterTransformer.java:[132,26] 错误: 对Record的引用不明确
[ERROR]   com.alibaba.datax.common.element 中的接口 com.alibaba.datax.common.element.Record 和 java.lang 中的类 java.lang.Record 都匹配
[ERROR] /Users/liuxiaoming/work/git/DataX/core/src/main/java/com/alibaba/datax/core/transport/transformer/FilterTransformer.java:[132,12] 错误: 对Record的引用不明确
[ERROR]   com.alibaba.datax.common.element 中的接口 com.alibaba.datax.common.element.Record 和 java.lang 中的类 java.lang.Record 都匹配
[ERROR] /Users/liuxiaoming/work/git/DataX/core/src/main/java/com/alibaba/datax/core/transport/transformer/FilterTransformer.java:[203,27] 错误: 对Record的引用不明确
[ERROR]   com.alibaba.datax.common.element 中的接口 com.alibaba.datax.common.element.Record 和 java.lang 中的类 java.lang.Record 都匹配
[ERROR] /Users/liuxiaoming/work/git/DataX/core/src/main/java/com/alibaba/datax/core/transport/transformer/FilterTransformer.java:[203,12] 错误: 对Record的引用不明确
[ERROR]   com.alibaba.datax.common.element 中的接口 com.alibaba.datax.common.element.Record 和 java.lang 中的类 java.lang.Record 都匹配
[ERROR] /Users/liuxiaoming/work/git/DataX/core/src/main/java/com/alibaba/datax/core/transport/transformer/FilterTransformer.java:[253,30] 错误: 对Record的引用不明确
[ERROR]   com.alibaba.datax.common.element 中的接口 com.alibaba.datax.common.element.Record 和 java.lang 中的类 java.lang.Record 都匹配
[ERROR] /Users/liuxiaoming/work/git/DataX/core/src/main/java/com/alibaba/datax/core/transport/transformer/FilterTransformer.java:[253,12] 错误: 对Record的引用不明确
[ERROR]   com.alibaba.datax.common.element 中的接口 com.alibaba.datax.common.element.Record 和 java.lang 中的类 java.lang.Record 都匹配
[ERROR] /Users/liuxiaoming/work/git/DataX/core/src/main/java/com/alibaba/datax/core/transport/transformer/FilterTransformer.java:[294,26] 错误: 对Record的引用不明确
[ERROR]   com.alibaba.datax.common.element 中的接口 com.alibaba.datax.common.element.Record 和 java.lang 中的类 java.lang.Record 都匹配
[ERROR] /Users/liuxiaoming/work/git/DataX/core/src/main/java/com/alibaba/datax/core/transport/transformer/FilterTransformer.java:[294,12] 错误: 对Record的引用不明确
[ERROR]   com.alibaba.datax.common.element 中的接口 com.alibaba.datax.common.element.Record 和 java.lang 中的类 java.lang.Record 都匹配
[ERROR] /Users/liuxiaoming/work/git/DataX/core/src/main/java/com/alibaba/datax/core/transport/transformer/FilterTransformer.java:[303,29] 错误: 对Record的引用不明确
[ERROR]   com.alibaba.datax.common.element 中的接口 com.alibaba.datax.common.element.Record 和 java.lang 中的类 java.lang.Record 都匹配
[ERROR] /Users/liuxiaoming/work/git/DataX/core/src/main/java/com/alibaba/datax/core/transport/transformer/FilterTransformer.java:[303,12] 错误: 对Record的引用不明确
[ERROR] -> [Help 1]`

`java version "11.0.8" 2020-07-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.8+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.8+10-LTS, mixed mode)
`

**Comment by fxfng** [comment]
检查下jdk版本是否是1.8的

**Comment by TrafalgarLuo** [comment]
编译命令：
mvn clean package -U -DskipTests assembly:assembly

使用最新代码可以正常编译
