### ISSUE TITLE
datax 读取csv写入Clickhouse时，是否支持csv文件多字符作为行和列的分隔符

### ISSUE THREAD

**Issue by jgswp** [alibaba/DataX#921]
能否支持多字符作为分隔符，比如一个随机字符串

**Comment by whmnoe4j** [comment]
支持吗？

**Comment by jgswp** [comment]
不支持，我自己修改了读写的源码


仰望
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/DataX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月29日(星期一) 中午1:31
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [alibaba/DataX] datax 读取csv写入Clickhouse时，是否支持csv文件多字符作为行和列的分隔符 (#921)





 
支持吗？
