### ISSUE TITLE
读取hdfs上的textfile格式的hive表需要指定源表的所有列以及数据类型（columns配置项），不能直接使用[*]

### ISSUE THREAD

**Issue by xiaozhch5** [alibaba/DataX#929]
读取hdfs上的textfile格式的hive表需要制定源表的所有列以及数据类型，不能直接使用[*]，如果直接使用[*]会报

java.lang.IndexOutOfBoundsException: Index: 9, Size: 9（这里的9是我配置的目标表的列数）。

当我在hdfsreader里面配置了columns之后就可以了。

**Comment by JuniorPainter** [comment]
> 读取hdfs上的textfile格式的hive表需要制定源表的所有列以及数据类型，不能直接使用[_]，如果直接使用[_]会报
> 
> java.lang.IndexOutOfBoundsException: Index: 9, Size: 9（这里的9是我配置的目标表的列数）。
> 
> 当我在hdfsreader里面配置了columns之后就可以了。

是的 我也遇到这个问题  想问一下 您在启动读取文本时 他始终根据数据文本数量去启动线程数 如果数据文本只有一个 他就只会启动一个线程，写入mysql或者gp的时候也只会一个线程去写入，想问下这个问题您有遇到或者解决吗

**Comment by Galthen** [comment]
> 读取hdfs上的textfile格式的hive表需要制定源表的所有列以及数据类型，不能直接使用[_]，如果直接使用[_]会报
> 
> java.lang.IndexOutOfBoundsException: Index: 9, Size: 9（这里的9是我配置的目标表的列数）。
> 
> 当我在hdfsreader里面配置了columns之后就可以了。

Hi，如果hdfsreader是支持星号的，我一直在用："column": ["*"]。
如果你发生了错误，可以提供更多的日志信息，也许官方人员会更了解情况。

**Comment by Galthen** [comment]
> > 读取hdfs上的textfile格式的hive表需要制定源表的所有列以及数据类型，不能直接使用[_]，如果直接使用[_]会报
> > java.lang.IndexOutOfBoundsException: Index: 9, Size: 9（这里的9是我配置的目标表的列数）。
> > 当我在hdfsreader里面配置了columns之后就可以了。
> 
> 是的 我也遇到这个问题 想问一下 您在启动读取文本时 他始终根据数据文本数量去启动线程数 如果数据文本只有一个 他就只会启动一个线程，写入mysql或者gp的时候也只会一个线程去写入，想问下这个问题您有遇到或者解决吗

源代码中默认按照文件数量决定线程数量的，关注下HdfsReader中的split代码。

public List<Configuration> split(int adviceNumber) {

            LOG.info("split() begin...");
            List<Configuration> readerSplitConfigs = new ArrayList<Configuration>();
            // warn:每个slice拖且仅拖一个文件,
            // int splitNumber = adviceNumber;
            int splitNumber = this.sourceFiles.size();
            if (0 == splitNumber) {
                throw DataXException.asDataXException(HdfsReaderErrorCode.EMPTY_DIR_EXCEPTION,
                        String.format("未能找到待读取的文件,请确认您的配置项path: %s", this.readerOriginConfig.getString(Key.PATH)));
            }

            List<List<String>> splitedSourceFiles = this.splitSourceFiles(new ArrayList<String>(this.sourceFiles), splitNumber);
            for (List<String> files : splitedSourceFiles) {
                Configuration splitedConfig = this.readerOriginConfig.clone();
                splitedConfig.set(Constant.SOURCE_FILES, files);
                readerSplitConfigs.add(splitedConfig);
            }

            return readerSplitConfigs;
        }

我建议你修改下splitNumber的拆分数量优先级：channl > fileSize。
