### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.4.1:single (dwzip) on project ossreader:

### ISSUE THREAD

**Issue by lskdegithub** [alibaba/DataX#941]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.4.1:single (dwzip) on project ossreader: Assembly is incorrectly configured: null: Assembly is incorrectly configured: null:
[ERROR] Assembly: null is not configured correctly: Assembly ID must be present and non-empty.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :ossreader

在编译过程中出现这个问题该如何解决呢？恳求大佬帮忙看看

**Comment by AIF333** [comment]
我也碰到了，解决没呢？

**Comment by AIF333** [comment]
我的maven版本是 Apache Maven 3.3.9， 后经高手指定升级到Apache Maven 3.5.4 就可以了

**Comment by han-a1** [comment]
我换成maven3.5.4还是不行
![1648030521(1)](https://user-images.githubusercontent.com/63838901/159676315-20d48f6a-0219-404a-b9fd-6208b3a8cd7b.png)

**Comment by TrafalgarLuo** [comment]
编译命令：
mvn clean package -U -DskipTests assembly:assembly

使用最新代码可以正常编译，注意使用 jdk >= 1.8
