### ISSUE TITLE
datax没维护了？？？？？

### ISSUE THREAD

**Issue by ffyyhh995511** [alibaba/DataX#955]
![lALPBGY17lf7tP3NAkzNBAQ_1028_588](https://user-images.githubusercontent.com/5106973/106412986-e62af380-6483-11eb-97b9-9f3d2a9a33ea.png)

open多余closed

**Comment by tanyo520** [comment]
应该是没维护了

**Comment by TrafalgarLuo** [comment]
目前在定期月度版本更新，有需求可以提交issue。 存量issue会逐步清理完
