### ISSUE TITLE
编译时出错：Failed to execute goal on project oscarwriter: Could not resolve dependencies for project 

### ISSUE THREAD

**Issue by wzzz** [alibaba/DataX#962]
版本33e6ace在编译时报以下错误：
```
[INFO] oscarwriter 0.0.1-SNAPSHOT ......................... FAILURE [  0.003 s]
[INFO] hbase20xsqlreader 0.0.1-SNAPSHOT ................... SKIPPED
[INFO] hbase20xsqlwriter 0.0.1-SNAPSHOT ................... SKIPPED
[INFO] kuduwriter 0.0.1-SNAPSHOT .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:41 min
[INFO] Finished at: 2021-02-07T15:39:03+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project oscarwriter: Could not resolve dependencies for project com.alibaba.datax:oscarwriter:jar:0.0.1-SNAPSHOT: Could not find artifact com.oscar:oscar:jar:7.0.8 at specified path /data/software/DataX/oscarwriter/src/main/lib/oscarJDBC.jar -> [Help 1]
```
错误提示应该是oscarwriter/src/main/lib/oscarJDBC.jar 这个文件不存在，进入该目录下查看确实不存在oscarJDBC.jar这个文件

**Comment by zhouhaolong** [comment]
我也遇到同样的问题

**Comment by zhouhaolong** [comment]
源码里面确实少了oscarwriter/src/main/lib/oscarJDBC.jar这个包，oscar应该是阿里自己用的，我没有用到oscarwriter这个，所以把根目录下的pom.xml里面的oscarwriter给注释掉了，不编译oscarwriter这个module。然后就成功了。

**Comment by wzzz** [comment]
@1471914707 oscarwriter应该是这位老哥开发的吧？

**Comment by zhanghengpei90** [comment]
[ERROR] Failed to execute goal on project oscarwriter: Could not resolve dependencies for project com.alibaba.datax:oscarwriter:jar:0.0.1-SNAPSHOT: Could not find artifact com.oscar:oscar:jar:7.0.8 at specified path /root/DataX/oscarwriter/src/main/lib/oscarJDBC.jar ->
编译打包报错缺少这个包怎么解决呢

**Comment by m769963249** [comment]
我解决了这个问题，详细解决过程：
https://blog.csdn.net/qq_39945938/article/details/117959051?

**Comment by TrafalgarLuo** [comment]
编译命令：
mvn clean package -U -DskipTests assembly:assembly

使用最新代码可以正常编译，注意使用 jdk >= 1.8
