### ISSUE TITLE
有同学开发了doris的读写插件吗

### ISSUE THREAD

**Issue by zhbdesign** [alibaba/DataX#967]
有同学开发了doris的读写插件吗

**Comment by wgzhao** [comment]
Doris 的JDBC驱动兼容MySQL，因此可以尝试直接使用MySQL的 reader/writer 插件连接

**Comment by zhbdesign** [comment]
> Doris 的JDBC驱动兼容MySQL，因此可以尝试直接使用MySQL的 reader/writer 插件连接

Doris是兼容MySQL的，独写使用MySQL插件都可以，但是写入的时候使用insert into的方式，Doris会使用FE节点解析sql，导致速度比较慢，所以有没有什么办法开发独立的，速度比较快的Doris读写插件

**Comment by wgzhao** [comment]
看官方文档只说 insert into 不适合用在生产环境，转而使用 insert into select 方式，现在这种方式不适合 DataX，但是它又不像PostgresSQL那样提供了类似 COPY FROM 这样的高效数据插入方式。

**Comment by zhbdesign** [comment]
> 看官方文档只说 insert into 不适合用在生产环境，转而使用 insert into select 方式，现在这种方式不适合 DataX，但是它又不像PostgresSQL那样提供了类似 COPY FROM 这样的高效数据插入方式。

他们一直推荐使用Stream Load的方式导入，不知道有没有大佬可以内部转换成Stream Load，以此来提高导入速度

**Comment by wgzhao** [comment]
看了下，应该是可以做的，我现在fork的版本(<https://github.com/wgzhao/datax>) 增加的influxdb 就是走到了http读写方式，官方这个例子(<https://github.com/apache/incubator-doris/blob/master/samples/stream_load/java/DorisStreamLoad.java>) 可以提供不少帮助

**Comment by zhbdesign** [comment]
> 看了下，应该是可以做的，我现在fork的版本(https://github.com/wgzhao/datax) 增加的influxdb 就是走到了http读写方式，官方这个例子(https://github.com/apache/incubator-doris/blob/master/samples/stream_load/java/DorisStreamLoad.java) 可以提供不少帮助

大佬能顺便开发一个出来吗

**Comment by wgzhao** [comment]
@zhbdesign 你去我那里提个issue，我怕忘记了

**Comment by dingxiaobo** [comment]
DataX 现已支持 doris write ，欢迎使用新版本
