### ISSUE TITLE
Oracle同步数据到hive问题

### ISSUE THREAD

**Issue by LxqGit-blip** [alibaba/DataX#969]
Oracle同步数据到hive，通过hdfswriter方式进行写入，任务执行完成后，查询表的数据却是空的，会是什么原因导致？

**Comment by xiaodingding-sudo** [comment]
你可能给hive表创建了分区，然而你的datax插件不支持分区的，支持分区的话，网上有解决方案，需要修改源码创建文件，最贱的是不创建分区
