### ISSUE TITLE
Oracle 同步更新到hive问题

### ISSUE THREAD

**Issue by LxqGit-blip** [alibaba/DataX#970]
Oracle通过hdfswriter方式写入到hive表中，当任务执行后，hive表没有同步后的数据，需要刷新元数据才能看到最新的数据，会是什么原因导致呢？

**Comment by VincentSleepless** [comment]
如果hive是非分区表，则写入到hdfs路径可以直接读取数据； 如果hive是分区表，则一定要刷新元数据后才可以读取到数据，建议先同步到一个路径后，用load方式灌进hive分区中;

**Comment by LxqGit-blip** [comment]
如果有hive表有分区字段，按照hdfswrite方式写入后，并没有写进去，刷新元数据后也没有，没有分区字段的话是可以写进去的，这是为什么？也要用load方式才能写进去吗？
