### ISSUE TITLE
编译最新版本错误

### ISSUE THREAD

**Issue by EminemJK** [alibaba/DataX#974]
![image](https://user-images.githubusercontent.com/33885904/109253251-58e08200-782a-11eb-917b-82a78d6ebba3.png)

**Comment by EminemJK** [comment]
可以了，必须安装 jdk 1.8 ，附上下载地址：https://www.jb51.net/softs/691593.html

**Comment by obc-glacier** [comment]
![image](https://user-images.githubusercontent.com/65336955/140678522-cb545a5d-c792-455b-91de-5701695c1d99.png)
不行，我下载了jdk18，还是mvn还是保持record引用不明确，但是直接在导入的时候加入具体的路径，就不报错了，问题是每一个文件都要新增这个Record的路径，就太麻烦了
