### ISSUE TITLE
将数据从不同的分库汇聚到另一个库中，想在数据导入过程中，在目标库的数据中添加该数据来自哪个分库的标示，应该怎么做？

### ISSUE THREAD

**Issue by YCjia** [alibaba/DataX#99]

**Comment by boboChina** [comment]
在你的json的select语句里面加上咯，select 'source_AAA' as sourcetype,BBB,CCC,DDD from table.这不就搞定了么

**Comment by alwayslovejava** [comment]
分库分表读，还有分库分库表写入数据，是怎么配置的？能说下具体的操作方法吗？
